;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem01)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (flight Melbourne Sidney)
     (flight Melbourne London)
     (flight Melbourne Paris)
     (flight Melbourne Berlin)
     (flight Sidney Wellington)
     (flight Sidney Melbourne)
     (flight Sidney Wellington)
     (flight Sidney Beijing)
     (flight Wellington Paris)
     (flight Wellington Tokio)
     (flight Wellington Berlin)
     (flight Beijing Wellington)
     (flight Beijing London)
     (flight Beijing Berlin)
     (flight Beijing Paris)
     (flight Taiwan Beijing)
     (flight Taiwan Nova_Dheli)
     (flight Taiwan Sidney)
     (flight Taiwan Wellington)
     (flight Tokio Berlin)
     (flight Tokio Beijing)
     (flight Tokio Sidney)
     (flight Tokio Berlin)
     (flight Nova_Dheli Taiwan)
     (flight Nova_Dheli Paris)
     (flight Nova_Dheli London)
     (flight Nova_Dheli Taiwan)
     (flight Paris Tokio)
     (flight Paris Melbourne)
     (flight Paris Beijing)
     (flight Paris Nova_Dheli)
     (flight London Sidney)
     (flight London Melbourne)
     (flight London Nova_Dheli)
     (flight London Beijing)
     (flight Berlin Wellington)
     (flight Berlin Melbourne)
     (flight Berlin Nova_Dheli)
     (flight Berlin Sidney)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Sidney)
     (inCity Hotel_Emperor_2 Wellington)
     (inCity Residence_Sky_3 Beijing)
     (inCity Hostel_Delphin_4 Taiwan)
     (inCity Residence_Single_Land_5 Tokio)
     (inCity Resort_Lollipop_6 Nova_Dheli)
     (inCity Hostel_Emperor_7 Paris)
     (inCity Hostel_Lollipop_8 London)
     (inCity Hostel_Single_Land_9 Berlin)
)

(:goal 
     (= (visited-cities) 5)
)


)
