;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem21)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 5)
     (= (minDaysCity Sidney) 2)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 1)
     (= (maxDaysCity Beijing) 4)
     (= (minDaysCity Taiwan) 2)
     (= (maxDaysCity Taiwan) 4)
     (= (minDaysCity Tokio) 2)
     (= (maxDaysCity Tokio) 3)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 3)
     (= (minDaysCity Paris) 2)
     (= (maxDaysCity Paris) 3)
     (= (minDaysCity London) 2)
     (= (maxDaysCity London) 4)
     (= (minDaysCity Berlin) 2)
     (= (maxDaysCity Berlin) 4)
     (= (total-interest) 0)
     (= (cityInterest Melbourne) 1)
     (= (cityInterest Sidney) 1)
     (= (cityInterest Wellington) 1)
     (= (cityInterest Beijing) 3)
     (= (cityInterest Taiwan) 3)
     (= (cityInterest Tokio) 2)
     (= (cityInterest Nova_Dheli) 3)
     (= (cityInterest Paris) 3)
     (= (cityInterest London) 3)
     (= (cityInterest Berlin) 1)
     (flight Melbourne Beijing)
     (flight Melbourne Nova_Dheli)
     (flight Melbourne Sidney)
     (flight Sidney Nova_Dheli)
     (flight Sidney Beijing)
     (flight Sidney Wellington)
     (flight Sidney Melbourne)
     (flight Wellington Nova_Dheli)
     (flight Wellington Sidney)
     (flight Wellington Tokio)
     (flight Wellington Tokio)
     (flight Beijing Taiwan)
     (flight Beijing Paris)
     (flight Beijing Nova_Dheli)
     (flight Beijing Tokio)
     (flight Taiwan Nova_Dheli)
     (flight Taiwan Berlin)
     (flight Taiwan Beijing)
     (flight Taiwan Paris)
     (flight Tokio Taiwan)
     (flight Tokio Wellington)
     (flight Nova_Dheli Taiwan)
     (flight Nova_Dheli Paris)
     (flight Nova_Dheli Taiwan)
     (flight Nova_Dheli Taiwan)
     (flight Paris Beijing)
     (flight Paris Melbourne)
     (flight Paris London)
     (flight London Nova_Dheli)
     (flight London Taiwan)
     (flight Berlin Beijing)
     (flight Berlin Sidney)
     (flight Berlin Taiwan)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Sidney)
     (inCity Hotel_Emperor_2 Wellington)
     (inCity Residence_Sky_3 Beijing)
     (inCity Hostel_Delphin_4 Taiwan)
     (inCity Residence_Single_Land_5 Tokio)
     (inCity Resort_Lollipop_6 Nova_Dheli)
     (inCity Hostel_Emperor_7 Paris)
     (inCity Hostel_Lollipop_8 London)
     (inCity Hostel_Single_Land_9 Berlin)
)

(:goal 
(and (> (visited-cities) 5)
     (> (total-days) 8)
)
)

(:metric minimize (total-interest))

)
