;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem11)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 5)
     (= (minDaysCity Sidney) 2)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 1)
     (= (maxDaysCity Beijing) 4)
     (= (minDaysCity Taiwan) 2)
     (= (maxDaysCity Taiwan) 4)
     (= (minDaysCity Tokio) 2)
     (= (maxDaysCity Tokio) 3)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 3)
     (= (minDaysCity Paris) 2)
     (= (maxDaysCity Paris) 3)
     (= (minDaysCity London) 2)
     (= (maxDaysCity London) 4)
     (= (minDaysCity Berlin) 2)
     (= (maxDaysCity Berlin) 4)
     (flight Melbourne Berlin)
     (flight Melbourne Beijing)
     (flight Melbourne Sidney)
     (flight Melbourne Berlin)
     (flight Sidney Taiwan)
     (flight Sidney Paris)
     (flight Sidney London)
     (flight Sidney Taiwan)
     (flight Wellington Tokio)
     (flight Wellington Melbourne)
     (flight Wellington Beijing)
     (flight Wellington Nova_Dheli)
     (flight Beijing Sidney)
     (flight Beijing Melbourne)
     (flight Beijing Nova_Dheli)
     (flight Taiwan Wellington)
     (flight Taiwan Melbourne)
     (flight Taiwan Nova_Dheli)
     (flight Taiwan Sidney)
     (flight Tokio Taiwan)
     (flight Tokio Paris)
     (flight Nova_Dheli Tokio)
     (flight Nova_Dheli Berlin)
     (flight Paris Beijing)
     (flight Paris Taiwan)
     (flight Paris Tokio)
     (flight London Wellington)
     (flight London Tokio)
     (flight London Taiwan)
     (flight London Paris)
     (flight Berlin Taiwan)
     (flight Berlin Taiwan)
     (flight Berlin Beijing)
     (flight Berlin Melbourne)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Sidney)
     (inCity Hotel_Emperor_2 Wellington)
     (inCity Residence_Sky_3 Beijing)
     (inCity Hostel_Delphin_4 Taiwan)
     (inCity Residence_Single_Land_5 Tokio)
     (inCity Resort_Lollipop_6 Nova_Dheli)
     (inCity Hostel_Emperor_7 Paris)
     (inCity Hostel_Lollipop_8 London)
     (inCity Hostel_Single_Land_9 Berlin)
)

(:goal 
(and (> (visited-cities) 5)
     (> (total-days) 8)
)
)


)
