;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem31)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin Dublin Edinburgh Moscow Krakow Venice Saint_Petersburg Istanbul Rome Caracas Rio_de_Janeiro La_Habana Medellin Cali Washington_DC New_York - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 Apartments_Paradise_10 Resort_Arabiga_11 Hotel_Single_Land_12 Apartments_Single_Land_13 Hotel_Arabiga_14 Residence_Delphin_15 Apartments_Single_Land_16 Residence_Delphin_17 Hostel_Emperor_18 Residence_Paradise_19 Apartments_Delphin_20 Resort_Paradise_21 Residence_Relax_22 Resort_NH_23 Hotel_Chill_24 Hostel_Emperor_25 Hotel_Paradise_26 Apartments_Sky_27 Hotel_Single_Land_28 Hostel_Sky_29 Hotel_Chill_30 Residence_Relax_31 Hotel_Sky_32 Resort_Sky_33 Residence_Emperor_34 Hotel_Relax_35 Hotel_Single_Land_36 Residence_Relax_37 Resort_Relax_38 Hotel_Emperor_39 Apartments_Arabiga_40 Apartments_Sky_41 Resort_NH_42 Hostel_Emperor_43 Resort_Relax_44 Hotel_Single_Land_45 Apartments_Sky_46 Residence_Delphin_47 Hostel_Sky_48 Resort_Relax_49 Hotel_Chill_50 Apartments_Relax_51 Hostel_Arabiga_52 Residence_Arabiga_53 Residence_Arabiga_54 Hostel_Single_Land_55 Hotel_Paradise_56 Hostel_Sky_57 Resort_Chill_58 Resort_Relax_59 Resort_Lollipop_60 Residence_Paradise_61 Hostel_Arabiga_62 Hotel_Paradise_63 Residence_Delphin_64 Hostel_Arabiga_65 Apartments_Arabiga_66 Hotel_Sky_67 Apartments_Sky_68 Resort_Delphin_69 Hostel_NH_70 Resort_Single_Land_71 Resort_Emperor_72 Apartments_Lollipop_73 Hotel_NH_74 Resort_Lollipop_75 Apartments_Sky_76 Hotel_NH_77 Hostel_Sky_78 Hotel_Paradise_79 Apartments_Delphin_80 Apartments_Relax_81 Hotel_Paradise_82 Hotel_Emperor_83 Resort_Relax_84 Resort_Relax_85 Hostel_Arabiga_86 Hostel_Emperor_87 Hotel_Arabiga_88 Hostel_Delphin_89 Hostel_Single_Land_90 Apartments_Arabiga_91 Residence_Chill_92 Hostel_Relax_93 Hotel_NH_94 Residence_Delphin_95 Apartments_Chill_96 Apartments_NH_97 Hostel_Emperor_98 Resort_NH_99 Resort_Sky_100 Apartments_Emperor_101 Apartments_Emperor_102 Hotel_Sky_103 Apartments_Relax_104 Apartments_NH_105 Residence_Delphin_106 Hostel_Arabiga_107 Apartments_Relax_108 Apartments_Lollipop_109 Resort_Lollipop_110 Hotel_Single_Land_111 Hotel_Relax_112 Resort_Chill_113 Hostel_Relax_114 Residence_Delphin_115 Resort_Single_Land_116 Residence_Arabiga_117 Resort_Chill_118 Hostel_NH_119 Apartments_Single_Land_120 Apartments_Delphin_121 Apartments_Sky_122 Residence_Lollipop_123 Hotel_Paradise_124 Hostel_Chill_125 Hotel_Paradise_126 Hotel_NH_127 Hostel_Lollipop_128 Hostel_Relax_129 Hotel_Single_Land_130 Hostel_NH_131 Apartments_Single_Land_132 Residence_Relax_133 Resort_Single_Land_134 Hostel_Lollipop_135 Resort_Single_Land_136 Hotel_Delphin_137 Hostel_NH_138 Hostel_Emperor_139 Hotel_Paradise_140 Resort_Emperor_141 Apartments_Lollipop_142 Hostel_Delphin_143 Hostel_Delphin_144 Apartments_Delphin_145 Apartments_Emperor_146 Hotel_Lollipop_147 Hostel_Sky_148 Hotel_Relax_149 Resort_Lollipop_150 Residence_Sky_151 Residence_Sky_152 Hostel_Chill_153 Apartments_Delphin_154 Residence_Arabiga_155 Residence_NH_156 Resort_Delphin_157 Hotel_Sky_158 Residence_Single_Land_159 Hostel_Sky_160 Residence_Emperor_161 Hotel_Paradise_162 Resort_Delphin_163 Resort_Paradise_164 Hostel_Delphin_165 Residence_Lollipop_166 Apartments_Chill_167 Hotel_Arabiga_168 Apartments_Relax_169 Resort_Lollipop_170 Resort_Single_Land_171 Hostel_Sky_172 Resort_Lollipop_173 Residence_Single_Land_174 Hotel_Single_Land_175 Hotel_Chill_176 Resort_Single_Land_177 Residence_Lollipop_178 Apartments_NH_179 Hotel_NH_180 Hotel_Relax_181 Hostel_Delphin_182 Hostel_Delphin_183 Hotel_Single_Land_184 Resort_Relax_185 Resort_Delphin_186 Hostel_Emperor_187 Hotel_Lollipop_188 Residence_Lollipop_189 Resort_Delphin_190 Hotel_Emperor_191 Residence_Paradise_192 Apartments_Relax_193 Resort_Paradise_194 Resort_Sky_195 Residence_Relax_196 Hostel_Single_Land_197 Hostel_Relax_198 Apartments_Single_Land_199 Resort_NH_200 Apartments_Single_Land_201 Apartments_NH_202 Apartments_Sky_203 Apartments_Emperor_204 Apartments_Emperor_205 Apartments_Emperor_206 Resort_Lollipop_207 Hostel_Arabiga_208 Resort_NH_209 Hostel_Lollipop_210 Residence_NH_211 Hotel_Delphin_212 Apartments_Emperor_213 Residence_Emperor_214 Residence_Emperor_215 Hotel_Sky_216 Hostel_Single_Land_217 Apartments_Chill_218 Resort_Arabiga_219 Hotel_Sky_220 Hostel_Relax_221 Resort_Lollipop_222 Residence_NH_223 Apartments_Lollipop_224 Residence_Sky_225 Residence_Relax_226 Apartments_Delphin_227 Residence_Delphin_228 Apartments_NH_229 Hostel_Lollipop_230 Apartments_Arabiga_231 Hostel_Delphin_232 Resort_Chill_233 Residence_Delphin_234 Residence_Chill_235 Resort_Relax_236 Resort_Delphin_237 Resort_Chill_238 Hotel_Emperor_239 Hotel_Arabiga_240 Hostel_NH_241 Resort_Delphin_242 Apartments_Arabiga_243 Hotel_Single_Land_244 Resort_Emperor_245 Hotel_Delphin_246 Hotel_Single_Land_247 Resort_Paradise_248 Residence_Sky_249 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (stay Dublin) 0)
     (= (stay Edinburgh) 0)
     (= (stay Moscow) 0)
     (= (stay Krakow) 0)
     (= (stay Venice) 0)
     (= (stay Saint_Petersburg) 0)
     (= (stay Istanbul) 0)
     (= (stay Rome) 0)
     (= (stay Caracas) 0)
     (= (stay Rio_de_Janeiro) 0)
     (= (stay La_Habana) 0)
     (= (stay Medellin) 0)
     (= (stay Cali) 0)
     (= (stay Washington_DC) 0)
     (= (stay New_York) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 3)
     (= (minDaysCity Sidney) 1)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 2)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 2)
     (= (maxDaysCity Beijing) 3)
     (= (minDaysCity Taiwan) 1)
     (= (maxDaysCity Taiwan) 3)
     (= (minDaysCity Tokio) 1)
     (= (maxDaysCity Tokio) 3)
     (= (minDaysCity Nova_Dheli) 2)
     (= (maxDaysCity Nova_Dheli) 3)
     (= (minDaysCity Paris) 1)
     (= (maxDaysCity Paris) 4)
     (= (minDaysCity London) 1)
     (= (maxDaysCity London) 5)
     (= (minDaysCity Berlin) 1)
     (= (maxDaysCity Berlin) 5)
     (= (minDaysCity Dublin) 2)
     (= (maxDaysCity Dublin) 5)
     (= (minDaysCity Edinburgh) 1)
     (= (maxDaysCity Edinburgh) 4)
     (= (minDaysCity Moscow) 1)
     (= (maxDaysCity Moscow) 3)
     (= (minDaysCity Krakow) 1)
     (= (maxDaysCity Krakow) 3)
     (= (minDaysCity Venice) 1)
     (= (maxDaysCity Venice) 5)
     (= (minDaysCity Saint_Petersburg) 1)
     (= (maxDaysCity Saint_Petersburg) 4)
     (= (minDaysCity Istanbul) 1)
     (= (maxDaysCity Istanbul) 4)
     (= (minDaysCity Rome) 2)
     (= (maxDaysCity Rome) 4)
     (= (minDaysCity Caracas) 2)
     (= (maxDaysCity Caracas) 3)
     (= (minDaysCity Rio_de_Janeiro) 2)
     (= (maxDaysCity Rio_de_Janeiro) 4)
     (= (minDaysCity La_Habana) 2)
     (= (maxDaysCity La_Habana) 4)
     (= (minDaysCity Medellin) 1)
     (= (maxDaysCity Medellin) 4)
     (= (minDaysCity Cali) 1)
     (= (maxDaysCity Cali) 4)
     (= (minDaysCity Washington_DC) 1)
     (= (maxDaysCity Washington_DC) 5)
     (= (minDaysCity New_York) 1)
     (= (maxDaysCity New_York) 3)
     (= (total-price) 0)
     (= (minPriceTrip) 400)
     (= (maxPriceTrip) 650)
     (= (hotelPrice Hostel_Emperor_0) 15)
     (= (hotelPrice Hotel_Arabiga_1) 24)
     (= (hotelPrice Hotel_Emperor_2) 34)
     (= (hotelPrice Residence_Sky_3) 19)
     (= (hotelPrice Hostel_Delphin_4) 40)
     (= (hotelPrice Residence_Single_Land_5) 16)
     (= (hotelPrice Resort_Lollipop_6) 40)
     (= (hotelPrice Hostel_Emperor_7) 33)
     (= (hotelPrice Hostel_Lollipop_8) 37)
     (= (hotelPrice Hostel_Single_Land_9) 28)
     (= (hotelPrice Apartments_Paradise_10) 23)
     (= (hotelPrice Resort_Arabiga_11) 36)
     (= (hotelPrice Hotel_Single_Land_12) 15)
     (= (hotelPrice Apartments_Single_Land_13) 44)
     (= (hotelPrice Hotel_Arabiga_14) 26)
     (= (hotelPrice Residence_Delphin_15) 17)
     (= (hotelPrice Apartments_Single_Land_16) 41)
     (= (hotelPrice Residence_Delphin_17) 10)
     (= (hotelPrice Hostel_Emperor_18) 44)
     (= (hotelPrice Residence_Paradise_19) 37)
     (= (hotelPrice Apartments_Delphin_20) 10)
     (= (hotelPrice Resort_Paradise_21) 14)
     (= (hotelPrice Residence_Relax_22) 42)
     (= (hotelPrice Resort_NH_23) 28)
     (= (hotelPrice Hotel_Chill_24) 20)
     (= (hotelPrice Hostel_Emperor_25) 43)
     (= (hotelPrice Hotel_Paradise_26) 43)
     (= (hotelPrice Apartments_Sky_27) 18)
     (= (hotelPrice Hotel_Single_Land_28) 28)
     (= (hotelPrice Hostel_Sky_29) 22)
     (= (hotelPrice Hotel_Chill_30) 44)
     (= (hotelPrice Residence_Relax_31) 33)
     (= (hotelPrice Hotel_Sky_32) 37)
     (= (hotelPrice Resort_Sky_33) 33)
     (= (hotelPrice Residence_Emperor_34) 42)
     (= (hotelPrice Hotel_Relax_35) 44)
     (= (hotelPrice Hotel_Single_Land_36) 16)
     (= (hotelPrice Residence_Relax_37) 14)
     (= (hotelPrice Resort_Relax_38) 10)
     (= (hotelPrice Hotel_Emperor_39) 44)
     (= (hotelPrice Apartments_Arabiga_40) 33)
     (= (hotelPrice Apartments_Sky_41) 23)
     (= (hotelPrice Resort_NH_42) 35)
     (= (hotelPrice Hostel_Emperor_43) 38)
     (= (hotelPrice Resort_Relax_44) 34)
     (= (hotelPrice Hotel_Single_Land_45) 28)
     (= (hotelPrice Apartments_Sky_46) 22)
     (= (hotelPrice Residence_Delphin_47) 31)
     (= (hotelPrice Hostel_Sky_48) 28)
     (= (hotelPrice Resort_Relax_49) 33)
     (= (hotelPrice Hotel_Chill_50) 35)
     (= (hotelPrice Apartments_Relax_51) 29)
     (= (hotelPrice Hostel_Arabiga_52) 37)
     (= (hotelPrice Residence_Arabiga_53) 44)
     (= (hotelPrice Residence_Arabiga_54) 24)
     (= (hotelPrice Hostel_Single_Land_55) 13)
     (= (hotelPrice Hotel_Paradise_56) 42)
     (= (hotelPrice Hostel_Sky_57) 34)
     (= (hotelPrice Resort_Chill_58) 33)
     (= (hotelPrice Resort_Relax_59) 37)
     (= (hotelPrice Resort_Lollipop_60) 11)
     (= (hotelPrice Residence_Paradise_61) 32)
     (= (hotelPrice Hostel_Arabiga_62) 37)
     (= (hotelPrice Hotel_Paradise_63) 15)
     (= (hotelPrice Residence_Delphin_64) 32)
     (= (hotelPrice Hostel_Arabiga_65) 11)
     (= (hotelPrice Apartments_Arabiga_66) 27)
     (= (hotelPrice Hotel_Sky_67) 15)
     (= (hotelPrice Apartments_Sky_68) 16)
     (= (hotelPrice Resort_Delphin_69) 27)
     (= (hotelPrice Hostel_NH_70) 14)
     (= (hotelPrice Resort_Single_Land_71) 16)
     (= (hotelPrice Resort_Emperor_72) 17)
     (= (hotelPrice Apartments_Lollipop_73) 16)
     (= (hotelPrice Hotel_NH_74) 21)
     (= (hotelPrice Resort_Lollipop_75) 41)
     (= (hotelPrice Apartments_Sky_76) 12)
     (= (hotelPrice Hotel_NH_77) 10)
     (= (hotelPrice Hostel_Sky_78) 39)
     (= (hotelPrice Hotel_Paradise_79) 30)
     (= (hotelPrice Apartments_Delphin_80) 33)
     (= (hotelPrice Apartments_Relax_81) 30)
     (= (hotelPrice Hotel_Paradise_82) 26)
     (= (hotelPrice Hotel_Emperor_83) 26)
     (= (hotelPrice Resort_Relax_84) 41)
     (= (hotelPrice Resort_Relax_85) 17)
     (= (hotelPrice Hostel_Arabiga_86) 41)
     (= (hotelPrice Hostel_Emperor_87) 39)
     (= (hotelPrice Hotel_Arabiga_88) 41)
     (= (hotelPrice Hostel_Delphin_89) 29)
     (= (hotelPrice Hostel_Single_Land_90) 43)
     (= (hotelPrice Apartments_Arabiga_91) 20)
     (= (hotelPrice Residence_Chill_92) 28)
     (= (hotelPrice Hostel_Relax_93) 36)
     (= (hotelPrice Hotel_NH_94) 25)
     (= (hotelPrice Residence_Delphin_95) 27)
     (= (hotelPrice Apartments_Chill_96) 37)
     (= (hotelPrice Apartments_NH_97) 19)
     (= (hotelPrice Hostel_Emperor_98) 32)
     (= (hotelPrice Resort_NH_99) 20)
     (= (hotelPrice Resort_Sky_100) 36)
     (= (hotelPrice Apartments_Emperor_101) 14)
     (= (hotelPrice Apartments_Emperor_102) 26)
     (= (hotelPrice Hotel_Sky_103) 43)
     (= (hotelPrice Apartments_Relax_104) 32)
     (= (hotelPrice Apartments_NH_105) 14)
     (= (hotelPrice Residence_Delphin_106) 17)
     (= (hotelPrice Hostel_Arabiga_107) 34)
     (= (hotelPrice Apartments_Relax_108) 14)
     (= (hotelPrice Apartments_Lollipop_109) 11)
     (= (hotelPrice Resort_Lollipop_110) 32)
     (= (hotelPrice Hotel_Single_Land_111) 15)
     (= (hotelPrice Hotel_Relax_112) 31)
     (= (hotelPrice Resort_Chill_113) 25)
     (= (hotelPrice Hostel_Relax_114) 43)
     (= (hotelPrice Residence_Delphin_115) 40)
     (= (hotelPrice Resort_Single_Land_116) 33)
     (= (hotelPrice Residence_Arabiga_117) 39)
     (= (hotelPrice Resort_Chill_118) 34)
     (= (hotelPrice Hostel_NH_119) 41)
     (= (hotelPrice Apartments_Single_Land_120) 35)
     (= (hotelPrice Apartments_Delphin_121) 44)
     (= (hotelPrice Apartments_Sky_122) 16)
     (= (hotelPrice Residence_Lollipop_123) 30)
     (= (hotelPrice Hotel_Paradise_124) 35)
     (= (hotelPrice Hostel_Chill_125) 44)
     (= (hotelPrice Hotel_Paradise_126) 24)
     (= (hotelPrice Hotel_NH_127) 28)
     (= (hotelPrice Hostel_Lollipop_128) 18)
     (= (hotelPrice Hostel_Relax_129) 23)
     (= (hotelPrice Hotel_Single_Land_130) 15)
     (= (hotelPrice Hostel_NH_131) 22)
     (= (hotelPrice Apartments_Single_Land_132) 27)
     (= (hotelPrice Residence_Relax_133) 32)
     (= (hotelPrice Resort_Single_Land_134) 32)
     (= (hotelPrice Hostel_Lollipop_135) 15)
     (= (hotelPrice Resort_Single_Land_136) 13)
     (= (hotelPrice Hotel_Delphin_137) 39)
     (= (hotelPrice Hostel_NH_138) 16)
     (= (hotelPrice Hostel_Emperor_139) 18)
     (= (hotelPrice Hotel_Paradise_140) 41)
     (= (hotelPrice Resort_Emperor_141) 38)
     (= (hotelPrice Apartments_Lollipop_142) 23)
     (= (hotelPrice Hostel_Delphin_143) 39)
     (= (hotelPrice Hostel_Delphin_144) 19)
     (= (hotelPrice Apartments_Delphin_145) 33)
     (= (hotelPrice Apartments_Emperor_146) 34)
     (= (hotelPrice Hotel_Lollipop_147) 42)
     (= (hotelPrice Hostel_Sky_148) 27)
     (= (hotelPrice Hotel_Relax_149) 35)
     (= (hotelPrice Resort_Lollipop_150) 38)
     (= (hotelPrice Residence_Sky_151) 29)
     (= (hotelPrice Residence_Sky_152) 35)
     (= (hotelPrice Hostel_Chill_153) 22)
     (= (hotelPrice Apartments_Delphin_154) 14)
     (= (hotelPrice Residence_Arabiga_155) 37)
     (= (hotelPrice Residence_NH_156) 21)
     (= (hotelPrice Resort_Delphin_157) 40)
     (= (hotelPrice Hotel_Sky_158) 32)
     (= (hotelPrice Residence_Single_Land_159) 41)
     (= (hotelPrice Hostel_Sky_160) 18)
     (= (hotelPrice Residence_Emperor_161) 38)
     (= (hotelPrice Hotel_Paradise_162) 18)
     (= (hotelPrice Resort_Delphin_163) 13)
     (= (hotelPrice Resort_Paradise_164) 25)
     (= (hotelPrice Hostel_Delphin_165) 41)
     (= (hotelPrice Residence_Lollipop_166) 30)
     (= (hotelPrice Apartments_Chill_167) 28)
     (= (hotelPrice Hotel_Arabiga_168) 12)
     (= (hotelPrice Apartments_Relax_169) 36)
     (= (hotelPrice Resort_Lollipop_170) 13)
     (= (hotelPrice Resort_Single_Land_171) 20)
     (= (hotelPrice Hostel_Sky_172) 30)
     (= (hotelPrice Resort_Lollipop_173) 38)
     (= (hotelPrice Residence_Single_Land_174) 15)
     (= (hotelPrice Hotel_Single_Land_175) 39)
     (= (hotelPrice Hotel_Chill_176) 26)
     (= (hotelPrice Resort_Single_Land_177) 16)
     (= (hotelPrice Residence_Lollipop_178) 13)
     (= (hotelPrice Apartments_NH_179) 20)
     (= (hotelPrice Hotel_NH_180) 19)
     (= (hotelPrice Hotel_Relax_181) 18)
     (= (hotelPrice Hostel_Delphin_182) 39)
     (= (hotelPrice Hostel_Delphin_183) 21)
     (= (hotelPrice Hotel_Single_Land_184) 30)
     (= (hotelPrice Resort_Relax_185) 20)
     (= (hotelPrice Resort_Delphin_186) 13)
     (= (hotelPrice Hostel_Emperor_187) 18)
     (= (hotelPrice Hotel_Lollipop_188) 15)
     (= (hotelPrice Residence_Lollipop_189) 36)
     (= (hotelPrice Resort_Delphin_190) 15)
     (= (hotelPrice Hotel_Emperor_191) 24)
     (= (hotelPrice Residence_Paradise_192) 29)
     (= (hotelPrice Apartments_Relax_193) 35)
     (= (hotelPrice Resort_Paradise_194) 27)
     (= (hotelPrice Resort_Sky_195) 21)
     (= (hotelPrice Residence_Relax_196) 43)
     (= (hotelPrice Hostel_Single_Land_197) 12)
     (= (hotelPrice Hostel_Relax_198) 16)
     (= (hotelPrice Apartments_Single_Land_199) 11)
     (= (hotelPrice Resort_NH_200) 15)
     (= (hotelPrice Apartments_Single_Land_201) 20)
     (= (hotelPrice Apartments_NH_202) 21)
     (= (hotelPrice Apartments_Sky_203) 35)
     (= (hotelPrice Apartments_Emperor_204) 25)
     (= (hotelPrice Apartments_Emperor_205) 38)
     (= (hotelPrice Apartments_Emperor_206) 41)
     (= (hotelPrice Resort_Lollipop_207) 42)
     (= (hotelPrice Hostel_Arabiga_208) 22)
     (= (hotelPrice Resort_NH_209) 21)
     (= (hotelPrice Hostel_Lollipop_210) 29)
     (= (hotelPrice Residence_NH_211) 31)
     (= (hotelPrice Hotel_Delphin_212) 30)
     (= (hotelPrice Apartments_Emperor_213) 24)
     (= (hotelPrice Residence_Emperor_214) 42)
     (= (hotelPrice Residence_Emperor_215) 27)
     (= (hotelPrice Hotel_Sky_216) 34)
     (= (hotelPrice Hostel_Single_Land_217) 10)
     (= (hotelPrice Apartments_Chill_218) 13)
     (= (hotelPrice Resort_Arabiga_219) 17)
     (= (hotelPrice Hotel_Sky_220) 13)
     (= (hotelPrice Hostel_Relax_221) 30)
     (= (hotelPrice Resort_Lollipop_222) 43)
     (= (hotelPrice Residence_NH_223) 32)
     (= (hotelPrice Apartments_Lollipop_224) 20)
     (= (hotelPrice Residence_Sky_225) 25)
     (= (hotelPrice Residence_Relax_226) 43)
     (= (hotelPrice Apartments_Delphin_227) 19)
     (= (hotelPrice Residence_Delphin_228) 39)
     (= (hotelPrice Apartments_NH_229) 27)
     (= (hotelPrice Hostel_Lollipop_230) 32)
     (= (hotelPrice Apartments_Arabiga_231) 44)
     (= (hotelPrice Hostel_Delphin_232) 37)
     (= (hotelPrice Resort_Chill_233) 20)
     (= (hotelPrice Residence_Delphin_234) 12)
     (= (hotelPrice Residence_Chill_235) 29)
     (= (hotelPrice Resort_Relax_236) 14)
     (= (hotelPrice Resort_Delphin_237) 43)
     (= (hotelPrice Resort_Chill_238) 38)
     (= (hotelPrice Hotel_Emperor_239) 26)
     (= (hotelPrice Hotel_Arabiga_240) 20)
     (= (hotelPrice Hostel_NH_241) 23)
     (= (hotelPrice Resort_Delphin_242) 24)
     (= (hotelPrice Apartments_Arabiga_243) 17)
     (= (hotelPrice Hotel_Single_Land_244) 37)
     (= (hotelPrice Resort_Emperor_245) 33)
     (= (hotelPrice Hotel_Delphin_246) 11)
     (= (hotelPrice Hotel_Single_Land_247) 38)
     (= (hotelPrice Resort_Paradise_248) 33)
     (= (hotelPrice Residence_Sky_249) 14)
     (flight Melbourne Sidney)
     (= (flightPrice Melbourne Sidney) 92)
     (flight Melbourne Wellington)
     (= (flightPrice Melbourne Wellington) 107)
     (flight Melbourne Beijing)
     (= (flightPrice Melbourne Beijing) 104)
     (flight Melbourne Taiwan)
     (= (flightPrice Melbourne Taiwan) 90)
     (flight Melbourne Tokio)
     (= (flightPrice Melbourne Tokio) 106)
     (flight Melbourne Nova_Dheli)
     (= (flightPrice Melbourne Nova_Dheli) 92)
     (flight Melbourne Paris)
     (= (flightPrice Melbourne Paris) 105)
     (flight Melbourne London)
     (= (flightPrice Melbourne London) 82)
     (flight Melbourne Berlin)
     (= (flightPrice Melbourne Berlin) 101)
     (flight Melbourne Dublin)
     (= (flightPrice Melbourne Dublin) 111)
     (flight Melbourne Edinburgh)
     (= (flightPrice Melbourne Edinburgh) 99)
     (flight Melbourne Moscow)
     (= (flightPrice Melbourne Moscow) 88)
     (flight Melbourne Krakow)
     (= (flightPrice Melbourne Krakow) 111)
     (flight Melbourne Venice)
     (= (flightPrice Melbourne Venice) 103)
     (flight Melbourne Saint_Petersburg)
     (= (flightPrice Melbourne Saint_Petersburg) 98)
     (flight Melbourne Istanbul)
     (= (flightPrice Melbourne Istanbul) 113)
     (flight Melbourne Rome)
     (= (flightPrice Melbourne Rome) 87)
     (flight Melbourne Caracas)
     (= (flightPrice Melbourne Caracas) 114)
     (flight Melbourne Rio_de_Janeiro)
     (= (flightPrice Melbourne Rio_de_Janeiro) 88)
     (flight Melbourne La_Habana)
     (= (flightPrice Melbourne La_Habana) 81)
     (flight Melbourne Medellin)
     (= (flightPrice Melbourne Medellin) 107)
     (flight Melbourne Cali)
     (= (flightPrice Melbourne Cali) 110)
     (flight Melbourne Washington_DC)
     (= (flightPrice Melbourne Washington_DC) 94)
     (flight Melbourne New_York)
     (= (flightPrice Melbourne New_York) 98)
     (flight Sidney Melbourne)
     (= (flightPrice Sidney Melbourne) 94)
     (flight Sidney Wellington)
     (= (flightPrice Sidney Wellington) 98)
     (flight Sidney Beijing)
     (= (flightPrice Sidney Beijing) 86)
     (flight Sidney Taiwan)
     (= (flightPrice Sidney Taiwan) 96)
     (flight Sidney Tokio)
     (= (flightPrice Sidney Tokio) 103)
     (flight Sidney Nova_Dheli)
     (= (flightPrice Sidney Nova_Dheli) 110)
     (flight Sidney Paris)
     (= (flightPrice Sidney Paris) 112)
     (flight Sidney London)
     (= (flightPrice Sidney London) 81)
     (flight Sidney Berlin)
     (= (flightPrice Sidney Berlin) 114)
     (flight Sidney Dublin)
     (= (flightPrice Sidney Dublin) 114)
     (flight Sidney Edinburgh)
     (= (flightPrice Sidney Edinburgh) 91)
     (flight Sidney Moscow)
     (= (flightPrice Sidney Moscow) 105)
     (flight Sidney Krakow)
     (= (flightPrice Sidney Krakow) 91)
     (flight Sidney Venice)
     (= (flightPrice Sidney Venice) 94)
     (flight Sidney Saint_Petersburg)
     (= (flightPrice Sidney Saint_Petersburg) 84)
     (flight Sidney Istanbul)
     (= (flightPrice Sidney Istanbul) 89)
     (flight Sidney Rome)
     (= (flightPrice Sidney Rome) 90)
     (flight Sidney Caracas)
     (= (flightPrice Sidney Caracas) 103)
     (flight Sidney Rio_de_Janeiro)
     (= (flightPrice Sidney Rio_de_Janeiro) 109)
     (flight Sidney La_Habana)
     (= (flightPrice Sidney La_Habana) 98)
     (flight Sidney Medellin)
     (= (flightPrice Sidney Medellin) 91)
     (flight Sidney Cali)
     (= (flightPrice Sidney Cali) 104)
     (flight Sidney Washington_DC)
     (= (flightPrice Sidney Washington_DC) 108)
     (flight Sidney New_York)
     (= (flightPrice Sidney New_York) 99)
     (flight Wellington Melbourne)
     (= (flightPrice Wellington Melbourne) 81)
     (flight Wellington Sidney)
     (= (flightPrice Wellington Sidney) 82)
     (flight Wellington Beijing)
     (= (flightPrice Wellington Beijing) 112)
     (flight Wellington Taiwan)
     (= (flightPrice Wellington Taiwan) 108)
     (flight Wellington Tokio)
     (= (flightPrice Wellington Tokio) 112)
     (flight Wellington Nova_Dheli)
     (= (flightPrice Wellington Nova_Dheli) 91)
     (flight Wellington Paris)
     (= (flightPrice Wellington Paris) 92)
     (flight Wellington London)
     (= (flightPrice Wellington London) 92)
     (flight Wellington Berlin)
     (= (flightPrice Wellington Berlin) 86)
     (flight Wellington Dublin)
     (= (flightPrice Wellington Dublin) 110)
     (flight Wellington Edinburgh)
     (= (flightPrice Wellington Edinburgh) 85)
     (flight Wellington Moscow)
     (= (flightPrice Wellington Moscow) 109)
     (flight Wellington Krakow)
     (= (flightPrice Wellington Krakow) 105)
     (flight Wellington Venice)
     (= (flightPrice Wellington Venice) 94)
     (flight Wellington Saint_Petersburg)
     (= (flightPrice Wellington Saint_Petersburg) 110)
     (flight Wellington Istanbul)
     (= (flightPrice Wellington Istanbul) 81)
     (flight Wellington Rome)
     (= (flightPrice Wellington Rome) 93)
     (flight Wellington Caracas)
     (= (flightPrice Wellington Caracas) 87)
     (flight Wellington Rio_de_Janeiro)
     (= (flightPrice Wellington Rio_de_Janeiro) 84)
     (flight Wellington La_Habana)
     (= (flightPrice Wellington La_Habana) 81)
     (flight Wellington Medellin)
     (= (flightPrice Wellington Medellin) 101)
     (flight Wellington Cali)
     (= (flightPrice Wellington Cali) 88)
     (flight Wellington Washington_DC)
     (= (flightPrice Wellington Washington_DC) 90)
     (flight Wellington New_York)
     (= (flightPrice Wellington New_York) 88)
     (flight Beijing Melbourne)
     (= (flightPrice Beijing Melbourne) 112)
     (flight Beijing Sidney)
     (= (flightPrice Beijing Sidney) 96)
     (flight Beijing Wellington)
     (= (flightPrice Beijing Wellington) 107)
     (flight Beijing Taiwan)
     (= (flightPrice Beijing Taiwan) 100)
     (flight Beijing Tokio)
     (= (flightPrice Beijing Tokio) 86)
     (flight Beijing Nova_Dheli)
     (= (flightPrice Beijing Nova_Dheli) 100)
     (flight Beijing Paris)
     (= (flightPrice Beijing Paris) 84)
     (flight Beijing London)
     (= (flightPrice Beijing London) 87)
     (flight Beijing Berlin)
     (= (flightPrice Beijing Berlin) 102)
     (flight Beijing Dublin)
     (= (flightPrice Beijing Dublin) 81)
     (flight Beijing Edinburgh)
     (= (flightPrice Beijing Edinburgh) 92)
     (flight Beijing Moscow)
     (= (flightPrice Beijing Moscow) 112)
     (flight Beijing Krakow)
     (= (flightPrice Beijing Krakow) 104)
     (flight Beijing Venice)
     (= (flightPrice Beijing Venice) 81)
     (flight Beijing Saint_Petersburg)
     (= (flightPrice Beijing Saint_Petersburg) 101)
     (flight Beijing Istanbul)
     (= (flightPrice Beijing Istanbul) 110)
     (flight Beijing Rome)
     (= (flightPrice Beijing Rome) 112)
     (flight Beijing Caracas)
     (= (flightPrice Beijing Caracas) 83)
     (flight Beijing Rio_de_Janeiro)
     (= (flightPrice Beijing Rio_de_Janeiro) 105)
     (flight Beijing La_Habana)
     (= (flightPrice Beijing La_Habana) 114)
     (flight Beijing Medellin)
     (= (flightPrice Beijing Medellin) 97)
     (flight Beijing Cali)
     (= (flightPrice Beijing Cali) 112)
     (flight Beijing Washington_DC)
     (= (flightPrice Beijing Washington_DC) 93)
     (flight Beijing New_York)
     (= (flightPrice Beijing New_York) 111)
     (flight Taiwan Melbourne)
     (= (flightPrice Taiwan Melbourne) 84)
     (flight Taiwan Sidney)
     (= (flightPrice Taiwan Sidney) 97)
     (flight Taiwan Wellington)
     (= (flightPrice Taiwan Wellington) 89)
     (flight Taiwan Beijing)
     (= (flightPrice Taiwan Beijing) 82)
     (flight Taiwan Tokio)
     (= (flightPrice Taiwan Tokio) 82)
     (flight Taiwan Nova_Dheli)
     (= (flightPrice Taiwan Nova_Dheli) 112)
     (flight Taiwan Paris)
     (= (flightPrice Taiwan Paris) 91)
     (flight Taiwan London)
     (= (flightPrice Taiwan London) 91)
     (flight Taiwan Berlin)
     (= (flightPrice Taiwan Berlin) 93)
     (flight Taiwan Dublin)
     (= (flightPrice Taiwan Dublin) 95)
     (flight Taiwan Edinburgh)
     (= (flightPrice Taiwan Edinburgh) 112)
     (flight Taiwan Moscow)
     (= (flightPrice Taiwan Moscow) 111)
     (flight Taiwan Krakow)
     (= (flightPrice Taiwan Krakow) 80)
     (flight Taiwan Venice)
     (= (flightPrice Taiwan Venice) 81)
     (flight Taiwan Saint_Petersburg)
     (= (flightPrice Taiwan Saint_Petersburg) 95)
     (flight Taiwan Istanbul)
     (= (flightPrice Taiwan Istanbul) 80)
     (flight Taiwan Rome)
     (= (flightPrice Taiwan Rome) 95)
     (flight Taiwan Caracas)
     (= (flightPrice Taiwan Caracas) 108)
     (flight Taiwan Rio_de_Janeiro)
     (= (flightPrice Taiwan Rio_de_Janeiro) 89)
     (flight Taiwan La_Habana)
     (= (flightPrice Taiwan La_Habana) 96)
     (flight Taiwan Medellin)
     (= (flightPrice Taiwan Medellin) 86)
     (flight Taiwan Cali)
     (= (flightPrice Taiwan Cali) 110)
     (flight Taiwan Washington_DC)
     (= (flightPrice Taiwan Washington_DC) 92)
     (flight Taiwan New_York)
     (= (flightPrice Taiwan New_York) 95)
     (flight Tokio Melbourne)
     (= (flightPrice Tokio Melbourne) 113)
     (flight Tokio Sidney)
     (= (flightPrice Tokio Sidney) 94)
     (flight Tokio Wellington)
     (= (flightPrice Tokio Wellington) 95)
     (flight Tokio Beijing)
     (= (flightPrice Tokio Beijing) 95)
     (flight Tokio Taiwan)
     (= (flightPrice Tokio Taiwan) 91)
     (flight Tokio Nova_Dheli)
     (= (flightPrice Tokio Nova_Dheli) 85)
     (flight Tokio Paris)
     (= (flightPrice Tokio Paris) 103)
     (flight Tokio London)
     (= (flightPrice Tokio London) 108)
     (flight Tokio Berlin)
     (= (flightPrice Tokio Berlin) 102)
     (flight Tokio Dublin)
     (= (flightPrice Tokio Dublin) 113)
     (flight Tokio Edinburgh)
     (= (flightPrice Tokio Edinburgh) 87)
     (flight Tokio Moscow)
     (= (flightPrice Tokio Moscow) 81)
     (flight Tokio Krakow)
     (= (flightPrice Tokio Krakow) 110)
     (flight Tokio Venice)
     (= (flightPrice Tokio Venice) 110)
     (flight Tokio Saint_Petersburg)
     (= (flightPrice Tokio Saint_Petersburg) 93)
     (flight Tokio Istanbul)
     (= (flightPrice Tokio Istanbul) 100)
     (flight Tokio Rome)
     (= (flightPrice Tokio Rome) 90)
     (flight Tokio Caracas)
     (= (flightPrice Tokio Caracas) 90)
     (flight Tokio Rio_de_Janeiro)
     (= (flightPrice Tokio Rio_de_Janeiro) 97)
     (flight Tokio La_Habana)
     (= (flightPrice Tokio La_Habana) 103)
     (flight Tokio Medellin)
     (= (flightPrice Tokio Medellin) 103)
     (flight Tokio Cali)
     (= (flightPrice Tokio Cali) 112)
     (flight Tokio Washington_DC)
     (= (flightPrice Tokio Washington_DC) 103)
     (flight Tokio New_York)
     (= (flightPrice Tokio New_York) 95)
     (flight Nova_Dheli Melbourne)
     (= (flightPrice Nova_Dheli Melbourne) 82)
     (flight Nova_Dheli Sidney)
     (= (flightPrice Nova_Dheli Sidney) 112)
     (flight Nova_Dheli Wellington)
     (= (flightPrice Nova_Dheli Wellington) 112)
     (flight Nova_Dheli Beijing)
     (= (flightPrice Nova_Dheli Beijing) 101)
     (flight Nova_Dheli Taiwan)
     (= (flightPrice Nova_Dheli Taiwan) 84)
     (flight Nova_Dheli Tokio)
     (= (flightPrice Nova_Dheli Tokio) 101)
     (flight Nova_Dheli Paris)
     (= (flightPrice Nova_Dheli Paris) 81)
     (flight Nova_Dheli London)
     (= (flightPrice Nova_Dheli London) 94)
     (flight Nova_Dheli Berlin)
     (= (flightPrice Nova_Dheli Berlin) 80)
     (flight Nova_Dheli Dublin)
     (= (flightPrice Nova_Dheli Dublin) 108)
     (flight Nova_Dheli Edinburgh)
     (= (flightPrice Nova_Dheli Edinburgh) 109)
     (flight Nova_Dheli Moscow)
     (= (flightPrice Nova_Dheli Moscow) 103)
     (flight Nova_Dheli Krakow)
     (= (flightPrice Nova_Dheli Krakow) 113)
     (flight Nova_Dheli Venice)
     (= (flightPrice Nova_Dheli Venice) 110)
     (flight Nova_Dheli Saint_Petersburg)
     (= (flightPrice Nova_Dheli Saint_Petersburg) 108)
     (flight Nova_Dheli Istanbul)
     (= (flightPrice Nova_Dheli Istanbul) 112)
     (flight Nova_Dheli Rome)
     (= (flightPrice Nova_Dheli Rome) 85)
     (flight Nova_Dheli Caracas)
     (= (flightPrice Nova_Dheli Caracas) 81)
     (flight Nova_Dheli Rio_de_Janeiro)
     (= (flightPrice Nova_Dheli Rio_de_Janeiro) 114)
     (flight Nova_Dheli La_Habana)
     (= (flightPrice Nova_Dheli La_Habana) 92)
     (flight Nova_Dheli Medellin)
     (= (flightPrice Nova_Dheli Medellin) 111)
     (flight Nova_Dheli Cali)
     (= (flightPrice Nova_Dheli Cali) 92)
     (flight Nova_Dheli Washington_DC)
     (= (flightPrice Nova_Dheli Washington_DC) 112)
     (flight Nova_Dheli New_York)
     (= (flightPrice Nova_Dheli New_York) 99)
     (flight Paris Melbourne)
     (= (flightPrice Paris Melbourne) 102)
     (flight Paris Sidney)
     (= (flightPrice Paris Sidney) 106)
     (flight Paris Wellington)
     (= (flightPrice Paris Wellington) 87)
     (flight Paris Beijing)
     (= (flightPrice Paris Beijing) 102)
     (flight Paris Taiwan)
     (= (flightPrice Paris Taiwan) 81)
     (flight Paris Tokio)
     (= (flightPrice Paris Tokio) 110)
     (flight Paris Nova_Dheli)
     (= (flightPrice Paris Nova_Dheli) 83)
     (flight Paris London)
     (= (flightPrice Paris London) 83)
     (flight Paris Berlin)
     (= (flightPrice Paris Berlin) 84)
     (flight Paris Dublin)
     (= (flightPrice Paris Dublin) 80)
     (flight Paris Edinburgh)
     (= (flightPrice Paris Edinburgh) 81)
     (flight Paris Moscow)
     (= (flightPrice Paris Moscow) 100)
     (flight Paris Krakow)
     (= (flightPrice Paris Krakow) 101)
     (flight Paris Venice)
     (= (flightPrice Paris Venice) 83)
     (flight Paris Saint_Petersburg)
     (= (flightPrice Paris Saint_Petersburg) 114)
     (flight Paris Istanbul)
     (= (flightPrice Paris Istanbul) 113)
     (flight Paris Rome)
     (= (flightPrice Paris Rome) 88)
     (flight Paris Caracas)
     (= (flightPrice Paris Caracas) 108)
     (flight Paris Rio_de_Janeiro)
     (= (flightPrice Paris Rio_de_Janeiro) 113)
     (flight Paris La_Habana)
     (= (flightPrice Paris La_Habana) 87)
     (flight Paris Medellin)
     (= (flightPrice Paris Medellin) 80)
     (flight Paris Cali)
     (= (flightPrice Paris Cali) 107)
     (flight Paris Washington_DC)
     (= (flightPrice Paris Washington_DC) 84)
     (flight Paris New_York)
     (= (flightPrice Paris New_York) 85)
     (flight London Melbourne)
     (= (flightPrice London Melbourne) 85)
     (flight London Sidney)
     (= (flightPrice London Sidney) 95)
     (flight London Wellington)
     (= (flightPrice London Wellington) 97)
     (flight London Beijing)
     (= (flightPrice London Beijing) 93)
     (flight London Taiwan)
     (= (flightPrice London Taiwan) 107)
     (flight London Tokio)
     (= (flightPrice London Tokio) 107)
     (flight London Nova_Dheli)
     (= (flightPrice London Nova_Dheli) 112)
     (flight London Paris)
     (= (flightPrice London Paris) 106)
     (flight London Berlin)
     (= (flightPrice London Berlin) 98)
     (flight London Dublin)
     (= (flightPrice London Dublin) 84)
     (flight London Edinburgh)
     (= (flightPrice London Edinburgh) 94)
     (flight London Moscow)
     (= (flightPrice London Moscow) 99)
     (flight London Krakow)
     (= (flightPrice London Krakow) 91)
     (flight London Venice)
     (= (flightPrice London Venice) 109)
     (flight London Saint_Petersburg)
     (= (flightPrice London Saint_Petersburg) 80)
     (flight London Istanbul)
     (= (flightPrice London Istanbul) 107)
     (flight London Rome)
     (= (flightPrice London Rome) 109)
     (flight London Caracas)
     (= (flightPrice London Caracas) 81)
     (flight London Rio_de_Janeiro)
     (= (flightPrice London Rio_de_Janeiro) 92)
     (flight London La_Habana)
     (= (flightPrice London La_Habana) 107)
     (flight London Medellin)
     (= (flightPrice London Medellin) 96)
     (flight London Cali)
     (= (flightPrice London Cali) 91)
     (flight London Washington_DC)
     (= (flightPrice London Washington_DC) 82)
     (flight London New_York)
     (= (flightPrice London New_York) 105)
     (flight Berlin Melbourne)
     (= (flightPrice Berlin Melbourne) 97)
     (flight Berlin Sidney)
     (= (flightPrice Berlin Sidney) 92)
     (flight Berlin Wellington)
     (= (flightPrice Berlin Wellington) 89)
     (flight Berlin Beijing)
     (= (flightPrice Berlin Beijing) 97)
     (flight Berlin Taiwan)
     (= (flightPrice Berlin Taiwan) 84)
     (flight Berlin Tokio)
     (= (flightPrice Berlin Tokio) 93)
     (flight Berlin Nova_Dheli)
     (= (flightPrice Berlin Nova_Dheli) 80)
     (flight Berlin Paris)
     (= (flightPrice Berlin Paris) 101)
     (flight Berlin London)
     (= (flightPrice Berlin London) 86)
     (flight Berlin Dublin)
     (= (flightPrice Berlin Dublin) 109)
     (flight Berlin Edinburgh)
     (= (flightPrice Berlin Edinburgh) 80)
     (flight Berlin Moscow)
     (= (flightPrice Berlin Moscow) 113)
     (flight Berlin Krakow)
     (= (flightPrice Berlin Krakow) 101)
     (flight Berlin Venice)
     (= (flightPrice Berlin Venice) 112)
     (flight Berlin Saint_Petersburg)
     (= (flightPrice Berlin Saint_Petersburg) 82)
     (flight Berlin Istanbul)
     (= (flightPrice Berlin Istanbul) 97)
     (flight Berlin Rome)
     (= (flightPrice Berlin Rome) 94)
     (flight Berlin Caracas)
     (= (flightPrice Berlin Caracas) 108)
     (flight Berlin Rio_de_Janeiro)
     (= (flightPrice Berlin Rio_de_Janeiro) 81)
     (flight Berlin La_Habana)
     (= (flightPrice Berlin La_Habana) 105)
     (flight Berlin Medellin)
     (= (flightPrice Berlin Medellin) 102)
     (flight Berlin Cali)
     (= (flightPrice Berlin Cali) 81)
     (flight Berlin Washington_DC)
     (= (flightPrice Berlin Washington_DC) 110)
     (flight Berlin New_York)
     (= (flightPrice Berlin New_York) 96)
     (flight Dublin Melbourne)
     (= (flightPrice Dublin Melbourne) 95)
     (flight Dublin Sidney)
     (= (flightPrice Dublin Sidney) 87)
     (flight Dublin Wellington)
     (= (flightPrice Dublin Wellington) 100)
     (flight Dublin Beijing)
     (= (flightPrice Dublin Beijing) 111)
     (flight Dublin Taiwan)
     (= (flightPrice Dublin Taiwan) 99)
     (flight Dublin Tokio)
     (= (flightPrice Dublin Tokio) 102)
     (flight Dublin Nova_Dheli)
     (= (flightPrice Dublin Nova_Dheli) 101)
     (flight Dublin Paris)
     (= (flightPrice Dublin Paris) 93)
     (flight Dublin London)
     (= (flightPrice Dublin London) 91)
     (flight Dublin Berlin)
     (= (flightPrice Dublin Berlin) 87)
     (flight Dublin Edinburgh)
     (= (flightPrice Dublin Edinburgh) 110)
     (flight Dublin Moscow)
     (= (flightPrice Dublin Moscow) 96)
     (flight Dublin Krakow)
     (= (flightPrice Dublin Krakow) 113)
     (flight Dublin Venice)
     (= (flightPrice Dublin Venice) 87)
     (flight Dublin Saint_Petersburg)
     (= (flightPrice Dublin Saint_Petersburg) 94)
     (flight Dublin Istanbul)
     (= (flightPrice Dublin Istanbul) 84)
     (flight Dublin Rome)
     (= (flightPrice Dublin Rome) 82)
     (flight Dublin Caracas)
     (= (flightPrice Dublin Caracas) 94)
     (flight Dublin Rio_de_Janeiro)
     (= (flightPrice Dublin Rio_de_Janeiro) 94)
     (flight Dublin La_Habana)
     (= (flightPrice Dublin La_Habana) 80)
     (flight Dublin Medellin)
     (= (flightPrice Dublin Medellin) 104)
     (flight Dublin Cali)
     (= (flightPrice Dublin Cali) 96)
     (flight Dublin Washington_DC)
     (= (flightPrice Dublin Washington_DC) 97)
     (flight Dublin New_York)
     (= (flightPrice Dublin New_York) 83)
     (flight Edinburgh Melbourne)
     (= (flightPrice Edinburgh Melbourne) 89)
     (flight Edinburgh Sidney)
     (= (flightPrice Edinburgh Sidney) 111)
     (flight Edinburgh Wellington)
     (= (flightPrice Edinburgh Wellington) 85)
     (flight Edinburgh Beijing)
     (= (flightPrice Edinburgh Beijing) 111)
     (flight Edinburgh Taiwan)
     (= (flightPrice Edinburgh Taiwan) 89)
     (flight Edinburgh Tokio)
     (= (flightPrice Edinburgh Tokio) 80)
     (flight Edinburgh Nova_Dheli)
     (= (flightPrice Edinburgh Nova_Dheli) 104)
     (flight Edinburgh Paris)
     (= (flightPrice Edinburgh Paris) 104)
     (flight Edinburgh London)
     (= (flightPrice Edinburgh London) 100)
     (flight Edinburgh Berlin)
     (= (flightPrice Edinburgh Berlin) 89)
     (flight Edinburgh Dublin)
     (= (flightPrice Edinburgh Dublin) 101)
     (flight Edinburgh Moscow)
     (= (flightPrice Edinburgh Moscow) 96)
     (flight Edinburgh Krakow)
     (= (flightPrice Edinburgh Krakow) 88)
     (flight Edinburgh Venice)
     (= (flightPrice Edinburgh Venice) 99)
     (flight Edinburgh Saint_Petersburg)
     (= (flightPrice Edinburgh Saint_Petersburg) 109)
     (flight Edinburgh Istanbul)
     (= (flightPrice Edinburgh Istanbul) 100)
     (flight Edinburgh Rome)
     (= (flightPrice Edinburgh Rome) 107)
     (flight Edinburgh Caracas)
     (= (flightPrice Edinburgh Caracas) 81)
     (flight Edinburgh Rio_de_Janeiro)
     (= (flightPrice Edinburgh Rio_de_Janeiro) 93)
     (flight Edinburgh La_Habana)
     (= (flightPrice Edinburgh La_Habana) 105)
     (flight Edinburgh Medellin)
     (= (flightPrice Edinburgh Medellin) 89)
     (flight Edinburgh Cali)
     (= (flightPrice Edinburgh Cali) 84)
     (flight Edinburgh Washington_DC)
     (= (flightPrice Edinburgh Washington_DC) 86)
     (flight Edinburgh New_York)
     (= (flightPrice Edinburgh New_York) 103)
     (flight Moscow Melbourne)
     (= (flightPrice Moscow Melbourne) 99)
     (flight Moscow Sidney)
     (= (flightPrice Moscow Sidney) 100)
     (flight Moscow Wellington)
     (= (flightPrice Moscow Wellington) 103)
     (flight Moscow Beijing)
     (= (flightPrice Moscow Beijing) 100)
     (flight Moscow Taiwan)
     (= (flightPrice Moscow Taiwan) 82)
     (flight Moscow Tokio)
     (= (flightPrice Moscow Tokio) 98)
     (flight Moscow Nova_Dheli)
     (= (flightPrice Moscow Nova_Dheli) 103)
     (flight Moscow Paris)
     (= (flightPrice Moscow Paris) 103)
     (flight Moscow London)
     (= (flightPrice Moscow London) 94)
     (flight Moscow Berlin)
     (= (flightPrice Moscow Berlin) 85)
     (flight Moscow Dublin)
     (= (flightPrice Moscow Dublin) 100)
     (flight Moscow Edinburgh)
     (= (flightPrice Moscow Edinburgh) 103)
     (flight Moscow Krakow)
     (= (flightPrice Moscow Krakow) 98)
     (flight Moscow Venice)
     (= (flightPrice Moscow Venice) 101)
     (flight Moscow Saint_Petersburg)
     (= (flightPrice Moscow Saint_Petersburg) 105)
     (flight Moscow Istanbul)
     (= (flightPrice Moscow Istanbul) 83)
     (flight Moscow Rome)
     (= (flightPrice Moscow Rome) 88)
     (flight Moscow Caracas)
     (= (flightPrice Moscow Caracas) 91)
     (flight Moscow Rio_de_Janeiro)
     (= (flightPrice Moscow Rio_de_Janeiro) 111)
     (flight Moscow La_Habana)
     (= (flightPrice Moscow La_Habana) 108)
     (flight Moscow Medellin)
     (= (flightPrice Moscow Medellin) 87)
     (flight Moscow Cali)
     (= (flightPrice Moscow Cali) 105)
     (flight Moscow Washington_DC)
     (= (flightPrice Moscow Washington_DC) 105)
     (flight Moscow New_York)
     (= (flightPrice Moscow New_York) 91)
     (flight Krakow Melbourne)
     (= (flightPrice Krakow Melbourne) 106)
     (flight Krakow Sidney)
     (= (flightPrice Krakow Sidney) 95)
     (flight Krakow Wellington)
     (= (flightPrice Krakow Wellington) 93)
     (flight Krakow Beijing)
     (= (flightPrice Krakow Beijing) 80)
     (flight Krakow Taiwan)
     (= (flightPrice Krakow Taiwan) 100)
     (flight Krakow Tokio)
     (= (flightPrice Krakow Tokio) 99)
     (flight Krakow Nova_Dheli)
     (= (flightPrice Krakow Nova_Dheli) 80)
     (flight Krakow Paris)
     (= (flightPrice Krakow Paris) 84)
     (flight Krakow London)
     (= (flightPrice Krakow London) 97)
     (flight Krakow Berlin)
     (= (flightPrice Krakow Berlin) 104)
     (flight Krakow Dublin)
     (= (flightPrice Krakow Dublin) 104)
     (flight Krakow Edinburgh)
     (= (flightPrice Krakow Edinburgh) 99)
     (flight Krakow Moscow)
     (= (flightPrice Krakow Moscow) 99)
     (flight Krakow Venice)
     (= (flightPrice Krakow Venice) 104)
     (flight Krakow Saint_Petersburg)
     (= (flightPrice Krakow Saint_Petersburg) 99)
     (flight Krakow Istanbul)
     (= (flightPrice Krakow Istanbul) 113)
     (flight Krakow Rome)
     (= (flightPrice Krakow Rome) 86)
     (flight Krakow Caracas)
     (= (flightPrice Krakow Caracas) 96)
     (flight Krakow Rio_de_Janeiro)
     (= (flightPrice Krakow Rio_de_Janeiro) 113)
     (flight Krakow La_Habana)
     (= (flightPrice Krakow La_Habana) 104)
     (flight Krakow Medellin)
     (= (flightPrice Krakow Medellin) 83)
     (flight Krakow Cali)
     (= (flightPrice Krakow Cali) 103)
     (flight Krakow Washington_DC)
     (= (flightPrice Krakow Washington_DC) 84)
     (flight Krakow New_York)
     (= (flightPrice Krakow New_York) 91)
     (flight Venice Melbourne)
     (= (flightPrice Venice Melbourne) 91)
     (flight Venice Sidney)
     (= (flightPrice Venice Sidney) 80)
     (flight Venice Wellington)
     (= (flightPrice Venice Wellington) 96)
     (flight Venice Beijing)
     (= (flightPrice Venice Beijing) 111)
     (flight Venice Taiwan)
     (= (flightPrice Venice Taiwan) 82)
     (flight Venice Tokio)
     (= (flightPrice Venice Tokio) 87)
     (flight Venice Nova_Dheli)
     (= (flightPrice Venice Nova_Dheli) 87)
     (flight Venice Paris)
     (= (flightPrice Venice Paris) 109)
     (flight Venice London)
     (= (flightPrice Venice London) 102)
     (flight Venice Berlin)
     (= (flightPrice Venice Berlin) 113)
     (flight Venice Dublin)
     (= (flightPrice Venice Dublin) 86)
     (flight Venice Edinburgh)
     (= (flightPrice Venice Edinburgh) 87)
     (flight Venice Moscow)
     (= (flightPrice Venice Moscow) 109)
     (flight Venice Krakow)
     (= (flightPrice Venice Krakow) 87)
     (flight Venice Saint_Petersburg)
     (= (flightPrice Venice Saint_Petersburg) 103)
     (flight Venice Istanbul)
     (= (flightPrice Venice Istanbul) 91)
     (flight Venice Rome)
     (= (flightPrice Venice Rome) 88)
     (flight Venice Caracas)
     (= (flightPrice Venice Caracas) 92)
     (flight Venice Rio_de_Janeiro)
     (= (flightPrice Venice Rio_de_Janeiro) 87)
     (flight Venice La_Habana)
     (= (flightPrice Venice La_Habana) 107)
     (flight Venice Medellin)
     (= (flightPrice Venice Medellin) 93)
     (flight Venice Cali)
     (= (flightPrice Venice Cali) 107)
     (flight Venice Washington_DC)
     (= (flightPrice Venice Washington_DC) 82)
     (flight Venice New_York)
     (= (flightPrice Venice New_York) 100)
     (flight Saint_Petersburg Melbourne)
     (= (flightPrice Saint_Petersburg Melbourne) 88)
     (flight Saint_Petersburg Sidney)
     (= (flightPrice Saint_Petersburg Sidney) 92)
     (flight Saint_Petersburg Wellington)
     (= (flightPrice Saint_Petersburg Wellington) 101)
     (flight Saint_Petersburg Beijing)
     (= (flightPrice Saint_Petersburg Beijing) 103)
     (flight Saint_Petersburg Taiwan)
     (= (flightPrice Saint_Petersburg Taiwan) 81)
     (flight Saint_Petersburg Tokio)
     (= (flightPrice Saint_Petersburg Tokio) 83)
     (flight Saint_Petersburg Nova_Dheli)
     (= (flightPrice Saint_Petersburg Nova_Dheli) 91)
     (flight Saint_Petersburg Paris)
     (= (flightPrice Saint_Petersburg Paris) 104)
     (flight Saint_Petersburg London)
     (= (flightPrice Saint_Petersburg London) 95)
     (flight Saint_Petersburg Berlin)
     (= (flightPrice Saint_Petersburg Berlin) 108)
     (flight Saint_Petersburg Dublin)
     (= (flightPrice Saint_Petersburg Dublin) 100)
     (flight Saint_Petersburg Edinburgh)
     (= (flightPrice Saint_Petersburg Edinburgh) 98)
     (flight Saint_Petersburg Moscow)
     (= (flightPrice Saint_Petersburg Moscow) 80)
     (flight Saint_Petersburg Krakow)
     (= (flightPrice Saint_Petersburg Krakow) 85)
     (flight Saint_Petersburg Venice)
     (= (flightPrice Saint_Petersburg Venice) 104)
     (flight Saint_Petersburg Istanbul)
     (= (flightPrice Saint_Petersburg Istanbul) 114)
     (flight Saint_Petersburg Rome)
     (= (flightPrice Saint_Petersburg Rome) 83)
     (flight Saint_Petersburg Caracas)
     (= (flightPrice Saint_Petersburg Caracas) 110)
     (flight Saint_Petersburg Rio_de_Janeiro)
     (= (flightPrice Saint_Petersburg Rio_de_Janeiro) 87)
     (flight Saint_Petersburg La_Habana)
     (= (flightPrice Saint_Petersburg La_Habana) 89)
     (flight Saint_Petersburg Medellin)
     (= (flightPrice Saint_Petersburg Medellin) 94)
     (flight Saint_Petersburg Cali)
     (= (flightPrice Saint_Petersburg Cali) 110)
     (flight Saint_Petersburg Washington_DC)
     (= (flightPrice Saint_Petersburg Washington_DC) 101)
     (flight Saint_Petersburg New_York)
     (= (flightPrice Saint_Petersburg New_York) 102)
     (flight Istanbul Melbourne)
     (= (flightPrice Istanbul Melbourne) 100)
     (flight Istanbul Sidney)
     (= (flightPrice Istanbul Sidney) 85)
     (flight Istanbul Wellington)
     (= (flightPrice Istanbul Wellington) 106)
     (flight Istanbul Beijing)
     (= (flightPrice Istanbul Beijing) 113)
     (flight Istanbul Taiwan)
     (= (flightPrice Istanbul Taiwan) 89)
     (flight Istanbul Tokio)
     (= (flightPrice Istanbul Tokio) 85)
     (flight Istanbul Nova_Dheli)
     (= (flightPrice Istanbul Nova_Dheli) 98)
     (flight Istanbul Paris)
     (= (flightPrice Istanbul Paris) 98)
     (flight Istanbul London)
     (= (flightPrice Istanbul London) 98)
     (flight Istanbul Berlin)
     (= (flightPrice Istanbul Berlin) 97)
     (flight Istanbul Dublin)
     (= (flightPrice Istanbul Dublin) 98)
     (flight Istanbul Edinburgh)
     (= (flightPrice Istanbul Edinburgh) 111)
     (flight Istanbul Moscow)
     (= (flightPrice Istanbul Moscow) 100)
     (flight Istanbul Krakow)
     (= (flightPrice Istanbul Krakow) 110)
     (flight Istanbul Venice)
     (= (flightPrice Istanbul Venice) 100)
     (flight Istanbul Saint_Petersburg)
     (= (flightPrice Istanbul Saint_Petersburg) 80)
     (flight Istanbul Rome)
     (= (flightPrice Istanbul Rome) 103)
     (flight Istanbul Caracas)
     (= (flightPrice Istanbul Caracas) 86)
     (flight Istanbul Rio_de_Janeiro)
     (= (flightPrice Istanbul Rio_de_Janeiro) 98)
     (flight Istanbul La_Habana)
     (= (flightPrice Istanbul La_Habana) 80)
     (flight Istanbul Medellin)
     (= (flightPrice Istanbul Medellin) 91)
     (flight Istanbul Cali)
     (= (flightPrice Istanbul Cali) 87)
     (flight Istanbul Washington_DC)
     (= (flightPrice Istanbul Washington_DC) 114)
     (flight Istanbul New_York)
     (= (flightPrice Istanbul New_York) 106)
     (flight Rome Melbourne)
     (= (flightPrice Rome Melbourne) 95)
     (flight Rome Sidney)
     (= (flightPrice Rome Sidney) 98)
     (flight Rome Wellington)
     (= (flightPrice Rome Wellington) 80)
     (flight Rome Beijing)
     (= (flightPrice Rome Beijing) 109)
     (flight Rome Taiwan)
     (= (flightPrice Rome Taiwan) 94)
     (flight Rome Tokio)
     (= (flightPrice Rome Tokio) 113)
     (flight Rome Nova_Dheli)
     (= (flightPrice Rome Nova_Dheli) 109)
     (flight Rome Paris)
     (= (flightPrice Rome Paris) 91)
     (flight Rome London)
     (= (flightPrice Rome London) 84)
     (flight Rome Berlin)
     (= (flightPrice Rome Berlin) 112)
     (flight Rome Dublin)
     (= (flightPrice Rome Dublin) 89)
     (flight Rome Edinburgh)
     (= (flightPrice Rome Edinburgh) 105)
     (flight Rome Moscow)
     (= (flightPrice Rome Moscow) 83)
     (flight Rome Krakow)
     (= (flightPrice Rome Krakow) 85)
     (flight Rome Venice)
     (= (flightPrice Rome Venice) 88)
     (flight Rome Saint_Petersburg)
     (= (flightPrice Rome Saint_Petersburg) 113)
     (flight Rome Istanbul)
     (= (flightPrice Rome Istanbul) 102)
     (flight Rome Caracas)
     (= (flightPrice Rome Caracas) 84)
     (flight Rome Rio_de_Janeiro)
     (= (flightPrice Rome Rio_de_Janeiro) 109)
     (flight Rome La_Habana)
     (= (flightPrice Rome La_Habana) 99)
     (flight Rome Medellin)
     (= (flightPrice Rome Medellin) 114)
     (flight Rome Cali)
     (= (flightPrice Rome Cali) 106)
     (flight Rome Washington_DC)
     (= (flightPrice Rome Washington_DC) 99)
     (flight Rome New_York)
     (= (flightPrice Rome New_York) 114)
     (flight Caracas Melbourne)
     (= (flightPrice Caracas Melbourne) 112)
     (flight Caracas Sidney)
     (= (flightPrice Caracas Sidney) 95)
     (flight Caracas Wellington)
     (= (flightPrice Caracas Wellington) 91)
     (flight Caracas Beijing)
     (= (flightPrice Caracas Beijing) 100)
     (flight Caracas Taiwan)
     (= (flightPrice Caracas Taiwan) 114)
     (flight Caracas Tokio)
     (= (flightPrice Caracas Tokio) 90)
     (flight Caracas Nova_Dheli)
     (= (flightPrice Caracas Nova_Dheli) 91)
     (flight Caracas Paris)
     (= (flightPrice Caracas Paris) 106)
     (flight Caracas London)
     (= (flightPrice Caracas London) 86)
     (flight Caracas Berlin)
     (= (flightPrice Caracas Berlin) 104)
     (flight Caracas Dublin)
     (= (flightPrice Caracas Dublin) 113)
     (flight Caracas Edinburgh)
     (= (flightPrice Caracas Edinburgh) 112)
     (flight Caracas Moscow)
     (= (flightPrice Caracas Moscow) 102)
     (flight Caracas Krakow)
     (= (flightPrice Caracas Krakow) 107)
     (flight Caracas Venice)
     (= (flightPrice Caracas Venice) 88)
     (flight Caracas Saint_Petersburg)
     (= (flightPrice Caracas Saint_Petersburg) 83)
     (flight Caracas Istanbul)
     (= (flightPrice Caracas Istanbul) 104)
     (flight Caracas Rome)
     (= (flightPrice Caracas Rome) 97)
     (flight Caracas Rio_de_Janeiro)
     (= (flightPrice Caracas Rio_de_Janeiro) 109)
     (flight Caracas La_Habana)
     (= (flightPrice Caracas La_Habana) 84)
     (flight Caracas Medellin)
     (= (flightPrice Caracas Medellin) 114)
     (flight Caracas Cali)
     (= (flightPrice Caracas Cali) 94)
     (flight Caracas Washington_DC)
     (= (flightPrice Caracas Washington_DC) 94)
     (flight Caracas New_York)
     (= (flightPrice Caracas New_York) 113)
     (flight Rio_de_Janeiro Melbourne)
     (= (flightPrice Rio_de_Janeiro Melbourne) 98)
     (flight Rio_de_Janeiro Sidney)
     (= (flightPrice Rio_de_Janeiro Sidney) 88)
     (flight Rio_de_Janeiro Wellington)
     (= (flightPrice Rio_de_Janeiro Wellington) 97)
     (flight Rio_de_Janeiro Beijing)
     (= (flightPrice Rio_de_Janeiro Beijing) 109)
     (flight Rio_de_Janeiro Taiwan)
     (= (flightPrice Rio_de_Janeiro Taiwan) 80)
     (flight Rio_de_Janeiro Tokio)
     (= (flightPrice Rio_de_Janeiro Tokio) 94)
     (flight Rio_de_Janeiro Nova_Dheli)
     (= (flightPrice Rio_de_Janeiro Nova_Dheli) 108)
     (flight Rio_de_Janeiro Paris)
     (= (flightPrice Rio_de_Janeiro Paris) 89)
     (flight Rio_de_Janeiro London)
     (= (flightPrice Rio_de_Janeiro London) 109)
     (flight Rio_de_Janeiro Berlin)
     (= (flightPrice Rio_de_Janeiro Berlin) 84)
     (flight Rio_de_Janeiro Dublin)
     (= (flightPrice Rio_de_Janeiro Dublin) 110)
     (flight Rio_de_Janeiro Edinburgh)
     (= (flightPrice Rio_de_Janeiro Edinburgh) 85)
     (flight Rio_de_Janeiro Moscow)
     (= (flightPrice Rio_de_Janeiro Moscow) 107)
     (flight Rio_de_Janeiro Krakow)
     (= (flightPrice Rio_de_Janeiro Krakow) 98)
     (flight Rio_de_Janeiro Venice)
     (= (flightPrice Rio_de_Janeiro Venice) 89)
     (flight Rio_de_Janeiro Saint_Petersburg)
     (= (flightPrice Rio_de_Janeiro Saint_Petersburg) 90)
     (flight Rio_de_Janeiro Istanbul)
     (= (flightPrice Rio_de_Janeiro Istanbul) 87)
     (flight Rio_de_Janeiro Rome)
     (= (flightPrice Rio_de_Janeiro Rome) 87)
     (flight Rio_de_Janeiro Caracas)
     (= (flightPrice Rio_de_Janeiro Caracas) 87)
     (flight Rio_de_Janeiro La_Habana)
     (= (flightPrice Rio_de_Janeiro La_Habana) 87)
     (flight Rio_de_Janeiro Medellin)
     (= (flightPrice Rio_de_Janeiro Medellin) 114)
     (flight Rio_de_Janeiro Cali)
     (= (flightPrice Rio_de_Janeiro Cali) 95)
     (flight Rio_de_Janeiro Washington_DC)
     (= (flightPrice Rio_de_Janeiro Washington_DC) 90)
     (flight Rio_de_Janeiro New_York)
     (= (flightPrice Rio_de_Janeiro New_York) 80)
     (flight La_Habana Melbourne)
     (= (flightPrice La_Habana Melbourne) 89)
     (flight La_Habana Sidney)
     (= (flightPrice La_Habana Sidney) 96)
     (flight La_Habana Wellington)
     (= (flightPrice La_Habana Wellington) 97)
     (flight La_Habana Beijing)
     (= (flightPrice La_Habana Beijing) 89)
     (flight La_Habana Taiwan)
     (= (flightPrice La_Habana Taiwan) 88)
     (flight La_Habana Tokio)
     (= (flightPrice La_Habana Tokio) 111)
     (flight La_Habana Nova_Dheli)
     (= (flightPrice La_Habana Nova_Dheli) 87)
     (flight La_Habana Paris)
     (= (flightPrice La_Habana Paris) 106)
     (flight La_Habana London)
     (= (flightPrice La_Habana London) 97)
     (flight La_Habana Berlin)
     (= (flightPrice La_Habana Berlin) 105)
     (flight La_Habana Dublin)
     (= (flightPrice La_Habana Dublin) 113)
     (flight La_Habana Edinburgh)
     (= (flightPrice La_Habana Edinburgh) 109)
     (flight La_Habana Moscow)
     (= (flightPrice La_Habana Moscow) 96)
     (flight La_Habana Krakow)
     (= (flightPrice La_Habana Krakow) 83)
     (flight La_Habana Venice)
     (= (flightPrice La_Habana Venice) 83)
     (flight La_Habana Saint_Petersburg)
     (= (flightPrice La_Habana Saint_Petersburg) 102)
     (flight La_Habana Istanbul)
     (= (flightPrice La_Habana Istanbul) 100)
     (flight La_Habana Rome)
     (= (flightPrice La_Habana Rome) 90)
     (flight La_Habana Caracas)
     (= (flightPrice La_Habana Caracas) 107)
     (flight La_Habana Rio_de_Janeiro)
     (= (flightPrice La_Habana Rio_de_Janeiro) 92)
     (flight La_Habana Medellin)
     (= (flightPrice La_Habana Medellin) 109)
     (flight La_Habana Cali)
     (= (flightPrice La_Habana Cali) 81)
     (flight La_Habana Washington_DC)
     (= (flightPrice La_Habana Washington_DC) 114)
     (flight La_Habana New_York)
     (= (flightPrice La_Habana New_York) 81)
     (flight Medellin Melbourne)
     (= (flightPrice Medellin Melbourne) 88)
     (flight Medellin Sidney)
     (= (flightPrice Medellin Sidney) 86)
     (flight Medellin Wellington)
     (= (flightPrice Medellin Wellington) 88)
     (flight Medellin Beijing)
     (= (flightPrice Medellin Beijing) 99)
     (flight Medellin Taiwan)
     (= (flightPrice Medellin Taiwan) 101)
     (flight Medellin Tokio)
     (= (flightPrice Medellin Tokio) 111)
     (flight Medellin Nova_Dheli)
     (= (flightPrice Medellin Nova_Dheli) 112)
     (flight Medellin Paris)
     (= (flightPrice Medellin Paris) 87)
     (flight Medellin London)
     (= (flightPrice Medellin London) 92)
     (flight Medellin Berlin)
     (= (flightPrice Medellin Berlin) 94)
     (flight Medellin Dublin)
     (= (flightPrice Medellin Dublin) 96)
     (flight Medellin Edinburgh)
     (= (flightPrice Medellin Edinburgh) 100)
     (flight Medellin Moscow)
     (= (flightPrice Medellin Moscow) 90)
     (flight Medellin Krakow)
     (= (flightPrice Medellin Krakow) 81)
     (flight Medellin Venice)
     (= (flightPrice Medellin Venice) 104)
     (flight Medellin Saint_Petersburg)
     (= (flightPrice Medellin Saint_Petersburg) 84)
     (flight Medellin Istanbul)
     (= (flightPrice Medellin Istanbul) 83)
     (flight Medellin Rome)
     (= (flightPrice Medellin Rome) 102)
     (flight Medellin Caracas)
     (= (flightPrice Medellin Caracas) 113)
     (flight Medellin Rio_de_Janeiro)
     (= (flightPrice Medellin Rio_de_Janeiro) 99)
     (flight Medellin La_Habana)
     (= (flightPrice Medellin La_Habana) 82)
     (flight Medellin Cali)
     (= (flightPrice Medellin Cali) 82)
     (flight Medellin Washington_DC)
     (= (flightPrice Medellin Washington_DC) 86)
     (flight Medellin New_York)
     (= (flightPrice Medellin New_York) 102)
     (flight Cali Melbourne)
     (= (flightPrice Cali Melbourne) 104)
     (flight Cali Sidney)
     (= (flightPrice Cali Sidney) 90)
     (flight Cali Wellington)
     (= (flightPrice Cali Wellington) 91)
     (flight Cali Beijing)
     (= (flightPrice Cali Beijing) 98)
     (flight Cali Taiwan)
     (= (flightPrice Cali Taiwan) 104)
     (flight Cali Tokio)
     (= (flightPrice Cali Tokio) 90)
     (flight Cali Nova_Dheli)
     (= (flightPrice Cali Nova_Dheli) 100)
     (flight Cali Paris)
     (= (flightPrice Cali Paris) 112)
     (flight Cali London)
     (= (flightPrice Cali London) 96)
     (flight Cali Berlin)
     (= (flightPrice Cali Berlin) 85)
     (flight Cali Dublin)
     (= (flightPrice Cali Dublin) 109)
     (flight Cali Edinburgh)
     (= (flightPrice Cali Edinburgh) 94)
     (flight Cali Moscow)
     (= (flightPrice Cali Moscow) 81)
     (flight Cali Krakow)
     (= (flightPrice Cali Krakow) 106)
     (flight Cali Venice)
     (= (flightPrice Cali Venice) 102)
     (flight Cali Saint_Petersburg)
     (= (flightPrice Cali Saint_Petersburg) 106)
     (flight Cali Istanbul)
     (= (flightPrice Cali Istanbul) 85)
     (flight Cali Rome)
     (= (flightPrice Cali Rome) 95)
     (flight Cali Caracas)
     (= (flightPrice Cali Caracas) 103)
     (flight Cali Rio_de_Janeiro)
     (= (flightPrice Cali Rio_de_Janeiro) 107)
     (flight Cali La_Habana)
     (= (flightPrice Cali La_Habana) 96)
     (flight Cali Medellin)
     (= (flightPrice Cali Medellin) 104)
     (flight Cali Washington_DC)
     (= (flightPrice Cali Washington_DC) 112)
     (flight Cali New_York)
     (= (flightPrice Cali New_York) 111)
     (flight Washington_DC Melbourne)
     (= (flightPrice Washington_DC Melbourne) 103)
     (flight Washington_DC Sidney)
     (= (flightPrice Washington_DC Sidney) 87)
     (flight Washington_DC Wellington)
     (= (flightPrice Washington_DC Wellington) 95)
     (flight Washington_DC Beijing)
     (= (flightPrice Washington_DC Beijing) 106)
     (flight Washington_DC Taiwan)
     (= (flightPrice Washington_DC Taiwan) 89)
     (flight Washington_DC Tokio)
     (= (flightPrice Washington_DC Tokio) 113)
     (flight Washington_DC Nova_Dheli)
     (= (flightPrice Washington_DC Nova_Dheli) 93)
     (flight Washington_DC Paris)
     (= (flightPrice Washington_DC Paris) 91)
     (flight Washington_DC London)
     (= (flightPrice Washington_DC London) 89)
     (flight Washington_DC Berlin)
     (= (flightPrice Washington_DC Berlin) 105)
     (flight Washington_DC Dublin)
     (= (flightPrice Washington_DC Dublin) 109)
     (flight Washington_DC Edinburgh)
     (= (flightPrice Washington_DC Edinburgh) 113)
     (flight Washington_DC Moscow)
     (= (flightPrice Washington_DC Moscow) 80)
     (flight Washington_DC Krakow)
     (= (flightPrice Washington_DC Krakow) 106)
     (flight Washington_DC Venice)
     (= (flightPrice Washington_DC Venice) 87)
     (flight Washington_DC Saint_Petersburg)
     (= (flightPrice Washington_DC Saint_Petersburg) 109)
     (flight Washington_DC Istanbul)
     (= (flightPrice Washington_DC Istanbul) 112)
     (flight Washington_DC Rome)
     (= (flightPrice Washington_DC Rome) 93)
     (flight Washington_DC Caracas)
     (= (flightPrice Washington_DC Caracas) 88)
     (flight Washington_DC Rio_de_Janeiro)
     (= (flightPrice Washington_DC Rio_de_Janeiro) 90)
     (flight Washington_DC La_Habana)
     (= (flightPrice Washington_DC La_Habana) 84)
     (flight Washington_DC Medellin)
     (= (flightPrice Washington_DC Medellin) 87)
     (flight Washington_DC Cali)
     (= (flightPrice Washington_DC Cali) 93)
     (flight Washington_DC New_York)
     (= (flightPrice Washington_DC New_York) 101)
     (flight New_York Melbourne)
     (= (flightPrice New_York Melbourne) 103)
     (flight New_York Sidney)
     (= (flightPrice New_York Sidney) 82)
     (flight New_York Wellington)
     (= (flightPrice New_York Wellington) 94)
     (flight New_York Beijing)
     (= (flightPrice New_York Beijing) 96)
     (flight New_York Taiwan)
     (= (flightPrice New_York Taiwan) 106)
     (flight New_York Tokio)
     (= (flightPrice New_York Tokio) 103)
     (flight New_York Nova_Dheli)
     (= (flightPrice New_York Nova_Dheli) 93)
     (flight New_York Paris)
     (= (flightPrice New_York Paris) 95)
     (flight New_York London)
     (= (flightPrice New_York London) 110)
     (flight New_York Berlin)
     (= (flightPrice New_York Berlin) 85)
     (flight New_York Dublin)
     (= (flightPrice New_York Dublin) 86)
     (flight New_York Edinburgh)
     (= (flightPrice New_York Edinburgh) 97)
     (flight New_York Moscow)
     (= (flightPrice New_York Moscow) 96)
     (flight New_York Krakow)
     (= (flightPrice New_York Krakow) 99)
     (flight New_York Venice)
     (= (flightPrice New_York Venice) 108)
     (flight New_York Saint_Petersburg)
     (= (flightPrice New_York Saint_Petersburg) 105)
     (flight New_York Istanbul)
     (= (flightPrice New_York Istanbul) 101)
     (flight New_York Rome)
     (= (flightPrice New_York Rome) 102)
     (flight New_York Caracas)
     (= (flightPrice New_York Caracas) 80)
     (flight New_York Rio_de_Janeiro)
     (= (flightPrice New_York Rio_de_Janeiro) 102)
     (flight New_York La_Habana)
     (= (flightPrice New_York La_Habana) 106)
     (flight New_York Medellin)
     (= (flightPrice New_York Medellin) 99)
     (flight New_York Cali)
     (= (flightPrice New_York Cali) 96)
     (flight New_York Washington_DC)
     (= (flightPrice New_York Washington_DC) 103)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Melbourne)
     (inCity Hotel_Emperor_2 Melbourne)
     (inCity Residence_Sky_3 Melbourne)
     (inCity Hostel_Delphin_4 Melbourne)
     (inCity Residence_Single_Land_5 Melbourne)
     (inCity Resort_Lollipop_6 Melbourne)
     (inCity Hostel_Emperor_7 Melbourne)
     (inCity Hostel_Lollipop_8 Melbourne)
     (inCity Hostel_Single_Land_9 Melbourne)
     (inCity Apartments_Paradise_10 Sidney)
     (inCity Resort_Arabiga_11 Sidney)
     (inCity Hotel_Single_Land_12 Sidney)
     (inCity Apartments_Single_Land_13 Sidney)
     (inCity Hotel_Arabiga_14 Sidney)
     (inCity Residence_Delphin_15 Sidney)
     (inCity Apartments_Single_Land_16 Sidney)
     (inCity Residence_Delphin_17 Sidney)
     (inCity Hostel_Emperor_18 Sidney)
     (inCity Residence_Paradise_19 Sidney)
     (inCity Apartments_Delphin_20 Wellington)
     (inCity Resort_Paradise_21 Wellington)
     (inCity Residence_Relax_22 Wellington)
     (inCity Resort_NH_23 Wellington)
     (inCity Hotel_Chill_24 Wellington)
     (inCity Hostel_Emperor_25 Wellington)
     (inCity Hotel_Paradise_26 Wellington)
     (inCity Apartments_Sky_27 Wellington)
     (inCity Hotel_Single_Land_28 Wellington)
     (inCity Hostel_Sky_29 Wellington)
     (inCity Hotel_Chill_30 Beijing)
     (inCity Residence_Relax_31 Beijing)
     (inCity Hotel_Sky_32 Beijing)
     (inCity Resort_Sky_33 Beijing)
     (inCity Residence_Emperor_34 Beijing)
     (inCity Hotel_Relax_35 Beijing)
     (inCity Hotel_Single_Land_36 Beijing)
     (inCity Residence_Relax_37 Beijing)
     (inCity Resort_Relax_38 Beijing)
     (inCity Hotel_Emperor_39 Beijing)
     (inCity Apartments_Arabiga_40 Taiwan)
     (inCity Apartments_Sky_41 Taiwan)
     (inCity Resort_NH_42 Taiwan)
     (inCity Hostel_Emperor_43 Taiwan)
     (inCity Resort_Relax_44 Taiwan)
     (inCity Hotel_Single_Land_45 Taiwan)
     (inCity Apartments_Sky_46 Taiwan)
     (inCity Residence_Delphin_47 Taiwan)
     (inCity Hostel_Sky_48 Taiwan)
     (inCity Resort_Relax_49 Taiwan)
     (inCity Hotel_Chill_50 Tokio)
     (inCity Apartments_Relax_51 Tokio)
     (inCity Hostel_Arabiga_52 Tokio)
     (inCity Residence_Arabiga_53 Tokio)
     (inCity Residence_Arabiga_54 Tokio)
     (inCity Hostel_Single_Land_55 Tokio)
     (inCity Hotel_Paradise_56 Tokio)
     (inCity Hostel_Sky_57 Tokio)
     (inCity Resort_Chill_58 Tokio)
     (inCity Resort_Relax_59 Tokio)
     (inCity Resort_Lollipop_60 Nova_Dheli)
     (inCity Residence_Paradise_61 Nova_Dheli)
     (inCity Hostel_Arabiga_62 Nova_Dheli)
     (inCity Hotel_Paradise_63 Nova_Dheli)
     (inCity Residence_Delphin_64 Nova_Dheli)
     (inCity Hostel_Arabiga_65 Nova_Dheli)
     (inCity Apartments_Arabiga_66 Nova_Dheli)
     (inCity Hotel_Sky_67 Nova_Dheli)
     (inCity Apartments_Sky_68 Nova_Dheli)
     (inCity Resort_Delphin_69 Nova_Dheli)
     (inCity Hostel_NH_70 Paris)
     (inCity Resort_Single_Land_71 Paris)
     (inCity Resort_Emperor_72 Paris)
     (inCity Apartments_Lollipop_73 Paris)
     (inCity Hotel_NH_74 Paris)
     (inCity Resort_Lollipop_75 Paris)
     (inCity Apartments_Sky_76 Paris)
     (inCity Hotel_NH_77 Paris)
     (inCity Hostel_Sky_78 Paris)
     (inCity Hotel_Paradise_79 Paris)
     (inCity Apartments_Delphin_80 London)
     (inCity Apartments_Relax_81 London)
     (inCity Hotel_Paradise_82 London)
     (inCity Hotel_Emperor_83 London)
     (inCity Resort_Relax_84 London)
     (inCity Resort_Relax_85 London)
     (inCity Hostel_Arabiga_86 London)
     (inCity Hostel_Emperor_87 London)
     (inCity Hotel_Arabiga_88 London)
     (inCity Hostel_Delphin_89 London)
     (inCity Hostel_Single_Land_90 Berlin)
     (inCity Apartments_Arabiga_91 Berlin)
     (inCity Residence_Chill_92 Berlin)
     (inCity Hostel_Relax_93 Berlin)
     (inCity Hotel_NH_94 Berlin)
     (inCity Residence_Delphin_95 Berlin)
     (inCity Apartments_Chill_96 Berlin)
     (inCity Apartments_NH_97 Berlin)
     (inCity Hostel_Emperor_98 Berlin)
     (inCity Resort_NH_99 Berlin)
     (inCity Resort_Sky_100 Dublin)
     (inCity Apartments_Emperor_101 Dublin)
     (inCity Apartments_Emperor_102 Dublin)
     (inCity Hotel_Sky_103 Dublin)
     (inCity Apartments_Relax_104 Dublin)
     (inCity Apartments_NH_105 Dublin)
     (inCity Residence_Delphin_106 Dublin)
     (inCity Hostel_Arabiga_107 Dublin)
     (inCity Apartments_Relax_108 Dublin)
     (inCity Apartments_Lollipop_109 Dublin)
     (inCity Resort_Lollipop_110 Edinburgh)
     (inCity Hotel_Single_Land_111 Edinburgh)
     (inCity Hotel_Relax_112 Edinburgh)
     (inCity Resort_Chill_113 Edinburgh)
     (inCity Hostel_Relax_114 Edinburgh)
     (inCity Residence_Delphin_115 Edinburgh)
     (inCity Resort_Single_Land_116 Edinburgh)
     (inCity Residence_Arabiga_117 Edinburgh)
     (inCity Resort_Chill_118 Edinburgh)
     (inCity Hostel_NH_119 Edinburgh)
     (inCity Apartments_Single_Land_120 Moscow)
     (inCity Apartments_Delphin_121 Moscow)
     (inCity Apartments_Sky_122 Moscow)
     (inCity Residence_Lollipop_123 Moscow)
     (inCity Hotel_Paradise_124 Moscow)
     (inCity Hostel_Chill_125 Moscow)
     (inCity Hotel_Paradise_126 Moscow)
     (inCity Hotel_NH_127 Moscow)
     (inCity Hostel_Lollipop_128 Moscow)
     (inCity Hostel_Relax_129 Moscow)
     (inCity Hotel_Single_Land_130 Krakow)
     (inCity Hostel_NH_131 Krakow)
     (inCity Apartments_Single_Land_132 Krakow)
     (inCity Residence_Relax_133 Krakow)
     (inCity Resort_Single_Land_134 Krakow)
     (inCity Hostel_Lollipop_135 Krakow)
     (inCity Resort_Single_Land_136 Krakow)
     (inCity Hotel_Delphin_137 Krakow)
     (inCity Hostel_NH_138 Krakow)
     (inCity Hostel_Emperor_139 Krakow)
     (inCity Hotel_Paradise_140 Venice)
     (inCity Resort_Emperor_141 Venice)
     (inCity Apartments_Lollipop_142 Venice)
     (inCity Hostel_Delphin_143 Venice)
     (inCity Hostel_Delphin_144 Venice)
     (inCity Apartments_Delphin_145 Venice)
     (inCity Apartments_Emperor_146 Venice)
     (inCity Hotel_Lollipop_147 Venice)
     (inCity Hostel_Sky_148 Venice)
     (inCity Hotel_Relax_149 Venice)
     (inCity Resort_Lollipop_150 Saint_Petersburg)
     (inCity Residence_Sky_151 Saint_Petersburg)
     (inCity Residence_Sky_152 Saint_Petersburg)
     (inCity Hostel_Chill_153 Saint_Petersburg)
     (inCity Apartments_Delphin_154 Saint_Petersburg)
     (inCity Residence_Arabiga_155 Saint_Petersburg)
     (inCity Residence_NH_156 Saint_Petersburg)
     (inCity Resort_Delphin_157 Saint_Petersburg)
     (inCity Hotel_Sky_158 Saint_Petersburg)
     (inCity Residence_Single_Land_159 Saint_Petersburg)
     (inCity Hostel_Sky_160 Istanbul)
     (inCity Residence_Emperor_161 Istanbul)
     (inCity Hotel_Paradise_162 Istanbul)
     (inCity Resort_Delphin_163 Istanbul)
     (inCity Resort_Paradise_164 Istanbul)
     (inCity Hostel_Delphin_165 Istanbul)
     (inCity Residence_Lollipop_166 Istanbul)
     (inCity Apartments_Chill_167 Istanbul)
     (inCity Hotel_Arabiga_168 Istanbul)
     (inCity Apartments_Relax_169 Istanbul)
     (inCity Resort_Lollipop_170 Rome)
     (inCity Resort_Single_Land_171 Rome)
     (inCity Hostel_Sky_172 Rome)
     (inCity Resort_Lollipop_173 Rome)
     (inCity Residence_Single_Land_174 Rome)
     (inCity Hotel_Single_Land_175 Rome)
     (inCity Hotel_Chill_176 Rome)
     (inCity Resort_Single_Land_177 Rome)
     (inCity Residence_Lollipop_178 Rome)
     (inCity Apartments_NH_179 Rome)
     (inCity Hotel_NH_180 Caracas)
     (inCity Hotel_Relax_181 Caracas)
     (inCity Hostel_Delphin_182 Caracas)
     (inCity Hostel_Delphin_183 Caracas)
     (inCity Hotel_Single_Land_184 Caracas)
     (inCity Resort_Relax_185 Caracas)
     (inCity Resort_Delphin_186 Caracas)
     (inCity Hostel_Emperor_187 Caracas)
     (inCity Hotel_Lollipop_188 Caracas)
     (inCity Residence_Lollipop_189 Caracas)
     (inCity Resort_Delphin_190 Rio_de_Janeiro)
     (inCity Hotel_Emperor_191 Rio_de_Janeiro)
     (inCity Residence_Paradise_192 Rio_de_Janeiro)
     (inCity Apartments_Relax_193 Rio_de_Janeiro)
     (inCity Resort_Paradise_194 Rio_de_Janeiro)
     (inCity Resort_Sky_195 Rio_de_Janeiro)
     (inCity Residence_Relax_196 Rio_de_Janeiro)
     (inCity Hostel_Single_Land_197 Rio_de_Janeiro)
     (inCity Hostel_Relax_198 Rio_de_Janeiro)
     (inCity Apartments_Single_Land_199 Rio_de_Janeiro)
     (inCity Resort_NH_200 La_Habana)
     (inCity Apartments_Single_Land_201 La_Habana)
     (inCity Apartments_NH_202 La_Habana)
     (inCity Apartments_Sky_203 La_Habana)
     (inCity Apartments_Emperor_204 La_Habana)
     (inCity Apartments_Emperor_205 La_Habana)
     (inCity Apartments_Emperor_206 La_Habana)
     (inCity Resort_Lollipop_207 La_Habana)
     (inCity Hostel_Arabiga_208 La_Habana)
     (inCity Resort_NH_209 La_Habana)
     (inCity Hostel_Lollipop_210 Medellin)
     (inCity Residence_NH_211 Medellin)
     (inCity Hotel_Delphin_212 Medellin)
     (inCity Apartments_Emperor_213 Medellin)
     (inCity Residence_Emperor_214 Medellin)
     (inCity Residence_Emperor_215 Medellin)
     (inCity Hotel_Sky_216 Medellin)
     (inCity Hostel_Single_Land_217 Medellin)
     (inCity Apartments_Chill_218 Medellin)
     (inCity Resort_Arabiga_219 Medellin)
     (inCity Hotel_Sky_220 Cali)
     (inCity Hostel_Relax_221 Cali)
     (inCity Resort_Lollipop_222 Cali)
     (inCity Residence_NH_223 Cali)
     (inCity Apartments_Lollipop_224 Cali)
     (inCity Residence_Sky_225 Cali)
     (inCity Residence_Relax_226 Cali)
     (inCity Apartments_Delphin_227 Cali)
     (inCity Residence_Delphin_228 Cali)
     (inCity Apartments_NH_229 Cali)
     (inCity Hostel_Lollipop_230 Washington_DC)
     (inCity Apartments_Arabiga_231 Washington_DC)
     (inCity Hostel_Delphin_232 Washington_DC)
     (inCity Resort_Chill_233 Washington_DC)
     (inCity Residence_Delphin_234 Washington_DC)
     (inCity Residence_Chill_235 Washington_DC)
     (inCity Resort_Relax_236 Washington_DC)
     (inCity Resort_Delphin_237 Washington_DC)
     (inCity Resort_Chill_238 Washington_DC)
     (inCity Hotel_Emperor_239 Washington_DC)
     (inCity Hotel_Arabiga_240 New_York)
     (inCity Hostel_NH_241 New_York)
     (inCity Resort_Delphin_242 New_York)
     (inCity Apartments_Arabiga_243 New_York)
     (inCity Hotel_Single_Land_244 New_York)
     (inCity Resort_Emperor_245 New_York)
     (inCity Hotel_Delphin_246 New_York)
     (inCity Hotel_Single_Land_247 New_York)
     (inCity Resort_Paradise_248 New_York)
     (inCity Residence_Sky_249 New_York)
)

(:goal 
(and (= (visited-cities) 5)
     (> (total-days) 8)
     (> (total-price) (minPriceTrip))
     (< (total-price) (maxPriceTrip))
)
)

(:metric minimize (total-price))

)
