;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem42)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin Dublin Edinburgh Moscow Krakow Venice Saint_Petersburg Istanbul Rome Caracas Rio_de_Janeiro La_Habana Medellin Cali Washington_DC New_York - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 Apartments_Paradise_10 Resort_Arabiga_11 Hotel_Single_Land_12 Apartments_Single_Land_13 Hotel_Arabiga_14 Residence_Delphin_15 Apartments_Single_Land_16 Residence_Delphin_17 Hostel_Emperor_18 Residence_Paradise_19 Apartments_Delphin_20 Resort_Paradise_21 Residence_Relax_22 Resort_NH_23 Hotel_Chill_24 Hostel_Emperor_25 Hotel_Paradise_26 Apartments_Sky_27 Hotel_Single_Land_28 Hostel_Sky_29 Hotel_Chill_30 Residence_Relax_31 Hotel_Sky_32 Resort_Sky_33 Residence_Emperor_34 Hotel_Relax_35 Hotel_Single_Land_36 Residence_Relax_37 Resort_Relax_38 Hotel_Emperor_39 Apartments_Arabiga_40 Apartments_Sky_41 Resort_NH_42 Hostel_Emperor_43 Resort_Relax_44 Hotel_Single_Land_45 Apartments_Sky_46 Residence_Delphin_47 Hostel_Sky_48 Resort_Relax_49 Hotel_Chill_50 Apartments_Relax_51 Hostel_Arabiga_52 Residence_Arabiga_53 Residence_Arabiga_54 Hostel_Single_Land_55 Hotel_Paradise_56 Hostel_Sky_57 Resort_Chill_58 Resort_Relax_59 Resort_Lollipop_60 Residence_Paradise_61 Hostel_Arabiga_62 Hotel_Paradise_63 Residence_Delphin_64 Hostel_Arabiga_65 Apartments_Arabiga_66 Hotel_Sky_67 Apartments_Sky_68 Resort_Delphin_69 Hostel_NH_70 Resort_Single_Land_71 Resort_Emperor_72 Apartments_Lollipop_73 Hotel_NH_74 Resort_Lollipop_75 Apartments_Sky_76 Hotel_NH_77 Hostel_Sky_78 Hotel_Paradise_79 Apartments_Delphin_80 Apartments_Relax_81 Hotel_Paradise_82 Hotel_Emperor_83 Resort_Relax_84 Resort_Relax_85 Hostel_Arabiga_86 Hostel_Emperor_87 Hotel_Arabiga_88 Hostel_Delphin_89 Hostel_Single_Land_90 Apartments_Arabiga_91 Residence_Chill_92 Hostel_Relax_93 Hotel_NH_94 Residence_Delphin_95 Apartments_Chill_96 Apartments_NH_97 Hostel_Emperor_98 Resort_NH_99 Resort_Sky_100 Apartments_Emperor_101 Apartments_Emperor_102 Hotel_Sky_103 Apartments_Relax_104 Apartments_NH_105 Residence_Delphin_106 Hostel_Arabiga_107 Apartments_Relax_108 Apartments_Lollipop_109 Resort_Lollipop_110 Hotel_Single_Land_111 Hotel_Relax_112 Resort_Chill_113 Hostel_Relax_114 Residence_Delphin_115 Resort_Single_Land_116 Residence_Arabiga_117 Resort_Chill_118 Hostel_NH_119 Apartments_Single_Land_120 Apartments_Delphin_121 Apartments_Sky_122 Residence_Lollipop_123 Hotel_Paradise_124 Hostel_Chill_125 Hotel_Paradise_126 Hotel_NH_127 Hostel_Lollipop_128 Hostel_Relax_129 Hotel_Single_Land_130 Hostel_NH_131 Apartments_Single_Land_132 Residence_Relax_133 Resort_Single_Land_134 Hostel_Lollipop_135 Resort_Single_Land_136 Hotel_Delphin_137 Hostel_NH_138 Hostel_Emperor_139 Hotel_Paradise_140 Resort_Emperor_141 Apartments_Lollipop_142 Hostel_Delphin_143 Hostel_Delphin_144 Apartments_Delphin_145 Apartments_Emperor_146 Hotel_Lollipop_147 Hostel_Sky_148 Hotel_Relax_149 Resort_Lollipop_150 Residence_Sky_151 Residence_Sky_152 Hostel_Chill_153 Apartments_Delphin_154 Residence_Arabiga_155 Residence_NH_156 Resort_Delphin_157 Hotel_Sky_158 Residence_Single_Land_159 Hostel_Sky_160 Residence_Emperor_161 Hotel_Paradise_162 Resort_Delphin_163 Resort_Paradise_164 Hostel_Delphin_165 Residence_Lollipop_166 Apartments_Chill_167 Hotel_Arabiga_168 Apartments_Relax_169 Resort_Lollipop_170 Resort_Single_Land_171 Hostel_Sky_172 Resort_Lollipop_173 Residence_Single_Land_174 Hotel_Single_Land_175 Hotel_Chill_176 Resort_Single_Land_177 Residence_Lollipop_178 Apartments_NH_179 Hotel_NH_180 Hotel_Relax_181 Hostel_Delphin_182 Hostel_Delphin_183 Hotel_Single_Land_184 Resort_Relax_185 Resort_Delphin_186 Hostel_Emperor_187 Hotel_Lollipop_188 Residence_Lollipop_189 Resort_Delphin_190 Hotel_Emperor_191 Residence_Paradise_192 Apartments_Relax_193 Resort_Paradise_194 Resort_Sky_195 Residence_Relax_196 Hostel_Single_Land_197 Hostel_Relax_198 Apartments_Single_Land_199 Resort_NH_200 Apartments_Single_Land_201 Apartments_NH_202 Apartments_Sky_203 Apartments_Emperor_204 Apartments_Emperor_205 Apartments_Emperor_206 Resort_Lollipop_207 Hostel_Arabiga_208 Resort_NH_209 Hostel_Lollipop_210 Residence_NH_211 Hotel_Delphin_212 Apartments_Emperor_213 Residence_Emperor_214 Residence_Emperor_215 Hotel_Sky_216 Hostel_Single_Land_217 Apartments_Chill_218 Resort_Arabiga_219 Hotel_Sky_220 Hostel_Relax_221 Resort_Lollipop_222 Residence_NH_223 Apartments_Lollipop_224 Residence_Sky_225 Residence_Relax_226 Apartments_Delphin_227 Residence_Delphin_228 Apartments_NH_229 Hostel_Lollipop_230 Apartments_Arabiga_231 Hostel_Delphin_232 Resort_Chill_233 Residence_Delphin_234 Residence_Chill_235 Resort_Relax_236 Resort_Delphin_237 Resort_Chill_238 Hotel_Emperor_239 Hotel_Arabiga_240 Hostel_NH_241 Resort_Delphin_242 Apartments_Arabiga_243 Hotel_Single_Land_244 Resort_Emperor_245 Hotel_Delphin_246 Hotel_Single_Land_247 Resort_Paradise_248 Residence_Sky_249 Residence_Paradise_250 Residence_Lollipop_251 Hostel_Emperor_252 Resort_Paradise_253 Hotel_Lollipop_254 Residence_Sky_255 Resort_Arabiga_256 Hostel_Lollipop_257 Residence_Relax_258 Apartments_Relax_259 Apartments_Chill_260 Hostel_Single_Land_261 Hostel_Lollipop_262 Resort_Sky_263 Residence_Sky_264 Resort_NH_265 Hotel_Sky_266 Hotel_Arabiga_267 Hotel_Paradise_268 Apartments_Paradise_269 Residence_Arabiga_270 Hostel_Single_Land_271 Hotel_Relax_272 Hotel_Single_Land_273 Resort_Single_Land_274 Resort_Lollipop_275 Resort_Delphin_276 Hostel_Chill_277 Apartments_Lollipop_278 Apartments_Arabiga_279 Hostel_NH_280 Resort_Lollipop_281 Residence_Sky_282 Hotel_Sky_283 Residence_Delphin_284 Resort_Chill_285 Apartments_Arabiga_286 Apartments_Chill_287 Apartments_Emperor_288 Residence_Emperor_289 Apartments_Delphin_290 Apartments_Arabiga_291 Resort_Arabiga_292 Resort_Paradise_293 Resort_Lollipop_294 Apartments_NH_295 Apartments_Chill_296 Apartments_Relax_297 Hostel_Arabiga_298 Apartments_Emperor_299 Resort_Lollipop_300 Resort_Arabiga_301 Apartments_Delphin_302 Resort_Single_Land_303 Residence_Emperor_304 Residence_Paradise_305 Hotel_Single_Land_306 Hostel_Single_Land_307 Hotel_Arabiga_308 Residence_Paradise_309 Hostel_Relax_310 Hostel_Arabiga_311 Hostel_Paradise_312 Hotel_Arabiga_313 Hotel_Relax_314 Hotel_NH_315 Hostel_Paradise_316 Residence_Sky_317 Resort_Paradise_318 Resort_Sky_319 Hotel_NH_320 Hostel_NH_321 Residence_Lollipop_322 Resort_Single_Land_323 Hotel_Arabiga_324 Resort_Sky_325 Apartments_Sky_326 Resort_Arabiga_327 Resort_Arabiga_328 Hostel_Delphin_329 Hotel_Arabiga_330 Hotel_Sky_331 Hotel_NH_332 Resort_Emperor_333 Hostel_Relax_334 Resort_Chill_335 Hotel_Paradise_336 Resort_Chill_337 Apartments_Delphin_338 Apartments_Emperor_339 Residence_Chill_340 Residence_Single_Land_341 Hotel_Arabiga_342 Resort_Emperor_343 Apartments_Sky_344 Apartments_Sky_345 Resort_Emperor_346 Apartments_Relax_347 Residence_Delphin_348 Hotel_Single_Land_349 Resort_NH_350 Residence_Lollipop_351 Residence_Relax_352 Hotel_Sky_353 Hostel_Arabiga_354 Apartments_Emperor_355 Apartments_Emperor_356 Hostel_Chill_357 Apartments_Lollipop_358 Hostel_Arabiga_359 Hotel_Emperor_360 Apartments_Lollipop_361 Resort_Lollipop_362 Hostel_Paradise_363 Hotel_Emperor_364 Apartments_Delphin_365 Hostel_Relax_366 Hotel_Chill_367 Apartments_NH_368 Hostel_Chill_369 Resort_Chill_370 Hotel_Delphin_371 Hostel_Arabiga_372 Residence_Emperor_373 Hostel_Sky_374 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (stay Dublin) 0)
     (= (stay Edinburgh) 0)
     (= (stay Moscow) 0)
     (= (stay Krakow) 0)
     (= (stay Venice) 0)
     (= (stay Saint_Petersburg) 0)
     (= (stay Istanbul) 0)
     (= (stay Rome) 0)
     (= (stay Caracas) 0)
     (= (stay Rio_de_Janeiro) 0)
     (= (stay La_Habana) 0)
     (= (stay Medellin) 0)
     (= (stay Cali) 0)
     (= (stay Washington_DC) 0)
     (= (stay New_York) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 3)
     (= (minDaysCity Sidney) 1)
     (= (maxDaysCity Sidney) 5)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 3)
     (= (minDaysCity Beijing) 2)
     (= (maxDaysCity Beijing) 3)
     (= (minDaysCity Taiwan) 1)
     (= (maxDaysCity Taiwan) 4)
     (= (minDaysCity Tokio) 2)
     (= (maxDaysCity Tokio) 3)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 5)
     (= (minDaysCity Paris) 1)
     (= (maxDaysCity Paris) 5)
     (= (minDaysCity London) 1)
     (= (maxDaysCity London) 4)
     (= (minDaysCity Berlin) 2)
     (= (maxDaysCity Berlin) 5)
     (= (minDaysCity Dublin) 1)
     (= (maxDaysCity Dublin) 4)
     (= (minDaysCity Edinburgh) 2)
     (= (maxDaysCity Edinburgh) 5)
     (= (minDaysCity Moscow) 1)
     (= (maxDaysCity Moscow) 3)
     (= (minDaysCity Krakow) 2)
     (= (maxDaysCity Krakow) 5)
     (= (minDaysCity Venice) 2)
     (= (maxDaysCity Venice) 3)
     (= (minDaysCity Saint_Petersburg) 2)
     (= (maxDaysCity Saint_Petersburg) 5)
     (= (minDaysCity Istanbul) 1)
     (= (maxDaysCity Istanbul) 3)
     (= (minDaysCity Rome) 1)
     (= (maxDaysCity Rome) 4)
     (= (minDaysCity Caracas) 1)
     (= (maxDaysCity Caracas) 3)
     (= (minDaysCity Rio_de_Janeiro) 1)
     (= (maxDaysCity Rio_de_Janeiro) 3)
     (= (minDaysCity La_Habana) 1)
     (= (maxDaysCity La_Habana) 4)
     (= (minDaysCity Medellin) 2)
     (= (maxDaysCity Medellin) 5)
     (= (minDaysCity Cali) 1)
     (= (maxDaysCity Cali) 3)
     (= (minDaysCity Washington_DC) 2)
     (= (maxDaysCity Washington_DC) 4)
     (= (minDaysCity New_York) 2)
     (= (maxDaysCity New_York) 5)
     (= (total-interest) 0)
     (= (cityInterest Melbourne) 2)
     (= (cityInterest Sidney) 1)
     (= (cityInterest Wellington) 1)
     (= (cityInterest Beijing) 1)
     (= (cityInterest Taiwan) 1)
     (= (cityInterest Tokio) 3)
     (= (cityInterest Nova_Dheli) 1)
     (= (cityInterest Paris) 1)
     (= (cityInterest London) 2)
     (= (cityInterest Berlin) 3)
     (= (cityInterest Dublin) 1)
     (= (cityInterest Edinburgh) 2)
     (= (cityInterest Moscow) 3)
     (= (cityInterest Krakow) 2)
     (= (cityInterest Venice) 2)
     (= (cityInterest Saint_Petersburg) 3)
     (= (cityInterest Istanbul) 3)
     (= (cityInterest Rome) 1)
     (= (cityInterest Caracas) 1)
     (= (cityInterest Rio_de_Janeiro) 3)
     (= (cityInterest La_Habana) 2)
     (= (cityInterest Medellin) 1)
     (= (cityInterest Cali) 1)
     (= (cityInterest Washington_DC) 1)
     (= (cityInterest New_York) 1)
     (= (total-price) 0)
     (= (minPriceTrip) 600)
     (= (maxPriceTrip) 900)
     (= (hotelPrice Hostel_Emperor_0) 28)
     (= (hotelPrice Hotel_Arabiga_1) 41)
     (= (hotelPrice Hotel_Emperor_2) 26)
     (= (hotelPrice Residence_Sky_3) 28)
     (= (hotelPrice Hostel_Delphin_4) 45)
     (= (hotelPrice Residence_Single_Land_5) 22)
     (= (hotelPrice Resort_Lollipop_6) 21)
     (= (hotelPrice Hostel_Emperor_7) 39)
     (= (hotelPrice Hostel_Lollipop_8) 49)
     (= (hotelPrice Hostel_Single_Land_9) 36)
     (= (hotelPrice Apartments_Paradise_10) 20)
     (= (hotelPrice Resort_Arabiga_11) 26)
     (= (hotelPrice Hotel_Single_Land_12) 34)
     (= (hotelPrice Apartments_Single_Land_13) 39)
     (= (hotelPrice Hotel_Arabiga_14) 29)
     (= (hotelPrice Residence_Delphin_15) 10)
     (= (hotelPrice Apartments_Single_Land_16) 28)
     (= (hotelPrice Residence_Delphin_17) 39)
     (= (hotelPrice Hostel_Emperor_18) 23)
     (= (hotelPrice Residence_Paradise_19) 11)
     (= (hotelPrice Apartments_Delphin_20) 44)
     (= (hotelPrice Resort_Paradise_21) 28)
     (= (hotelPrice Residence_Relax_22) 39)
     (= (hotelPrice Resort_NH_23) 36)
     (= (hotelPrice Hotel_Chill_24) 37)
     (= (hotelPrice Hostel_Emperor_25) 37)
     (= (hotelPrice Hotel_Paradise_26) 33)
     (= (hotelPrice Apartments_Sky_27) 37)
     (= (hotelPrice Hotel_Single_Land_28) 41)
     (= (hotelPrice Hostel_Sky_29) 22)
     (= (hotelPrice Hotel_Chill_30) 12)
     (= (hotelPrice Residence_Relax_31) 11)
     (= (hotelPrice Hotel_Sky_32) 45)
     (= (hotelPrice Resort_Sky_33) 20)
     (= (hotelPrice Residence_Emperor_34) 29)
     (= (hotelPrice Hotel_Relax_35) 40)
     (= (hotelPrice Hotel_Single_Land_36) 24)
     (= (hotelPrice Residence_Relax_37) 40)
     (= (hotelPrice Resort_Relax_38) 21)
     (= (hotelPrice Hotel_Emperor_39) 23)
     (= (hotelPrice Apartments_Arabiga_40) 27)
     (= (hotelPrice Apartments_Sky_41) 24)
     (= (hotelPrice Resort_NH_42) 31)
     (= (hotelPrice Hostel_Emperor_43) 11)
     (= (hotelPrice Resort_Relax_44) 13)
     (= (hotelPrice Hotel_Single_Land_45) 10)
     (= (hotelPrice Apartments_Sky_46) 43)
     (= (hotelPrice Residence_Delphin_47) 32)
     (= (hotelPrice Hostel_Sky_48) 31)
     (= (hotelPrice Resort_Relax_49) 17)
     (= (hotelPrice Hotel_Chill_50) 25)
     (= (hotelPrice Apartments_Relax_51) 26)
     (= (hotelPrice Hostel_Arabiga_52) 35)
     (= (hotelPrice Residence_Arabiga_53) 14)
     (= (hotelPrice Residence_Arabiga_54) 12)
     (= (hotelPrice Hostel_Single_Land_55) 22)
     (= (hotelPrice Hotel_Paradise_56) 41)
     (= (hotelPrice Hostel_Sky_57) 27)
     (= (hotelPrice Resort_Chill_58) 42)
     (= (hotelPrice Resort_Relax_59) 24)
     (= (hotelPrice Resort_Lollipop_60) 31)
     (= (hotelPrice Residence_Paradise_61) 36)
     (= (hotelPrice Hostel_Arabiga_62) 25)
     (= (hotelPrice Hotel_Paradise_63) 27)
     (= (hotelPrice Residence_Delphin_64) 38)
     (= (hotelPrice Hostel_Arabiga_65) 45)
     (= (hotelPrice Apartments_Arabiga_66) 49)
     (= (hotelPrice Hotel_Sky_67) 12)
     (= (hotelPrice Apartments_Sky_68) 27)
     (= (hotelPrice Resort_Delphin_69) 13)
     (= (hotelPrice Hostel_NH_70) 26)
     (= (hotelPrice Resort_Single_Land_71) 44)
     (= (hotelPrice Resort_Emperor_72) 27)
     (= (hotelPrice Apartments_Lollipop_73) 39)
     (= (hotelPrice Hotel_NH_74) 37)
     (= (hotelPrice Resort_Lollipop_75) 22)
     (= (hotelPrice Apartments_Sky_76) 32)
     (= (hotelPrice Hotel_NH_77) 31)
     (= (hotelPrice Hostel_Sky_78) 36)
     (= (hotelPrice Hotel_Paradise_79) 13)
     (= (hotelPrice Apartments_Delphin_80) 30)
     (= (hotelPrice Apartments_Relax_81) 12)
     (= (hotelPrice Hotel_Paradise_82) 21)
     (= (hotelPrice Hotel_Emperor_83) 15)
     (= (hotelPrice Resort_Relax_84) 16)
     (= (hotelPrice Resort_Relax_85) 15)
     (= (hotelPrice Hostel_Arabiga_86) 20)
     (= (hotelPrice Hostel_Emperor_87) 40)
     (= (hotelPrice Hotel_Arabiga_88) 33)
     (= (hotelPrice Hostel_Delphin_89) 44)
     (= (hotelPrice Hostel_Single_Land_90) 46)
     (= (hotelPrice Apartments_Arabiga_91) 46)
     (= (hotelPrice Residence_Chill_92) 30)
     (= (hotelPrice Hostel_Relax_93) 22)
     (= (hotelPrice Hotel_NH_94) 15)
     (= (hotelPrice Residence_Delphin_95) 18)
     (= (hotelPrice Apartments_Chill_96) 49)
     (= (hotelPrice Apartments_NH_97) 15)
     (= (hotelPrice Hostel_Emperor_98) 20)
     (= (hotelPrice Resort_NH_99) 26)
     (= (hotelPrice Resort_Sky_100) 10)
     (= (hotelPrice Apartments_Emperor_101) 28)
     (= (hotelPrice Apartments_Emperor_102) 13)
     (= (hotelPrice Hotel_Sky_103) 27)
     (= (hotelPrice Apartments_Relax_104) 18)
     (= (hotelPrice Apartments_NH_105) 32)
     (= (hotelPrice Residence_Delphin_106) 31)
     (= (hotelPrice Hostel_Arabiga_107) 40)
     (= (hotelPrice Apartments_Relax_108) 45)
     (= (hotelPrice Apartments_Lollipop_109) 18)
     (= (hotelPrice Resort_Lollipop_110) 35)
     (= (hotelPrice Hotel_Single_Land_111) 25)
     (= (hotelPrice Hotel_Relax_112) 20)
     (= (hotelPrice Resort_Chill_113) 47)
     (= (hotelPrice Hostel_Relax_114) 23)
     (= (hotelPrice Residence_Delphin_115) 18)
     (= (hotelPrice Resort_Single_Land_116) 12)
     (= (hotelPrice Residence_Arabiga_117) 33)
     (= (hotelPrice Resort_Chill_118) 40)
     (= (hotelPrice Hostel_NH_119) 27)
     (= (hotelPrice Apartments_Single_Land_120) 27)
     (= (hotelPrice Apartments_Delphin_121) 37)
     (= (hotelPrice Apartments_Sky_122) 16)
     (= (hotelPrice Residence_Lollipop_123) 39)
     (= (hotelPrice Hotel_Paradise_124) 41)
     (= (hotelPrice Hostel_Chill_125) 21)
     (= (hotelPrice Hotel_Paradise_126) 39)
     (= (hotelPrice Hotel_NH_127) 40)
     (= (hotelPrice Hostel_Lollipop_128) 18)
     (= (hotelPrice Hostel_Relax_129) 49)
     (= (hotelPrice Hotel_Single_Land_130) 48)
     (= (hotelPrice Hostel_NH_131) 18)
     (= (hotelPrice Apartments_Single_Land_132) 20)
     (= (hotelPrice Residence_Relax_133) 43)
     (= (hotelPrice Resort_Single_Land_134) 27)
     (= (hotelPrice Hostel_Lollipop_135) 20)
     (= (hotelPrice Resort_Single_Land_136) 26)
     (= (hotelPrice Hotel_Delphin_137) 49)
     (= (hotelPrice Hostel_NH_138) 42)
     (= (hotelPrice Hostel_Emperor_139) 21)
     (= (hotelPrice Hotel_Paradise_140) 17)
     (= (hotelPrice Resort_Emperor_141) 27)
     (= (hotelPrice Apartments_Lollipop_142) 29)
     (= (hotelPrice Hostel_Delphin_143) 27)
     (= (hotelPrice Hostel_Delphin_144) 16)
     (= (hotelPrice Apartments_Delphin_145) 42)
     (= (hotelPrice Apartments_Emperor_146) 27)
     (= (hotelPrice Hotel_Lollipop_147) 11)
     (= (hotelPrice Hostel_Sky_148) 25)
     (= (hotelPrice Hotel_Relax_149) 18)
     (= (hotelPrice Resort_Lollipop_150) 28)
     (= (hotelPrice Residence_Sky_151) 34)
     (= (hotelPrice Residence_Sky_152) 45)
     (= (hotelPrice Hostel_Chill_153) 26)
     (= (hotelPrice Apartments_Delphin_154) 15)
     (= (hotelPrice Residence_Arabiga_155) 36)
     (= (hotelPrice Residence_NH_156) 38)
     (= (hotelPrice Resort_Delphin_157) 44)
     (= (hotelPrice Hotel_Sky_158) 18)
     (= (hotelPrice Residence_Single_Land_159) 38)
     (= (hotelPrice Hostel_Sky_160) 43)
     (= (hotelPrice Residence_Emperor_161) 48)
     (= (hotelPrice Hotel_Paradise_162) 47)
     (= (hotelPrice Resort_Delphin_163) 45)
     (= (hotelPrice Resort_Paradise_164) 42)
     (= (hotelPrice Hostel_Delphin_165) 24)
     (= (hotelPrice Residence_Lollipop_166) 15)
     (= (hotelPrice Apartments_Chill_167) 10)
     (= (hotelPrice Hotel_Arabiga_168) 15)
     (= (hotelPrice Apartments_Relax_169) 47)
     (= (hotelPrice Resort_Lollipop_170) 13)
     (= (hotelPrice Resort_Single_Land_171) 22)
     (= (hotelPrice Hostel_Sky_172) 17)
     (= (hotelPrice Resort_Lollipop_173) 32)
     (= (hotelPrice Residence_Single_Land_174) 31)
     (= (hotelPrice Hotel_Single_Land_175) 23)
     (= (hotelPrice Hotel_Chill_176) 24)
     (= (hotelPrice Resort_Single_Land_177) 49)
     (= (hotelPrice Residence_Lollipop_178) 24)
     (= (hotelPrice Apartments_NH_179) 31)
     (= (hotelPrice Hotel_NH_180) 49)
     (= (hotelPrice Hotel_Relax_181) 35)
     (= (hotelPrice Hostel_Delphin_182) 47)
     (= (hotelPrice Hostel_Delphin_183) 44)
     (= (hotelPrice Hotel_Single_Land_184) 11)
     (= (hotelPrice Resort_Relax_185) 12)
     (= (hotelPrice Resort_Delphin_186) 22)
     (= (hotelPrice Hostel_Emperor_187) 31)
     (= (hotelPrice Hotel_Lollipop_188) 46)
     (= (hotelPrice Residence_Lollipop_189) 22)
     (= (hotelPrice Resort_Delphin_190) 20)
     (= (hotelPrice Hotel_Emperor_191) 32)
     (= (hotelPrice Residence_Paradise_192) 12)
     (= (hotelPrice Apartments_Relax_193) 49)
     (= (hotelPrice Resort_Paradise_194) 27)
     (= (hotelPrice Resort_Sky_195) 44)
     (= (hotelPrice Residence_Relax_196) 23)
     (= (hotelPrice Hostel_Single_Land_197) 25)
     (= (hotelPrice Hostel_Relax_198) 36)
     (= (hotelPrice Apartments_Single_Land_199) 21)
     (= (hotelPrice Resort_NH_200) 14)
     (= (hotelPrice Apartments_Single_Land_201) 40)
     (= (hotelPrice Apartments_NH_202) 33)
     (= (hotelPrice Apartments_Sky_203) 21)
     (= (hotelPrice Apartments_Emperor_204) 22)
     (= (hotelPrice Apartments_Emperor_205) 47)
     (= (hotelPrice Apartments_Emperor_206) 27)
     (= (hotelPrice Resort_Lollipop_207) 29)
     (= (hotelPrice Hostel_Arabiga_208) 38)
     (= (hotelPrice Resort_NH_209) 41)
     (= (hotelPrice Hostel_Lollipop_210) 10)
     (= (hotelPrice Residence_NH_211) 37)
     (= (hotelPrice Hotel_Delphin_212) 26)
     (= (hotelPrice Apartments_Emperor_213) 40)
     (= (hotelPrice Residence_Emperor_214) 31)
     (= (hotelPrice Residence_Emperor_215) 20)
     (= (hotelPrice Hotel_Sky_216) 42)
     (= (hotelPrice Hostel_Single_Land_217) 35)
     (= (hotelPrice Apartments_Chill_218) 41)
     (= (hotelPrice Resort_Arabiga_219) 39)
     (= (hotelPrice Hotel_Sky_220) 47)
     (= (hotelPrice Hostel_Relax_221) 11)
     (= (hotelPrice Resort_Lollipop_222) 13)
     (= (hotelPrice Residence_NH_223) 41)
     (= (hotelPrice Apartments_Lollipop_224) 42)
     (= (hotelPrice Residence_Sky_225) 30)
     (= (hotelPrice Residence_Relax_226) 36)
     (= (hotelPrice Apartments_Delphin_227) 48)
     (= (hotelPrice Residence_Delphin_228) 37)
     (= (hotelPrice Apartments_NH_229) 14)
     (= (hotelPrice Hostel_Lollipop_230) 19)
     (= (hotelPrice Apartments_Arabiga_231) 42)
     (= (hotelPrice Hostel_Delphin_232) 44)
     (= (hotelPrice Resort_Chill_233) 34)
     (= (hotelPrice Residence_Delphin_234) 45)
     (= (hotelPrice Residence_Chill_235) 49)
     (= (hotelPrice Resort_Relax_236) 31)
     (= (hotelPrice Resort_Delphin_237) 22)
     (= (hotelPrice Resort_Chill_238) 28)
     (= (hotelPrice Hotel_Emperor_239) 19)
     (= (hotelPrice Hotel_Arabiga_240) 46)
     (= (hotelPrice Hostel_NH_241) 20)
     (= (hotelPrice Resort_Delphin_242) 46)
     (= (hotelPrice Apartments_Arabiga_243) 14)
     (= (hotelPrice Hotel_Single_Land_244) 10)
     (= (hotelPrice Resort_Emperor_245) 19)
     (= (hotelPrice Hotel_Delphin_246) 24)
     (= (hotelPrice Hotel_Single_Land_247) 35)
     (= (hotelPrice Resort_Paradise_248) 44)
     (= (hotelPrice Residence_Sky_249) 16)
     (= (hotelPrice Residence_Paradise_250) 16)
     (= (hotelPrice Residence_Lollipop_251) 33)
     (= (hotelPrice Hostel_Emperor_252) 49)
     (= (hotelPrice Resort_Paradise_253) 19)
     (= (hotelPrice Hotel_Lollipop_254) 25)
     (= (hotelPrice Residence_Sky_255) 42)
     (= (hotelPrice Resort_Arabiga_256) 31)
     (= (hotelPrice Hostel_Lollipop_257) 43)
     (= (hotelPrice Residence_Relax_258) 40)
     (= (hotelPrice Apartments_Relax_259) 19)
     (= (hotelPrice Apartments_Chill_260) 39)
     (= (hotelPrice Hostel_Single_Land_261) 41)
     (= (hotelPrice Hostel_Lollipop_262) 43)
     (= (hotelPrice Resort_Sky_263) 34)
     (= (hotelPrice Residence_Sky_264) 25)
     (= (hotelPrice Resort_NH_265) 38)
     (= (hotelPrice Hotel_Sky_266) 25)
     (= (hotelPrice Hotel_Arabiga_267) 47)
     (= (hotelPrice Hotel_Paradise_268) 43)
     (= (hotelPrice Apartments_Paradise_269) 43)
     (= (hotelPrice Residence_Arabiga_270) 48)
     (= (hotelPrice Hostel_Single_Land_271) 39)
     (= (hotelPrice Hotel_Relax_272) 45)
     (= (hotelPrice Hotel_Single_Land_273) 45)
     (= (hotelPrice Resort_Single_Land_274) 43)
     (= (hotelPrice Resort_Lollipop_275) 38)
     (= (hotelPrice Resort_Delphin_276) 46)
     (= (hotelPrice Hostel_Chill_277) 10)
     (= (hotelPrice Apartments_Lollipop_278) 23)
     (= (hotelPrice Apartments_Arabiga_279) 33)
     (= (hotelPrice Hostel_NH_280) 16)
     (= (hotelPrice Resort_Lollipop_281) 21)
     (= (hotelPrice Residence_Sky_282) 48)
     (= (hotelPrice Hotel_Sky_283) 47)
     (= (hotelPrice Residence_Delphin_284) 30)
     (= (hotelPrice Resort_Chill_285) 15)
     (= (hotelPrice Apartments_Arabiga_286) 31)
     (= (hotelPrice Apartments_Chill_287) 11)
     (= (hotelPrice Apartments_Emperor_288) 40)
     (= (hotelPrice Residence_Emperor_289) 13)
     (= (hotelPrice Apartments_Delphin_290) 20)
     (= (hotelPrice Apartments_Arabiga_291) 30)
     (= (hotelPrice Resort_Arabiga_292) 44)
     (= (hotelPrice Resort_Paradise_293) 45)
     (= (hotelPrice Resort_Lollipop_294) 14)
     (= (hotelPrice Apartments_NH_295) 12)
     (= (hotelPrice Apartments_Chill_296) 34)
     (= (hotelPrice Apartments_Relax_297) 29)
     (= (hotelPrice Hostel_Arabiga_298) 49)
     (= (hotelPrice Apartments_Emperor_299) 19)
     (= (hotelPrice Resort_Lollipop_300) 14)
     (= (hotelPrice Resort_Arabiga_301) 39)
     (= (hotelPrice Apartments_Delphin_302) 48)
     (= (hotelPrice Resort_Single_Land_303) 41)
     (= (hotelPrice Residence_Emperor_304) 26)
     (= (hotelPrice Residence_Paradise_305) 33)
     (= (hotelPrice Hotel_Single_Land_306) 29)
     (= (hotelPrice Hostel_Single_Land_307) 23)
     (= (hotelPrice Hotel_Arabiga_308) 33)
     (= (hotelPrice Residence_Paradise_309) 34)
     (= (hotelPrice Hostel_Relax_310) 46)
     (= (hotelPrice Hostel_Arabiga_311) 31)
     (= (hotelPrice Hostel_Paradise_312) 45)
     (= (hotelPrice Hotel_Arabiga_313) 36)
     (= (hotelPrice Hotel_Relax_314) 21)
     (= (hotelPrice Hotel_NH_315) 17)
     (= (hotelPrice Hostel_Paradise_316) 42)
     (= (hotelPrice Residence_Sky_317) 42)
     (= (hotelPrice Resort_Paradise_318) 19)
     (= (hotelPrice Resort_Sky_319) 32)
     (= (hotelPrice Hotel_NH_320) 38)
     (= (hotelPrice Hostel_NH_321) 21)
     (= (hotelPrice Residence_Lollipop_322) 12)
     (= (hotelPrice Resort_Single_Land_323) 24)
     (= (hotelPrice Hotel_Arabiga_324) 17)
     (= (hotelPrice Resort_Sky_325) 48)
     (= (hotelPrice Apartments_Sky_326) 26)
     (= (hotelPrice Resort_Arabiga_327) 33)
     (= (hotelPrice Resort_Arabiga_328) 27)
     (= (hotelPrice Hostel_Delphin_329) 17)
     (= (hotelPrice Hotel_Arabiga_330) 42)
     (= (hotelPrice Hotel_Sky_331) 23)
     (= (hotelPrice Hotel_NH_332) 47)
     (= (hotelPrice Resort_Emperor_333) 32)
     (= (hotelPrice Hostel_Relax_334) 15)
     (= (hotelPrice Resort_Chill_335) 23)
     (= (hotelPrice Hotel_Paradise_336) 47)
     (= (hotelPrice Resort_Chill_337) 26)
     (= (hotelPrice Apartments_Delphin_338) 28)
     (= (hotelPrice Apartments_Emperor_339) 31)
     (= (hotelPrice Residence_Chill_340) 43)
     (= (hotelPrice Residence_Single_Land_341) 16)
     (= (hotelPrice Hotel_Arabiga_342) 44)
     (= (hotelPrice Resort_Emperor_343) 30)
     (= (hotelPrice Apartments_Sky_344) 43)
     (= (hotelPrice Apartments_Sky_345) 15)
     (= (hotelPrice Resort_Emperor_346) 38)
     (= (hotelPrice Apartments_Relax_347) 35)
     (= (hotelPrice Residence_Delphin_348) 40)
     (= (hotelPrice Hotel_Single_Land_349) 39)
     (= (hotelPrice Resort_NH_350) 49)
     (= (hotelPrice Residence_Lollipop_351) 28)
     (= (hotelPrice Residence_Relax_352) 10)
     (= (hotelPrice Hotel_Sky_353) 12)
     (= (hotelPrice Hostel_Arabiga_354) 34)
     (= (hotelPrice Apartments_Emperor_355) 49)
     (= (hotelPrice Apartments_Emperor_356) 10)
     (= (hotelPrice Hostel_Chill_357) 11)
     (= (hotelPrice Apartments_Lollipop_358) 32)
     (= (hotelPrice Hostel_Arabiga_359) 20)
     (= (hotelPrice Hotel_Emperor_360) 10)
     (= (hotelPrice Apartments_Lollipop_361) 16)
     (= (hotelPrice Resort_Lollipop_362) 33)
     (= (hotelPrice Hostel_Paradise_363) 39)
     (= (hotelPrice Hotel_Emperor_364) 30)
     (= (hotelPrice Apartments_Delphin_365) 38)
     (= (hotelPrice Hostel_Relax_366) 13)
     (= (hotelPrice Hotel_Chill_367) 28)
     (= (hotelPrice Apartments_NH_368) 47)
     (= (hotelPrice Hostel_Chill_369) 23)
     (= (hotelPrice Resort_Chill_370) 41)
     (= (hotelPrice Hotel_Delphin_371) 40)
     (= (hotelPrice Hostel_Arabiga_372) 30)
     (= (hotelPrice Residence_Emperor_373) 35)
     (= (hotelPrice Hostel_Sky_374) 20)
     (flight Melbourne Sidney)
     (= (flightPrice Melbourne Sidney) 93)
     (flight Melbourne Wellington)
     (= (flightPrice Melbourne Wellington) 111)
     (flight Melbourne Beijing)
     (= (flightPrice Melbourne Beijing) 118)
     (flight Melbourne Taiwan)
     (= (flightPrice Melbourne Taiwan) 110)
     (flight Melbourne Tokio)
     (= (flightPrice Melbourne Tokio) 101)
     (flight Melbourne Nova_Dheli)
     (= (flightPrice Melbourne Nova_Dheli) 107)
     (flight Melbourne Paris)
     (= (flightPrice Melbourne Paris) 109)
     (flight Melbourne London)
     (= (flightPrice Melbourne London) 111)
     (flight Melbourne Berlin)
     (= (flightPrice Melbourne Berlin) 100)
     (flight Melbourne Dublin)
     (= (flightPrice Melbourne Dublin) 103)
     (flight Melbourne Edinburgh)
     (= (flightPrice Melbourne Edinburgh) 95)
     (flight Melbourne Moscow)
     (= (flightPrice Melbourne Moscow) 99)
     (flight Melbourne Krakow)
     (= (flightPrice Melbourne Krakow) 104)
     (flight Melbourne Venice)
     (= (flightPrice Melbourne Venice) 88)
     (flight Melbourne Saint_Petersburg)
     (= (flightPrice Melbourne Saint_Petersburg) 114)
     (flight Melbourne Istanbul)
     (= (flightPrice Melbourne Istanbul) 106)
     (flight Melbourne Rome)
     (= (flightPrice Melbourne Rome) 89)
     (flight Melbourne Caracas)
     (= (flightPrice Melbourne Caracas) 112)
     (flight Melbourne Rio_de_Janeiro)
     (= (flightPrice Melbourne Rio_de_Janeiro) 89)
     (flight Melbourne La_Habana)
     (= (flightPrice Melbourne La_Habana) 110)
     (flight Melbourne Medellin)
     (= (flightPrice Melbourne Medellin) 93)
     (flight Melbourne Cali)
     (= (flightPrice Melbourne Cali) 110)
     (flight Melbourne Washington_DC)
     (= (flightPrice Melbourne Washington_DC) 113)
     (flight Melbourne New_York)
     (= (flightPrice Melbourne New_York) 103)
     (flight Sidney Melbourne)
     (= (flightPrice Sidney Melbourne) 107)
     (flight Sidney Wellington)
     (= (flightPrice Sidney Wellington) 119)
     (flight Sidney Beijing)
     (= (flightPrice Sidney Beijing) 94)
     (flight Sidney Taiwan)
     (= (flightPrice Sidney Taiwan) 89)
     (flight Sidney Tokio)
     (= (flightPrice Sidney Tokio) 99)
     (flight Sidney Nova_Dheli)
     (= (flightPrice Sidney Nova_Dheli) 111)
     (flight Sidney Paris)
     (= (flightPrice Sidney Paris) 99)
     (flight Sidney London)
     (= (flightPrice Sidney London) 104)
     (flight Sidney Berlin)
     (= (flightPrice Sidney Berlin) 102)
     (flight Sidney Dublin)
     (= (flightPrice Sidney Dublin) 90)
     (flight Sidney Edinburgh)
     (= (flightPrice Sidney Edinburgh) 86)
     (flight Sidney Moscow)
     (= (flightPrice Sidney Moscow) 115)
     (flight Sidney Krakow)
     (= (flightPrice Sidney Krakow) 109)
     (flight Sidney Venice)
     (= (flightPrice Sidney Venice) 115)
     (flight Sidney Saint_Petersburg)
     (= (flightPrice Sidney Saint_Petersburg) 106)
     (flight Sidney Istanbul)
     (= (flightPrice Sidney Istanbul) 81)
     (flight Sidney Rome)
     (= (flightPrice Sidney Rome) 91)
     (flight Sidney Caracas)
     (= (flightPrice Sidney Caracas) 114)
     (flight Sidney Rio_de_Janeiro)
     (= (flightPrice Sidney Rio_de_Janeiro) 93)
     (flight Sidney La_Habana)
     (= (flightPrice Sidney La_Habana) 107)
     (flight Sidney Medellin)
     (= (flightPrice Sidney Medellin) 82)
     (flight Sidney Cali)
     (= (flightPrice Sidney Cali) 87)
     (flight Sidney Washington_DC)
     (= (flightPrice Sidney Washington_DC) 93)
     (flight Sidney New_York)
     (= (flightPrice Sidney New_York) 83)
     (flight Wellington Melbourne)
     (= (flightPrice Wellington Melbourne) 119)
     (flight Wellington Sidney)
     (= (flightPrice Wellington Sidney) 102)
     (flight Wellington Beijing)
     (= (flightPrice Wellington Beijing) 114)
     (flight Wellington Taiwan)
     (= (flightPrice Wellington Taiwan) 84)
     (flight Wellington Tokio)
     (= (flightPrice Wellington Tokio) 84)
     (flight Wellington Nova_Dheli)
     (= (flightPrice Wellington Nova_Dheli) 99)
     (flight Wellington Paris)
     (= (flightPrice Wellington Paris) 99)
     (flight Wellington London)
     (= (flightPrice Wellington London) 103)
     (flight Wellington Berlin)
     (= (flightPrice Wellington Berlin) 98)
     (flight Wellington Dublin)
     (= (flightPrice Wellington Dublin) 113)
     (flight Wellington Edinburgh)
     (= (flightPrice Wellington Edinburgh) 112)
     (flight Wellington Moscow)
     (= (flightPrice Wellington Moscow) 109)
     (flight Wellington Krakow)
     (= (flightPrice Wellington Krakow) 105)
     (flight Wellington Venice)
     (= (flightPrice Wellington Venice) 84)
     (flight Wellington Saint_Petersburg)
     (= (flightPrice Wellington Saint_Petersburg) 93)
     (flight Wellington Istanbul)
     (= (flightPrice Wellington Istanbul) 119)
     (flight Wellington Rome)
     (= (flightPrice Wellington Rome) 94)
     (flight Wellington Caracas)
     (= (flightPrice Wellington Caracas) 99)
     (flight Wellington Rio_de_Janeiro)
     (= (flightPrice Wellington Rio_de_Janeiro) 115)
     (flight Wellington La_Habana)
     (= (flightPrice Wellington La_Habana) 115)
     (flight Wellington Medellin)
     (= (flightPrice Wellington Medellin) 87)
     (flight Wellington Cali)
     (= (flightPrice Wellington Cali) 93)
     (flight Wellington Washington_DC)
     (= (flightPrice Wellington Washington_DC) 109)
     (flight Wellington New_York)
     (= (flightPrice Wellington New_York) 90)
     (flight Beijing Melbourne)
     (= (flightPrice Beijing Melbourne) 87)
     (flight Beijing Sidney)
     (= (flightPrice Beijing Sidney) 82)
     (flight Beijing Wellington)
     (= (flightPrice Beijing Wellington) 117)
     (flight Beijing Taiwan)
     (= (flightPrice Beijing Taiwan) 82)
     (flight Beijing Tokio)
     (= (flightPrice Beijing Tokio) 89)
     (flight Beijing Nova_Dheli)
     (= (flightPrice Beijing Nova_Dheli) 90)
     (flight Beijing Paris)
     (= (flightPrice Beijing Paris) 85)
     (flight Beijing London)
     (= (flightPrice Beijing London) 80)
     (flight Beijing Berlin)
     (= (flightPrice Beijing Berlin) 104)
     (flight Beijing Dublin)
     (= (flightPrice Beijing Dublin) 111)
     (flight Beijing Edinburgh)
     (= (flightPrice Beijing Edinburgh) 117)
     (flight Beijing Moscow)
     (= (flightPrice Beijing Moscow) 109)
     (flight Beijing Krakow)
     (= (flightPrice Beijing Krakow) 83)
     (flight Beijing Venice)
     (= (flightPrice Beijing Venice) 96)
     (flight Beijing Saint_Petersburg)
     (= (flightPrice Beijing Saint_Petersburg) 92)
     (flight Beijing Istanbul)
     (= (flightPrice Beijing Istanbul) 101)
     (flight Beijing Rome)
     (= (flightPrice Beijing Rome) 82)
     (flight Beijing Caracas)
     (= (flightPrice Beijing Caracas) 85)
     (flight Beijing Rio_de_Janeiro)
     (= (flightPrice Beijing Rio_de_Janeiro) 83)
     (flight Beijing La_Habana)
     (= (flightPrice Beijing La_Habana) 99)
     (flight Beijing Medellin)
     (= (flightPrice Beijing Medellin) 81)
     (flight Beijing Cali)
     (= (flightPrice Beijing Cali) 88)
     (flight Beijing Washington_DC)
     (= (flightPrice Beijing Washington_DC) 98)
     (flight Beijing New_York)
     (= (flightPrice Beijing New_York) 87)
     (flight Taiwan Melbourne)
     (= (flightPrice Taiwan Melbourne) 100)
     (flight Taiwan Sidney)
     (= (flightPrice Taiwan Sidney) 85)
     (flight Taiwan Wellington)
     (= (flightPrice Taiwan Wellington) 82)
     (flight Taiwan Beijing)
     (= (flightPrice Taiwan Beijing) 107)
     (flight Taiwan Tokio)
     (= (flightPrice Taiwan Tokio) 99)
     (flight Taiwan Nova_Dheli)
     (= (flightPrice Taiwan Nova_Dheli) 111)
     (flight Taiwan Paris)
     (= (flightPrice Taiwan Paris) 109)
     (flight Taiwan London)
     (= (flightPrice Taiwan London) 106)
     (flight Taiwan Berlin)
     (= (flightPrice Taiwan Berlin) 113)
     (flight Taiwan Dublin)
     (= (flightPrice Taiwan Dublin) 106)
     (flight Taiwan Edinburgh)
     (= (flightPrice Taiwan Edinburgh) 108)
     (flight Taiwan Moscow)
     (= (flightPrice Taiwan Moscow) 114)
     (flight Taiwan Krakow)
     (= (flightPrice Taiwan Krakow) 116)
     (flight Taiwan Venice)
     (= (flightPrice Taiwan Venice) 106)
     (flight Taiwan Saint_Petersburg)
     (= (flightPrice Taiwan Saint_Petersburg) 107)
     (flight Taiwan Istanbul)
     (= (flightPrice Taiwan Istanbul) 92)
     (flight Taiwan Rome)
     (= (flightPrice Taiwan Rome) 97)
     (flight Taiwan Caracas)
     (= (flightPrice Taiwan Caracas) 104)
     (flight Taiwan Rio_de_Janeiro)
     (= (flightPrice Taiwan Rio_de_Janeiro) 81)
     (flight Taiwan La_Habana)
     (= (flightPrice Taiwan La_Habana) 100)
     (flight Taiwan Medellin)
     (= (flightPrice Taiwan Medellin) 80)
     (flight Taiwan Cali)
     (= (flightPrice Taiwan Cali) 86)
     (flight Taiwan Washington_DC)
     (= (flightPrice Taiwan Washington_DC) 114)
     (flight Taiwan New_York)
     (= (flightPrice Taiwan New_York) 114)
     (flight Tokio Melbourne)
     (= (flightPrice Tokio Melbourne) 83)
     (flight Tokio Sidney)
     (= (flightPrice Tokio Sidney) 117)
     (flight Tokio Wellington)
     (= (flightPrice Tokio Wellington) 93)
     (flight Tokio Beijing)
     (= (flightPrice Tokio Beijing) 84)
     (flight Tokio Taiwan)
     (= (flightPrice Tokio Taiwan) 117)
     (flight Tokio Nova_Dheli)
     (= (flightPrice Tokio Nova_Dheli) 112)
     (flight Tokio Paris)
     (= (flightPrice Tokio Paris) 91)
     (flight Tokio London)
     (= (flightPrice Tokio London) 97)
     (flight Tokio Berlin)
     (= (flightPrice Tokio Berlin) 109)
     (flight Tokio Dublin)
     (= (flightPrice Tokio Dublin) 85)
     (flight Tokio Edinburgh)
     (= (flightPrice Tokio Edinburgh) 116)
     (flight Tokio Moscow)
     (= (flightPrice Tokio Moscow) 88)
     (flight Tokio Krakow)
     (= (flightPrice Tokio Krakow) 109)
     (flight Tokio Venice)
     (= (flightPrice Tokio Venice) 105)
     (flight Tokio Saint_Petersburg)
     (= (flightPrice Tokio Saint_Petersburg) 115)
     (flight Tokio Istanbul)
     (= (flightPrice Tokio Istanbul) 102)
     (flight Tokio Rome)
     (= (flightPrice Tokio Rome) 91)
     (flight Tokio Caracas)
     (= (flightPrice Tokio Caracas) 95)
     (flight Tokio Rio_de_Janeiro)
     (= (flightPrice Tokio Rio_de_Janeiro) 89)
     (flight Tokio La_Habana)
     (= (flightPrice Tokio La_Habana) 119)
     (flight Tokio Medellin)
     (= (flightPrice Tokio Medellin) 81)
     (flight Tokio Cali)
     (= (flightPrice Tokio Cali) 116)
     (flight Tokio Washington_DC)
     (= (flightPrice Tokio Washington_DC) 92)
     (flight Tokio New_York)
     (= (flightPrice Tokio New_York) 91)
     (flight Nova_Dheli Melbourne)
     (= (flightPrice Nova_Dheli Melbourne) 100)
     (flight Nova_Dheli Sidney)
     (= (flightPrice Nova_Dheli Sidney) 85)
     (flight Nova_Dheli Wellington)
     (= (flightPrice Nova_Dheli Wellington) 103)
     (flight Nova_Dheli Beijing)
     (= (flightPrice Nova_Dheli Beijing) 92)
     (flight Nova_Dheli Taiwan)
     (= (flightPrice Nova_Dheli Taiwan) 91)
     (flight Nova_Dheli Tokio)
     (= (flightPrice Nova_Dheli Tokio) 89)
     (flight Nova_Dheli Paris)
     (= (flightPrice Nova_Dheli Paris) 87)
     (flight Nova_Dheli London)
     (= (flightPrice Nova_Dheli London) 86)
     (flight Nova_Dheli Berlin)
     (= (flightPrice Nova_Dheli Berlin) 118)
     (flight Nova_Dheli Dublin)
     (= (flightPrice Nova_Dheli Dublin) 92)
     (flight Nova_Dheli Edinburgh)
     (= (flightPrice Nova_Dheli Edinburgh) 90)
     (flight Nova_Dheli Moscow)
     (= (flightPrice Nova_Dheli Moscow) 116)
     (flight Nova_Dheli Krakow)
     (= (flightPrice Nova_Dheli Krakow) 84)
     (flight Nova_Dheli Venice)
     (= (flightPrice Nova_Dheli Venice) 93)
     (flight Nova_Dheli Saint_Petersburg)
     (= (flightPrice Nova_Dheli Saint_Petersburg) 93)
     (flight Nova_Dheli Istanbul)
     (= (flightPrice Nova_Dheli Istanbul) 106)
     (flight Nova_Dheli Rome)
     (= (flightPrice Nova_Dheli Rome) 99)
     (flight Nova_Dheli Caracas)
     (= (flightPrice Nova_Dheli Caracas) 90)
     (flight Nova_Dheli Rio_de_Janeiro)
     (= (flightPrice Nova_Dheli Rio_de_Janeiro) 114)
     (flight Nova_Dheli La_Habana)
     (= (flightPrice Nova_Dheli La_Habana) 88)
     (flight Nova_Dheli Medellin)
     (= (flightPrice Nova_Dheli Medellin) 115)
     (flight Nova_Dheli Cali)
     (= (flightPrice Nova_Dheli Cali) 101)
     (flight Nova_Dheli Washington_DC)
     (= (flightPrice Nova_Dheli Washington_DC) 102)
     (flight Nova_Dheli New_York)
     (= (flightPrice Nova_Dheli New_York) 119)
     (flight Paris Melbourne)
     (= (flightPrice Paris Melbourne) 117)
     (flight Paris Sidney)
     (= (flightPrice Paris Sidney) 103)
     (flight Paris Wellington)
     (= (flightPrice Paris Wellington) 118)
     (flight Paris Beijing)
     (= (flightPrice Paris Beijing) 110)
     (flight Paris Taiwan)
     (= (flightPrice Paris Taiwan) 99)
     (flight Paris Tokio)
     (= (flightPrice Paris Tokio) 82)
     (flight Paris Nova_Dheli)
     (= (flightPrice Paris Nova_Dheli) 113)
     (flight Paris London)
     (= (flightPrice Paris London) 111)
     (flight Paris Berlin)
     (= (flightPrice Paris Berlin) 88)
     (flight Paris Dublin)
     (= (flightPrice Paris Dublin) 97)
     (flight Paris Edinburgh)
     (= (flightPrice Paris Edinburgh) 84)
     (flight Paris Moscow)
     (= (flightPrice Paris Moscow) 91)
     (flight Paris Krakow)
     (= (flightPrice Paris Krakow) 106)
     (flight Paris Venice)
     (= (flightPrice Paris Venice) 83)
     (flight Paris Saint_Petersburg)
     (= (flightPrice Paris Saint_Petersburg) 98)
     (flight Paris Istanbul)
     (= (flightPrice Paris Istanbul) 105)
     (flight Paris Rome)
     (= (flightPrice Paris Rome) 95)
     (flight Paris Caracas)
     (= (flightPrice Paris Caracas) 100)
     (flight Paris Rio_de_Janeiro)
     (= (flightPrice Paris Rio_de_Janeiro) 101)
     (flight Paris La_Habana)
     (= (flightPrice Paris La_Habana) 92)
     (flight Paris Medellin)
     (= (flightPrice Paris Medellin) 106)
     (flight Paris Cali)
     (= (flightPrice Paris Cali) 114)
     (flight Paris Washington_DC)
     (= (flightPrice Paris Washington_DC) 118)
     (flight Paris New_York)
     (= (flightPrice Paris New_York) 85)
     (flight London Melbourne)
     (= (flightPrice London Melbourne) 116)
     (flight London Sidney)
     (= (flightPrice London Sidney) 112)
     (flight London Wellington)
     (= (flightPrice London Wellington) 85)
     (flight London Beijing)
     (= (flightPrice London Beijing) 112)
     (flight London Taiwan)
     (= (flightPrice London Taiwan) 86)
     (flight London Tokio)
     (= (flightPrice London Tokio) 99)
     (flight London Nova_Dheli)
     (= (flightPrice London Nova_Dheli) 111)
     (flight London Paris)
     (= (flightPrice London Paris) 83)
     (flight London Berlin)
     (= (flightPrice London Berlin) 83)
     (flight London Dublin)
     (= (flightPrice London Dublin) 101)
     (flight London Edinburgh)
     (= (flightPrice London Edinburgh) 105)
     (flight London Moscow)
     (= (flightPrice London Moscow) 102)
     (flight London Krakow)
     (= (flightPrice London Krakow) 96)
     (flight London Venice)
     (= (flightPrice London Venice) 99)
     (flight London Saint_Petersburg)
     (= (flightPrice London Saint_Petersburg) 94)
     (flight London Istanbul)
     (= (flightPrice London Istanbul) 104)
     (flight London Rome)
     (= (flightPrice London Rome) 116)
     (flight London Caracas)
     (= (flightPrice London Caracas) 90)
     (flight London Rio_de_Janeiro)
     (= (flightPrice London Rio_de_Janeiro) 107)
     (flight London La_Habana)
     (= (flightPrice London La_Habana) 94)
     (flight London Medellin)
     (= (flightPrice London Medellin) 93)
     (flight London Cali)
     (= (flightPrice London Cali) 117)
     (flight London Washington_DC)
     (= (flightPrice London Washington_DC) 119)
     (flight London New_York)
     (= (flightPrice London New_York) 100)
     (flight Berlin Melbourne)
     (= (flightPrice Berlin Melbourne) 90)
     (flight Berlin Sidney)
     (= (flightPrice Berlin Sidney) 92)
     (flight Berlin Wellington)
     (= (flightPrice Berlin Wellington) 112)
     (flight Berlin Beijing)
     (= (flightPrice Berlin Beijing) 116)
     (flight Berlin Taiwan)
     (= (flightPrice Berlin Taiwan) 119)
     (flight Berlin Tokio)
     (= (flightPrice Berlin Tokio) 110)
     (flight Berlin Nova_Dheli)
     (= (flightPrice Berlin Nova_Dheli) 113)
     (flight Berlin Paris)
     (= (flightPrice Berlin Paris) 115)
     (flight Berlin London)
     (= (flightPrice Berlin London) 95)
     (flight Berlin Dublin)
     (= (flightPrice Berlin Dublin) 118)
     (flight Berlin Edinburgh)
     (= (flightPrice Berlin Edinburgh) 107)
     (flight Berlin Moscow)
     (= (flightPrice Berlin Moscow) 101)
     (flight Berlin Krakow)
     (= (flightPrice Berlin Krakow) 97)
     (flight Berlin Venice)
     (= (flightPrice Berlin Venice) 90)
     (flight Berlin Saint_Petersburg)
     (= (flightPrice Berlin Saint_Petersburg) 96)
     (flight Berlin Istanbul)
     (= (flightPrice Berlin Istanbul) 100)
     (flight Berlin Rome)
     (= (flightPrice Berlin Rome) 104)
     (flight Berlin Caracas)
     (= (flightPrice Berlin Caracas) 81)
     (flight Berlin Rio_de_Janeiro)
     (= (flightPrice Berlin Rio_de_Janeiro) 83)
     (flight Berlin La_Habana)
     (= (flightPrice Berlin La_Habana) 80)
     (flight Berlin Medellin)
     (= (flightPrice Berlin Medellin) 92)
     (flight Berlin Cali)
     (= (flightPrice Berlin Cali) 89)
     (flight Berlin Washington_DC)
     (= (flightPrice Berlin Washington_DC) 96)
     (flight Berlin New_York)
     (= (flightPrice Berlin New_York) 80)
     (flight Dublin Melbourne)
     (= (flightPrice Dublin Melbourne) 99)
     (flight Dublin Sidney)
     (= (flightPrice Dublin Sidney) 83)
     (flight Dublin Wellington)
     (= (flightPrice Dublin Wellington) 95)
     (flight Dublin Beijing)
     (= (flightPrice Dublin Beijing) 104)
     (flight Dublin Taiwan)
     (= (flightPrice Dublin Taiwan) 113)
     (flight Dublin Tokio)
     (= (flightPrice Dublin Tokio) 86)
     (flight Dublin Nova_Dheli)
     (= (flightPrice Dublin Nova_Dheli) 84)
     (flight Dublin Paris)
     (= (flightPrice Dublin Paris) 83)
     (flight Dublin London)
     (= (flightPrice Dublin London) 91)
     (flight Dublin Berlin)
     (= (flightPrice Dublin Berlin) 109)
     (flight Dublin Edinburgh)
     (= (flightPrice Dublin Edinburgh) 111)
     (flight Dublin Moscow)
     (= (flightPrice Dublin Moscow) 90)
     (flight Dublin Krakow)
     (= (flightPrice Dublin Krakow) 99)
     (flight Dublin Venice)
     (= (flightPrice Dublin Venice) 104)
     (flight Dublin Saint_Petersburg)
     (= (flightPrice Dublin Saint_Petersburg) 85)
     (flight Dublin Istanbul)
     (= (flightPrice Dublin Istanbul) 106)
     (flight Dublin Rome)
     (= (flightPrice Dublin Rome) 102)
     (flight Dublin Caracas)
     (= (flightPrice Dublin Caracas) 105)
     (flight Dublin Rio_de_Janeiro)
     (= (flightPrice Dublin Rio_de_Janeiro) 119)
     (flight Dublin La_Habana)
     (= (flightPrice Dublin La_Habana) 111)
     (flight Dublin Medellin)
     (= (flightPrice Dublin Medellin) 107)
     (flight Dublin Cali)
     (= (flightPrice Dublin Cali) 87)
     (flight Dublin Washington_DC)
     (= (flightPrice Dublin Washington_DC) 84)
     (flight Dublin New_York)
     (= (flightPrice Dublin New_York) 91)
     (flight Edinburgh Melbourne)
     (= (flightPrice Edinburgh Melbourne) 81)
     (flight Edinburgh Sidney)
     (= (flightPrice Edinburgh Sidney) 119)
     (flight Edinburgh Wellington)
     (= (flightPrice Edinburgh Wellington) 91)
     (flight Edinburgh Beijing)
     (= (flightPrice Edinburgh Beijing) 93)
     (flight Edinburgh Taiwan)
     (= (flightPrice Edinburgh Taiwan) 88)
     (flight Edinburgh Tokio)
     (= (flightPrice Edinburgh Tokio) 107)
     (flight Edinburgh Nova_Dheli)
     (= (flightPrice Edinburgh Nova_Dheli) 94)
     (flight Edinburgh Paris)
     (= (flightPrice Edinburgh Paris) 99)
     (flight Edinburgh London)
     (= (flightPrice Edinburgh London) 103)
     (flight Edinburgh Berlin)
     (= (flightPrice Edinburgh Berlin) 101)
     (flight Edinburgh Dublin)
     (= (flightPrice Edinburgh Dublin) 83)
     (flight Edinburgh Moscow)
     (= (flightPrice Edinburgh Moscow) 88)
     (flight Edinburgh Krakow)
     (= (flightPrice Edinburgh Krakow) 107)
     (flight Edinburgh Venice)
     (= (flightPrice Edinburgh Venice) 119)
     (flight Edinburgh Saint_Petersburg)
     (= (flightPrice Edinburgh Saint_Petersburg) 83)
     (flight Edinburgh Istanbul)
     (= (flightPrice Edinburgh Istanbul) 118)
     (flight Edinburgh Rome)
     (= (flightPrice Edinburgh Rome) 108)
     (flight Edinburgh Caracas)
     (= (flightPrice Edinburgh Caracas) 114)
     (flight Edinburgh Rio_de_Janeiro)
     (= (flightPrice Edinburgh Rio_de_Janeiro) 80)
     (flight Edinburgh La_Habana)
     (= (flightPrice Edinburgh La_Habana) 80)
     (flight Edinburgh Medellin)
     (= (flightPrice Edinburgh Medellin) 98)
     (flight Edinburgh Cali)
     (= (flightPrice Edinburgh Cali) 86)
     (flight Edinburgh Washington_DC)
     (= (flightPrice Edinburgh Washington_DC) 98)
     (flight Edinburgh New_York)
     (= (flightPrice Edinburgh New_York) 112)
     (flight Moscow Melbourne)
     (= (flightPrice Moscow Melbourne) 103)
     (flight Moscow Sidney)
     (= (flightPrice Moscow Sidney) 98)
     (flight Moscow Wellington)
     (= (flightPrice Moscow Wellington) 95)
     (flight Moscow Beijing)
     (= (flightPrice Moscow Beijing) 90)
     (flight Moscow Taiwan)
     (= (flightPrice Moscow Taiwan) 105)
     (flight Moscow Tokio)
     (= (flightPrice Moscow Tokio) 99)
     (flight Moscow Nova_Dheli)
     (= (flightPrice Moscow Nova_Dheli) 102)
     (flight Moscow Paris)
     (= (flightPrice Moscow Paris) 106)
     (flight Moscow London)
     (= (flightPrice Moscow London) 98)
     (flight Moscow Berlin)
     (= (flightPrice Moscow Berlin) 105)
     (flight Moscow Dublin)
     (= (flightPrice Moscow Dublin) 112)
     (flight Moscow Edinburgh)
     (= (flightPrice Moscow Edinburgh) 98)
     (flight Moscow Krakow)
     (= (flightPrice Moscow Krakow) 93)
     (flight Moscow Venice)
     (= (flightPrice Moscow Venice) 86)
     (flight Moscow Saint_Petersburg)
     (= (flightPrice Moscow Saint_Petersburg) 117)
     (flight Moscow Istanbul)
     (= (flightPrice Moscow Istanbul) 108)
     (flight Moscow Rome)
     (= (flightPrice Moscow Rome) 107)
     (flight Moscow Caracas)
     (= (flightPrice Moscow Caracas) 112)
     (flight Moscow Rio_de_Janeiro)
     (= (flightPrice Moscow Rio_de_Janeiro) 116)
     (flight Moscow La_Habana)
     (= (flightPrice Moscow La_Habana) 86)
     (flight Moscow Medellin)
     (= (flightPrice Moscow Medellin) 112)
     (flight Moscow Cali)
     (= (flightPrice Moscow Cali) 119)
     (flight Moscow Washington_DC)
     (= (flightPrice Moscow Washington_DC) 117)
     (flight Moscow New_York)
     (= (flightPrice Moscow New_York) 100)
     (flight Krakow Melbourne)
     (= (flightPrice Krakow Melbourne) 113)
     (flight Krakow Sidney)
     (= (flightPrice Krakow Sidney) 117)
     (flight Krakow Wellington)
     (= (flightPrice Krakow Wellington) 92)
     (flight Krakow Beijing)
     (= (flightPrice Krakow Beijing) 83)
     (flight Krakow Taiwan)
     (= (flightPrice Krakow Taiwan) 115)
     (flight Krakow Tokio)
     (= (flightPrice Krakow Tokio) 111)
     (flight Krakow Nova_Dheli)
     (= (flightPrice Krakow Nova_Dheli) 107)
     (flight Krakow Paris)
     (= (flightPrice Krakow Paris) 98)
     (flight Krakow London)
     (= (flightPrice Krakow London) 89)
     (flight Krakow Berlin)
     (= (flightPrice Krakow Berlin) 114)
     (flight Krakow Dublin)
     (= (flightPrice Krakow Dublin) 101)
     (flight Krakow Edinburgh)
     (= (flightPrice Krakow Edinburgh) 106)
     (flight Krakow Moscow)
     (= (flightPrice Krakow Moscow) 94)
     (flight Krakow Venice)
     (= (flightPrice Krakow Venice) 83)
     (flight Krakow Saint_Petersburg)
     (= (flightPrice Krakow Saint_Petersburg) 85)
     (flight Krakow Istanbul)
     (= (flightPrice Krakow Istanbul) 104)
     (flight Krakow Rome)
     (= (flightPrice Krakow Rome) 108)
     (flight Krakow Caracas)
     (= (flightPrice Krakow Caracas) 117)
     (flight Krakow Rio_de_Janeiro)
     (= (flightPrice Krakow Rio_de_Janeiro) 83)
     (flight Krakow La_Habana)
     (= (flightPrice Krakow La_Habana) 113)
     (flight Krakow Medellin)
     (= (flightPrice Krakow Medellin) 115)
     (flight Krakow Cali)
     (= (flightPrice Krakow Cali) 80)
     (flight Krakow Washington_DC)
     (= (flightPrice Krakow Washington_DC) 101)
     (flight Krakow New_York)
     (= (flightPrice Krakow New_York) 94)
     (flight Venice Melbourne)
     (= (flightPrice Venice Melbourne) 105)
     (flight Venice Sidney)
     (= (flightPrice Venice Sidney) 97)
     (flight Venice Wellington)
     (= (flightPrice Venice Wellington) 100)
     (flight Venice Beijing)
     (= (flightPrice Venice Beijing) 97)
     (flight Venice Taiwan)
     (= (flightPrice Venice Taiwan) 88)
     (flight Venice Tokio)
     (= (flightPrice Venice Tokio) 89)
     (flight Venice Nova_Dheli)
     (= (flightPrice Venice Nova_Dheli) 109)
     (flight Venice Paris)
     (= (flightPrice Venice Paris) 113)
     (flight Venice London)
     (= (flightPrice Venice London) 119)
     (flight Venice Berlin)
     (= (flightPrice Venice Berlin) 114)
     (flight Venice Dublin)
     (= (flightPrice Venice Dublin) 116)
     (flight Venice Edinburgh)
     (= (flightPrice Venice Edinburgh) 114)
     (flight Venice Moscow)
     (= (flightPrice Venice Moscow) 105)
     (flight Venice Krakow)
     (= (flightPrice Venice Krakow) 95)
     (flight Venice Saint_Petersburg)
     (= (flightPrice Venice Saint_Petersburg) 85)
     (flight Venice Istanbul)
     (= (flightPrice Venice Istanbul) 106)
     (flight Venice Rome)
     (= (flightPrice Venice Rome) 90)
     (flight Venice Caracas)
     (= (flightPrice Venice Caracas) 106)
     (flight Venice Rio_de_Janeiro)
     (= (flightPrice Venice Rio_de_Janeiro) 92)
     (flight Venice La_Habana)
     (= (flightPrice Venice La_Habana) 96)
     (flight Venice Medellin)
     (= (flightPrice Venice Medellin) 109)
     (flight Venice Cali)
     (= (flightPrice Venice Cali) 89)
     (flight Venice Washington_DC)
     (= (flightPrice Venice Washington_DC) 112)
     (flight Venice New_York)
     (= (flightPrice Venice New_York) 89)
     (flight Saint_Petersburg Melbourne)
     (= (flightPrice Saint_Petersburg Melbourne) 86)
     (flight Saint_Petersburg Sidney)
     (= (flightPrice Saint_Petersburg Sidney) 115)
     (flight Saint_Petersburg Wellington)
     (= (flightPrice Saint_Petersburg Wellington) 115)
     (flight Saint_Petersburg Beijing)
     (= (flightPrice Saint_Petersburg Beijing) 113)
     (flight Saint_Petersburg Taiwan)
     (= (flightPrice Saint_Petersburg Taiwan) 108)
     (flight Saint_Petersburg Tokio)
     (= (flightPrice Saint_Petersburg Tokio) 96)
     (flight Saint_Petersburg Nova_Dheli)
     (= (flightPrice Saint_Petersburg Nova_Dheli) 87)
     (flight Saint_Petersburg Paris)
     (= (flightPrice Saint_Petersburg Paris) 93)
     (flight Saint_Petersburg London)
     (= (flightPrice Saint_Petersburg London) 106)
     (flight Saint_Petersburg Berlin)
     (= (flightPrice Saint_Petersburg Berlin) 100)
     (flight Saint_Petersburg Dublin)
     (= (flightPrice Saint_Petersburg Dublin) 102)
     (flight Saint_Petersburg Edinburgh)
     (= (flightPrice Saint_Petersburg Edinburgh) 106)
     (flight Saint_Petersburg Moscow)
     (= (flightPrice Saint_Petersburg Moscow) 109)
     (flight Saint_Petersburg Krakow)
     (= (flightPrice Saint_Petersburg Krakow) 83)
     (flight Saint_Petersburg Venice)
     (= (flightPrice Saint_Petersburg Venice) 100)
     (flight Saint_Petersburg Istanbul)
     (= (flightPrice Saint_Petersburg Istanbul) 108)
     (flight Saint_Petersburg Rome)
     (= (flightPrice Saint_Petersburg Rome) 117)
     (flight Saint_Petersburg Caracas)
     (= (flightPrice Saint_Petersburg Caracas) 96)
     (flight Saint_Petersburg Rio_de_Janeiro)
     (= (flightPrice Saint_Petersburg Rio_de_Janeiro) 95)
     (flight Saint_Petersburg La_Habana)
     (= (flightPrice Saint_Petersburg La_Habana) 102)
     (flight Saint_Petersburg Medellin)
     (= (flightPrice Saint_Petersburg Medellin) 104)
     (flight Saint_Petersburg Cali)
     (= (flightPrice Saint_Petersburg Cali) 100)
     (flight Saint_Petersburg Washington_DC)
     (= (flightPrice Saint_Petersburg Washington_DC) 80)
     (flight Saint_Petersburg New_York)
     (= (flightPrice Saint_Petersburg New_York) 106)
     (flight Istanbul Melbourne)
     (= (flightPrice Istanbul Melbourne) 118)
     (flight Istanbul Sidney)
     (= (flightPrice Istanbul Sidney) 85)
     (flight Istanbul Wellington)
     (= (flightPrice Istanbul Wellington) 114)
     (flight Istanbul Beijing)
     (= (flightPrice Istanbul Beijing) 99)
     (flight Istanbul Taiwan)
     (= (flightPrice Istanbul Taiwan) 94)
     (flight Istanbul Tokio)
     (= (flightPrice Istanbul Tokio) 106)
     (flight Istanbul Nova_Dheli)
     (= (flightPrice Istanbul Nova_Dheli) 108)
     (flight Istanbul Paris)
     (= (flightPrice Istanbul Paris) 93)
     (flight Istanbul London)
     (= (flightPrice Istanbul London) 102)
     (flight Istanbul Berlin)
     (= (flightPrice Istanbul Berlin) 103)
     (flight Istanbul Dublin)
     (= (flightPrice Istanbul Dublin) 86)
     (flight Istanbul Edinburgh)
     (= (flightPrice Istanbul Edinburgh) 82)
     (flight Istanbul Moscow)
     (= (flightPrice Istanbul Moscow) 112)
     (flight Istanbul Krakow)
     (= (flightPrice Istanbul Krakow) 94)
     (flight Istanbul Venice)
     (= (flightPrice Istanbul Venice) 87)
     (flight Istanbul Saint_Petersburg)
     (= (flightPrice Istanbul Saint_Petersburg) 90)
     (flight Istanbul Rome)
     (= (flightPrice Istanbul Rome) 114)
     (flight Istanbul Caracas)
     (= (flightPrice Istanbul Caracas) 109)
     (flight Istanbul Rio_de_Janeiro)
     (= (flightPrice Istanbul Rio_de_Janeiro) 116)
     (flight Istanbul La_Habana)
     (= (flightPrice Istanbul La_Habana) 95)
     (flight Istanbul Medellin)
     (= (flightPrice Istanbul Medellin) 104)
     (flight Istanbul Cali)
     (= (flightPrice Istanbul Cali) 96)
     (flight Istanbul Washington_DC)
     (= (flightPrice Istanbul Washington_DC) 84)
     (flight Istanbul New_York)
     (= (flightPrice Istanbul New_York) 102)
     (flight Rome Melbourne)
     (= (flightPrice Rome Melbourne) 105)
     (flight Rome Sidney)
     (= (flightPrice Rome Sidney) 91)
     (flight Rome Wellington)
     (= (flightPrice Rome Wellington) 116)
     (flight Rome Beijing)
     (= (flightPrice Rome Beijing) 81)
     (flight Rome Taiwan)
     (= (flightPrice Rome Taiwan) 103)
     (flight Rome Tokio)
     (= (flightPrice Rome Tokio) 117)
     (flight Rome Nova_Dheli)
     (= (flightPrice Rome Nova_Dheli) 107)
     (flight Rome Paris)
     (= (flightPrice Rome Paris) 101)
     (flight Rome London)
     (= (flightPrice Rome London) 82)
     (flight Rome Berlin)
     (= (flightPrice Rome Berlin) 101)
     (flight Rome Dublin)
     (= (flightPrice Rome Dublin) 80)
     (flight Rome Edinburgh)
     (= (flightPrice Rome Edinburgh) 88)
     (flight Rome Moscow)
     (= (flightPrice Rome Moscow) 119)
     (flight Rome Krakow)
     (= (flightPrice Rome Krakow) 100)
     (flight Rome Venice)
     (= (flightPrice Rome Venice) 101)
     (flight Rome Saint_Petersburg)
     (= (flightPrice Rome Saint_Petersburg) 93)
     (flight Rome Istanbul)
     (= (flightPrice Rome Istanbul) 84)
     (flight Rome Caracas)
     (= (flightPrice Rome Caracas) 108)
     (flight Rome Rio_de_Janeiro)
     (= (flightPrice Rome Rio_de_Janeiro) 95)
     (flight Rome La_Habana)
     (= (flightPrice Rome La_Habana) 108)
     (flight Rome Medellin)
     (= (flightPrice Rome Medellin) 82)
     (flight Rome Cali)
     (= (flightPrice Rome Cali) 102)
     (flight Rome Washington_DC)
     (= (flightPrice Rome Washington_DC) 110)
     (flight Rome New_York)
     (= (flightPrice Rome New_York) 116)
     (flight Caracas Melbourne)
     (= (flightPrice Caracas Melbourne) 83)
     (flight Caracas Sidney)
     (= (flightPrice Caracas Sidney) 106)
     (flight Caracas Wellington)
     (= (flightPrice Caracas Wellington) 91)
     (flight Caracas Beijing)
     (= (flightPrice Caracas Beijing) 100)
     (flight Caracas Taiwan)
     (= (flightPrice Caracas Taiwan) 115)
     (flight Caracas Tokio)
     (= (flightPrice Caracas Tokio) 87)
     (flight Caracas Nova_Dheli)
     (= (flightPrice Caracas Nova_Dheli) 114)
     (flight Caracas Paris)
     (= (flightPrice Caracas Paris) 92)
     (flight Caracas London)
     (= (flightPrice Caracas London) 90)
     (flight Caracas Berlin)
     (= (flightPrice Caracas Berlin) 110)
     (flight Caracas Dublin)
     (= (flightPrice Caracas Dublin) 93)
     (flight Caracas Edinburgh)
     (= (flightPrice Caracas Edinburgh) 113)
     (flight Caracas Moscow)
     (= (flightPrice Caracas Moscow) 99)
     (flight Caracas Krakow)
     (= (flightPrice Caracas Krakow) 80)
     (flight Caracas Venice)
     (= (flightPrice Caracas Venice) 94)
     (flight Caracas Saint_Petersburg)
     (= (flightPrice Caracas Saint_Petersburg) 93)
     (flight Caracas Istanbul)
     (= (flightPrice Caracas Istanbul) 93)
     (flight Caracas Rome)
     (= (flightPrice Caracas Rome) 94)
     (flight Caracas Rio_de_Janeiro)
     (= (flightPrice Caracas Rio_de_Janeiro) 102)
     (flight Caracas La_Habana)
     (= (flightPrice Caracas La_Habana) 84)
     (flight Caracas Medellin)
     (= (flightPrice Caracas Medellin) 115)
     (flight Caracas Cali)
     (= (flightPrice Caracas Cali) 83)
     (flight Caracas Washington_DC)
     (= (flightPrice Caracas Washington_DC) 98)
     (flight Caracas New_York)
     (= (flightPrice Caracas New_York) 111)
     (flight Rio_de_Janeiro Melbourne)
     (= (flightPrice Rio_de_Janeiro Melbourne) 111)
     (flight Rio_de_Janeiro Sidney)
     (= (flightPrice Rio_de_Janeiro Sidney) 113)
     (flight Rio_de_Janeiro Wellington)
     (= (flightPrice Rio_de_Janeiro Wellington) 91)
     (flight Rio_de_Janeiro Beijing)
     (= (flightPrice Rio_de_Janeiro Beijing) 105)
     (flight Rio_de_Janeiro Taiwan)
     (= (flightPrice Rio_de_Janeiro Taiwan) 88)
     (flight Rio_de_Janeiro Tokio)
     (= (flightPrice Rio_de_Janeiro Tokio) 81)
     (flight Rio_de_Janeiro Nova_Dheli)
     (= (flightPrice Rio_de_Janeiro Nova_Dheli) 93)
     (flight Rio_de_Janeiro Paris)
     (= (flightPrice Rio_de_Janeiro Paris) 83)
     (flight Rio_de_Janeiro London)
     (= (flightPrice Rio_de_Janeiro London) 99)
     (flight Rio_de_Janeiro Berlin)
     (= (flightPrice Rio_de_Janeiro Berlin) 97)
     (flight Rio_de_Janeiro Dublin)
     (= (flightPrice Rio_de_Janeiro Dublin) 95)
     (flight Rio_de_Janeiro Edinburgh)
     (= (flightPrice Rio_de_Janeiro Edinburgh) 94)
     (flight Rio_de_Janeiro Moscow)
     (= (flightPrice Rio_de_Janeiro Moscow) 104)
     (flight Rio_de_Janeiro Krakow)
     (= (flightPrice Rio_de_Janeiro Krakow) 89)
     (flight Rio_de_Janeiro Venice)
     (= (flightPrice Rio_de_Janeiro Venice) 106)
     (flight Rio_de_Janeiro Saint_Petersburg)
     (= (flightPrice Rio_de_Janeiro Saint_Petersburg) 107)
     (flight Rio_de_Janeiro Istanbul)
     (= (flightPrice Rio_de_Janeiro Istanbul) 112)
     (flight Rio_de_Janeiro Rome)
     (= (flightPrice Rio_de_Janeiro Rome) 111)
     (flight Rio_de_Janeiro Caracas)
     (= (flightPrice Rio_de_Janeiro Caracas) 100)
     (flight Rio_de_Janeiro La_Habana)
     (= (flightPrice Rio_de_Janeiro La_Habana) 91)
     (flight Rio_de_Janeiro Medellin)
     (= (flightPrice Rio_de_Janeiro Medellin) 103)
     (flight Rio_de_Janeiro Cali)
     (= (flightPrice Rio_de_Janeiro Cali) 107)
     (flight Rio_de_Janeiro Washington_DC)
     (= (flightPrice Rio_de_Janeiro Washington_DC) 97)
     (flight Rio_de_Janeiro New_York)
     (= (flightPrice Rio_de_Janeiro New_York) 116)
     (flight La_Habana Melbourne)
     (= (flightPrice La_Habana Melbourne) 113)
     (flight La_Habana Sidney)
     (= (flightPrice La_Habana Sidney) 119)
     (flight La_Habana Wellington)
     (= (flightPrice La_Habana Wellington) 81)
     (flight La_Habana Beijing)
     (= (flightPrice La_Habana Beijing) 100)
     (flight La_Habana Taiwan)
     (= (flightPrice La_Habana Taiwan) 114)
     (flight La_Habana Tokio)
     (= (flightPrice La_Habana Tokio) 91)
     (flight La_Habana Nova_Dheli)
     (= (flightPrice La_Habana Nova_Dheli) 91)
     (flight La_Habana Paris)
     (= (flightPrice La_Habana Paris) 98)
     (flight La_Habana London)
     (= (flightPrice La_Habana London) 116)
     (flight La_Habana Berlin)
     (= (flightPrice La_Habana Berlin) 94)
     (flight La_Habana Dublin)
     (= (flightPrice La_Habana Dublin) 83)
     (flight La_Habana Edinburgh)
     (= (flightPrice La_Habana Edinburgh) 84)
     (flight La_Habana Moscow)
     (= (flightPrice La_Habana Moscow) 87)
     (flight La_Habana Krakow)
     (= (flightPrice La_Habana Krakow) 97)
     (flight La_Habana Venice)
     (= (flightPrice La_Habana Venice) 80)
     (flight La_Habana Saint_Petersburg)
     (= (flightPrice La_Habana Saint_Petersburg) 107)
     (flight La_Habana Istanbul)
     (= (flightPrice La_Habana Istanbul) 114)
     (flight La_Habana Rome)
     (= (flightPrice La_Habana Rome) 95)
     (flight La_Habana Caracas)
     (= (flightPrice La_Habana Caracas) 113)
     (flight La_Habana Rio_de_Janeiro)
     (= (flightPrice La_Habana Rio_de_Janeiro) 90)
     (flight La_Habana Medellin)
     (= (flightPrice La_Habana Medellin) 97)
     (flight La_Habana Cali)
     (= (flightPrice La_Habana Cali) 92)
     (flight La_Habana Washington_DC)
     (= (flightPrice La_Habana Washington_DC) 109)
     (flight La_Habana New_York)
     (= (flightPrice La_Habana New_York) 89)
     (flight Medellin Melbourne)
     (= (flightPrice Medellin Melbourne) 83)
     (flight Medellin Sidney)
     (= (flightPrice Medellin Sidney) 90)
     (flight Medellin Wellington)
     (= (flightPrice Medellin Wellington) 92)
     (flight Medellin Beijing)
     (= (flightPrice Medellin Beijing) 107)
     (flight Medellin Taiwan)
     (= (flightPrice Medellin Taiwan) 109)
     (flight Medellin Tokio)
     (= (flightPrice Medellin Tokio) 109)
     (flight Medellin Nova_Dheli)
     (= (flightPrice Medellin Nova_Dheli) 95)
     (flight Medellin Paris)
     (= (flightPrice Medellin Paris) 102)
     (flight Medellin London)
     (= (flightPrice Medellin London) 100)
     (flight Medellin Berlin)
     (= (flightPrice Medellin Berlin) 88)
     (flight Medellin Dublin)
     (= (flightPrice Medellin Dublin) 83)
     (flight Medellin Edinburgh)
     (= (flightPrice Medellin Edinburgh) 95)
     (flight Medellin Moscow)
     (= (flightPrice Medellin Moscow) 99)
     (flight Medellin Krakow)
     (= (flightPrice Medellin Krakow) 86)
     (flight Medellin Venice)
     (= (flightPrice Medellin Venice) 105)
     (flight Medellin Saint_Petersburg)
     (= (flightPrice Medellin Saint_Petersburg) 96)
     (flight Medellin Istanbul)
     (= (flightPrice Medellin Istanbul) 93)
     (flight Medellin Rome)
     (= (flightPrice Medellin Rome) 100)
     (flight Medellin Caracas)
     (= (flightPrice Medellin Caracas) 92)
     (flight Medellin Rio_de_Janeiro)
     (= (flightPrice Medellin Rio_de_Janeiro) 100)
     (flight Medellin La_Habana)
     (= (flightPrice Medellin La_Habana) 117)
     (flight Medellin Cali)
     (= (flightPrice Medellin Cali) 84)
     (flight Medellin Washington_DC)
     (= (flightPrice Medellin Washington_DC) 87)
     (flight Medellin New_York)
     (= (flightPrice Medellin New_York) 103)
     (flight Cali Melbourne)
     (= (flightPrice Cali Melbourne) 100)
     (flight Cali Sidney)
     (= (flightPrice Cali Sidney) 81)
     (flight Cali Wellington)
     (= (flightPrice Cali Wellington) 106)
     (flight Cali Beijing)
     (= (flightPrice Cali Beijing) 117)
     (flight Cali Taiwan)
     (= (flightPrice Cali Taiwan) 85)
     (flight Cali Tokio)
     (= (flightPrice Cali Tokio) 87)
     (flight Cali Nova_Dheli)
     (= (flightPrice Cali Nova_Dheli) 118)
     (flight Cali Paris)
     (= (flightPrice Cali Paris) 88)
     (flight Cali London)
     (= (flightPrice Cali London) 89)
     (flight Cali Berlin)
     (= (flightPrice Cali Berlin) 90)
     (flight Cali Dublin)
     (= (flightPrice Cali Dublin) 107)
     (flight Cali Edinburgh)
     (= (flightPrice Cali Edinburgh) 118)
     (flight Cali Moscow)
     (= (flightPrice Cali Moscow) 80)
     (flight Cali Krakow)
     (= (flightPrice Cali Krakow) 83)
     (flight Cali Venice)
     (= (flightPrice Cali Venice) 101)
     (flight Cali Saint_Petersburg)
     (= (flightPrice Cali Saint_Petersburg) 100)
     (flight Cali Istanbul)
     (= (flightPrice Cali Istanbul) 83)
     (flight Cali Rome)
     (= (flightPrice Cali Rome) 96)
     (flight Cali Caracas)
     (= (flightPrice Cali Caracas) 107)
     (flight Cali Rio_de_Janeiro)
     (= (flightPrice Cali Rio_de_Janeiro) 103)
     (flight Cali La_Habana)
     (= (flightPrice Cali La_Habana) 102)
     (flight Cali Medellin)
     (= (flightPrice Cali Medellin) 92)
     (flight Cali Washington_DC)
     (= (flightPrice Cali Washington_DC) 111)
     (flight Cali New_York)
     (= (flightPrice Cali New_York) 115)
     (flight Washington_DC Melbourne)
     (= (flightPrice Washington_DC Melbourne) 113)
     (flight Washington_DC Sidney)
     (= (flightPrice Washington_DC Sidney) 83)
     (flight Washington_DC Wellington)
     (= (flightPrice Washington_DC Wellington) 88)
     (flight Washington_DC Beijing)
     (= (flightPrice Washington_DC Beijing) 102)
     (flight Washington_DC Taiwan)
     (= (flightPrice Washington_DC Taiwan) 88)
     (flight Washington_DC Tokio)
     (= (flightPrice Washington_DC Tokio) 95)
     (flight Washington_DC Nova_Dheli)
     (= (flightPrice Washington_DC Nova_Dheli) 118)
     (flight Washington_DC Paris)
     (= (flightPrice Washington_DC Paris) 100)
     (flight Washington_DC London)
     (= (flightPrice Washington_DC London) 88)
     (flight Washington_DC Berlin)
     (= (flightPrice Washington_DC Berlin) 96)
     (flight Washington_DC Dublin)
     (= (flightPrice Washington_DC Dublin) 89)
     (flight Washington_DC Edinburgh)
     (= (flightPrice Washington_DC Edinburgh) 93)
     (flight Washington_DC Moscow)
     (= (flightPrice Washington_DC Moscow) 103)
     (flight Washington_DC Krakow)
     (= (flightPrice Washington_DC Krakow) 87)
     (flight Washington_DC Venice)
     (= (flightPrice Washington_DC Venice) 94)
     (flight Washington_DC Saint_Petersburg)
     (= (flightPrice Washington_DC Saint_Petersburg) 113)
     (flight Washington_DC Istanbul)
     (= (flightPrice Washington_DC Istanbul) 97)
     (flight Washington_DC Rome)
     (= (flightPrice Washington_DC Rome) 81)
     (flight Washington_DC Caracas)
     (= (flightPrice Washington_DC Caracas) 103)
     (flight Washington_DC Rio_de_Janeiro)
     (= (flightPrice Washington_DC Rio_de_Janeiro) 89)
     (flight Washington_DC La_Habana)
     (= (flightPrice Washington_DC La_Habana) 116)
     (flight Washington_DC Medellin)
     (= (flightPrice Washington_DC Medellin) 84)
     (flight Washington_DC Cali)
     (= (flightPrice Washington_DC Cali) 102)
     (flight Washington_DC New_York)
     (= (flightPrice Washington_DC New_York) 80)
     (flight New_York Melbourne)
     (= (flightPrice New_York Melbourne) 92)
     (flight New_York Sidney)
     (= (flightPrice New_York Sidney) 89)
     (flight New_York Wellington)
     (= (flightPrice New_York Wellington) 95)
     (flight New_York Beijing)
     (= (flightPrice New_York Beijing) 107)
     (flight New_York Taiwan)
     (= (flightPrice New_York Taiwan) 94)
     (flight New_York Tokio)
     (= (flightPrice New_York Tokio) 86)
     (flight New_York Nova_Dheli)
     (= (flightPrice New_York Nova_Dheli) 94)
     (flight New_York Paris)
     (= (flightPrice New_York Paris) 119)
     (flight New_York London)
     (= (flightPrice New_York London) 81)
     (flight New_York Berlin)
     (= (flightPrice New_York Berlin) 102)
     (flight New_York Dublin)
     (= (flightPrice New_York Dublin) 93)
     (flight New_York Edinburgh)
     (= (flightPrice New_York Edinburgh) 81)
     (flight New_York Moscow)
     (= (flightPrice New_York Moscow) 118)
     (flight New_York Krakow)
     (= (flightPrice New_York Krakow) 91)
     (flight New_York Venice)
     (= (flightPrice New_York Venice) 93)
     (flight New_York Saint_Petersburg)
     (= (flightPrice New_York Saint_Petersburg) 118)
     (flight New_York Istanbul)
     (= (flightPrice New_York Istanbul) 99)
     (flight New_York Rome)
     (= (flightPrice New_York Rome) 102)
     (flight New_York Caracas)
     (= (flightPrice New_York Caracas) 84)
     (flight New_York Rio_de_Janeiro)
     (= (flightPrice New_York Rio_de_Janeiro) 115)
     (flight New_York La_Habana)
     (= (flightPrice New_York La_Habana) 101)
     (flight New_York Medellin)
     (= (flightPrice New_York Medellin) 90)
     (flight New_York Cali)
     (= (flightPrice New_York Cali) 100)
     (flight New_York Washington_DC)
     (= (flightPrice New_York Washington_DC) 111)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Melbourne)
     (inCity Hotel_Emperor_2 Melbourne)
     (inCity Residence_Sky_3 Melbourne)
     (inCity Hostel_Delphin_4 Melbourne)
     (inCity Residence_Single_Land_5 Melbourne)
     (inCity Resort_Lollipop_6 Melbourne)
     (inCity Hostel_Emperor_7 Melbourne)
     (inCity Hostel_Lollipop_8 Melbourne)
     (inCity Hostel_Single_Land_9 Melbourne)
     (inCity Apartments_Paradise_10 Melbourne)
     (inCity Resort_Arabiga_11 Melbourne)
     (inCity Hotel_Single_Land_12 Melbourne)
     (inCity Apartments_Single_Land_13 Melbourne)
     (inCity Hotel_Arabiga_14 Melbourne)
     (inCity Residence_Delphin_15 Sidney)
     (inCity Apartments_Single_Land_16 Sidney)
     (inCity Residence_Delphin_17 Sidney)
     (inCity Hostel_Emperor_18 Sidney)
     (inCity Residence_Paradise_19 Sidney)
     (inCity Apartments_Delphin_20 Sidney)
     (inCity Resort_Paradise_21 Sidney)
     (inCity Residence_Relax_22 Sidney)
     (inCity Resort_NH_23 Sidney)
     (inCity Hotel_Chill_24 Sidney)
     (inCity Hostel_Emperor_25 Sidney)
     (inCity Hotel_Paradise_26 Sidney)
     (inCity Apartments_Sky_27 Sidney)
     (inCity Hotel_Single_Land_28 Sidney)
     (inCity Hostel_Sky_29 Sidney)
     (inCity Hotel_Chill_30 Wellington)
     (inCity Residence_Relax_31 Wellington)
     (inCity Hotel_Sky_32 Wellington)
     (inCity Resort_Sky_33 Wellington)
     (inCity Residence_Emperor_34 Wellington)
     (inCity Hotel_Relax_35 Wellington)
     (inCity Hotel_Single_Land_36 Wellington)
     (inCity Residence_Relax_37 Wellington)
     (inCity Resort_Relax_38 Wellington)
     (inCity Hotel_Emperor_39 Wellington)
     (inCity Apartments_Arabiga_40 Wellington)
     (inCity Apartments_Sky_41 Wellington)
     (inCity Resort_NH_42 Wellington)
     (inCity Hostel_Emperor_43 Wellington)
     (inCity Resort_Relax_44 Wellington)
     (inCity Hotel_Single_Land_45 Beijing)
     (inCity Apartments_Sky_46 Beijing)
     (inCity Residence_Delphin_47 Beijing)
     (inCity Hostel_Sky_48 Beijing)
     (inCity Resort_Relax_49 Beijing)
     (inCity Hotel_Chill_50 Beijing)
     (inCity Apartments_Relax_51 Beijing)
     (inCity Hostel_Arabiga_52 Beijing)
     (inCity Residence_Arabiga_53 Beijing)
     (inCity Residence_Arabiga_54 Beijing)
     (inCity Hostel_Single_Land_55 Beijing)
     (inCity Hotel_Paradise_56 Beijing)
     (inCity Hostel_Sky_57 Beijing)
     (inCity Resort_Chill_58 Beijing)
     (inCity Resort_Relax_59 Beijing)
     (inCity Resort_Lollipop_60 Taiwan)
     (inCity Residence_Paradise_61 Taiwan)
     (inCity Hostel_Arabiga_62 Taiwan)
     (inCity Hotel_Paradise_63 Taiwan)
     (inCity Residence_Delphin_64 Taiwan)
     (inCity Hostel_Arabiga_65 Taiwan)
     (inCity Apartments_Arabiga_66 Taiwan)
     (inCity Hotel_Sky_67 Taiwan)
     (inCity Apartments_Sky_68 Taiwan)
     (inCity Resort_Delphin_69 Taiwan)
     (inCity Hostel_NH_70 Taiwan)
     (inCity Resort_Single_Land_71 Taiwan)
     (inCity Resort_Emperor_72 Taiwan)
     (inCity Apartments_Lollipop_73 Taiwan)
     (inCity Hotel_NH_74 Taiwan)
     (inCity Resort_Lollipop_75 Tokio)
     (inCity Apartments_Sky_76 Tokio)
     (inCity Hotel_NH_77 Tokio)
     (inCity Hostel_Sky_78 Tokio)
     (inCity Hotel_Paradise_79 Tokio)
     (inCity Apartments_Delphin_80 Tokio)
     (inCity Apartments_Relax_81 Tokio)
     (inCity Hotel_Paradise_82 Tokio)
     (inCity Hotel_Emperor_83 Tokio)
     (inCity Resort_Relax_84 Tokio)
     (inCity Resort_Relax_85 Tokio)
     (inCity Hostel_Arabiga_86 Tokio)
     (inCity Hostel_Emperor_87 Tokio)
     (inCity Hotel_Arabiga_88 Tokio)
     (inCity Hostel_Delphin_89 Tokio)
     (inCity Hostel_Single_Land_90 Nova_Dheli)
     (inCity Apartments_Arabiga_91 Nova_Dheli)
     (inCity Residence_Chill_92 Nova_Dheli)
     (inCity Hostel_Relax_93 Nova_Dheli)
     (inCity Hotel_NH_94 Nova_Dheli)
     (inCity Residence_Delphin_95 Nova_Dheli)
     (inCity Apartments_Chill_96 Nova_Dheli)
     (inCity Apartments_NH_97 Nova_Dheli)
     (inCity Hostel_Emperor_98 Nova_Dheli)
     (inCity Resort_NH_99 Nova_Dheli)
     (inCity Resort_Sky_100 Nova_Dheli)
     (inCity Apartments_Emperor_101 Nova_Dheli)
     (inCity Apartments_Emperor_102 Nova_Dheli)
     (inCity Hotel_Sky_103 Nova_Dheli)
     (inCity Apartments_Relax_104 Nova_Dheli)
     (inCity Apartments_NH_105 Paris)
     (inCity Residence_Delphin_106 Paris)
     (inCity Hostel_Arabiga_107 Paris)
     (inCity Apartments_Relax_108 Paris)
     (inCity Apartments_Lollipop_109 Paris)
     (inCity Resort_Lollipop_110 Paris)
     (inCity Hotel_Single_Land_111 Paris)
     (inCity Hotel_Relax_112 Paris)
     (inCity Resort_Chill_113 Paris)
     (inCity Hostel_Relax_114 Paris)
     (inCity Residence_Delphin_115 Paris)
     (inCity Resort_Single_Land_116 Paris)
     (inCity Residence_Arabiga_117 Paris)
     (inCity Resort_Chill_118 Paris)
     (inCity Hostel_NH_119 Paris)
     (inCity Apartments_Single_Land_120 London)
     (inCity Apartments_Delphin_121 London)
     (inCity Apartments_Sky_122 London)
     (inCity Residence_Lollipop_123 London)
     (inCity Hotel_Paradise_124 London)
     (inCity Hostel_Chill_125 London)
     (inCity Hotel_Paradise_126 London)
     (inCity Hotel_NH_127 London)
     (inCity Hostel_Lollipop_128 London)
     (inCity Hostel_Relax_129 London)
     (inCity Hotel_Single_Land_130 London)
     (inCity Hostel_NH_131 London)
     (inCity Apartments_Single_Land_132 London)
     (inCity Residence_Relax_133 London)
     (inCity Resort_Single_Land_134 London)
     (inCity Hostel_Lollipop_135 Berlin)
     (inCity Resort_Single_Land_136 Berlin)
     (inCity Hotel_Delphin_137 Berlin)
     (inCity Hostel_NH_138 Berlin)
     (inCity Hostel_Emperor_139 Berlin)
     (inCity Hotel_Paradise_140 Berlin)
     (inCity Resort_Emperor_141 Berlin)
     (inCity Apartments_Lollipop_142 Berlin)
     (inCity Hostel_Delphin_143 Berlin)
     (inCity Hostel_Delphin_144 Berlin)
     (inCity Apartments_Delphin_145 Berlin)
     (inCity Apartments_Emperor_146 Berlin)
     (inCity Hotel_Lollipop_147 Berlin)
     (inCity Hostel_Sky_148 Berlin)
     (inCity Hotel_Relax_149 Berlin)
     (inCity Resort_Lollipop_150 Dublin)
     (inCity Residence_Sky_151 Dublin)
     (inCity Residence_Sky_152 Dublin)
     (inCity Hostel_Chill_153 Dublin)
     (inCity Apartments_Delphin_154 Dublin)
     (inCity Residence_Arabiga_155 Dublin)
     (inCity Residence_NH_156 Dublin)
     (inCity Resort_Delphin_157 Dublin)
     (inCity Hotel_Sky_158 Dublin)
     (inCity Residence_Single_Land_159 Dublin)
     (inCity Hostel_Sky_160 Dublin)
     (inCity Residence_Emperor_161 Dublin)
     (inCity Hotel_Paradise_162 Dublin)
     (inCity Resort_Delphin_163 Dublin)
     (inCity Resort_Paradise_164 Dublin)
     (inCity Hostel_Delphin_165 Edinburgh)
     (inCity Residence_Lollipop_166 Edinburgh)
     (inCity Apartments_Chill_167 Edinburgh)
     (inCity Hotel_Arabiga_168 Edinburgh)
     (inCity Apartments_Relax_169 Edinburgh)
     (inCity Resort_Lollipop_170 Edinburgh)
     (inCity Resort_Single_Land_171 Edinburgh)
     (inCity Hostel_Sky_172 Edinburgh)
     (inCity Resort_Lollipop_173 Edinburgh)
     (inCity Residence_Single_Land_174 Edinburgh)
     (inCity Hotel_Single_Land_175 Edinburgh)
     (inCity Hotel_Chill_176 Edinburgh)
     (inCity Resort_Single_Land_177 Edinburgh)
     (inCity Residence_Lollipop_178 Edinburgh)
     (inCity Apartments_NH_179 Edinburgh)
     (inCity Hotel_NH_180 Moscow)
     (inCity Hotel_Relax_181 Moscow)
     (inCity Hostel_Delphin_182 Moscow)
     (inCity Hostel_Delphin_183 Moscow)
     (inCity Hotel_Single_Land_184 Moscow)
     (inCity Resort_Relax_185 Moscow)
     (inCity Resort_Delphin_186 Moscow)
     (inCity Hostel_Emperor_187 Moscow)
     (inCity Hotel_Lollipop_188 Moscow)
     (inCity Residence_Lollipop_189 Moscow)
     (inCity Resort_Delphin_190 Moscow)
     (inCity Hotel_Emperor_191 Moscow)
     (inCity Residence_Paradise_192 Moscow)
     (inCity Apartments_Relax_193 Moscow)
     (inCity Resort_Paradise_194 Moscow)
     (inCity Resort_Sky_195 Krakow)
     (inCity Residence_Relax_196 Krakow)
     (inCity Hostel_Single_Land_197 Krakow)
     (inCity Hostel_Relax_198 Krakow)
     (inCity Apartments_Single_Land_199 Krakow)
     (inCity Resort_NH_200 Krakow)
     (inCity Apartments_Single_Land_201 Krakow)
     (inCity Apartments_NH_202 Krakow)
     (inCity Apartments_Sky_203 Krakow)
     (inCity Apartments_Emperor_204 Krakow)
     (inCity Apartments_Emperor_205 Krakow)
     (inCity Apartments_Emperor_206 Krakow)
     (inCity Resort_Lollipop_207 Krakow)
     (inCity Hostel_Arabiga_208 Krakow)
     (inCity Resort_NH_209 Krakow)
     (inCity Hostel_Lollipop_210 Venice)
     (inCity Residence_NH_211 Venice)
     (inCity Hotel_Delphin_212 Venice)
     (inCity Apartments_Emperor_213 Venice)
     (inCity Residence_Emperor_214 Venice)
     (inCity Residence_Emperor_215 Venice)
     (inCity Hotel_Sky_216 Venice)
     (inCity Hostel_Single_Land_217 Venice)
     (inCity Apartments_Chill_218 Venice)
     (inCity Resort_Arabiga_219 Venice)
     (inCity Hotel_Sky_220 Venice)
     (inCity Hostel_Relax_221 Venice)
     (inCity Resort_Lollipop_222 Venice)
     (inCity Residence_NH_223 Venice)
     (inCity Apartments_Lollipop_224 Venice)
     (inCity Residence_Sky_225 Saint_Petersburg)
     (inCity Residence_Relax_226 Saint_Petersburg)
     (inCity Apartments_Delphin_227 Saint_Petersburg)
     (inCity Residence_Delphin_228 Saint_Petersburg)
     (inCity Apartments_NH_229 Saint_Petersburg)
     (inCity Hostel_Lollipop_230 Saint_Petersburg)
     (inCity Apartments_Arabiga_231 Saint_Petersburg)
     (inCity Hostel_Delphin_232 Saint_Petersburg)
     (inCity Resort_Chill_233 Saint_Petersburg)
     (inCity Residence_Delphin_234 Saint_Petersburg)
     (inCity Residence_Chill_235 Saint_Petersburg)
     (inCity Resort_Relax_236 Saint_Petersburg)
     (inCity Resort_Delphin_237 Saint_Petersburg)
     (inCity Resort_Chill_238 Saint_Petersburg)
     (inCity Hotel_Emperor_239 Saint_Petersburg)
     (inCity Hotel_Arabiga_240 Istanbul)
     (inCity Hostel_NH_241 Istanbul)
     (inCity Resort_Delphin_242 Istanbul)
     (inCity Apartments_Arabiga_243 Istanbul)
     (inCity Hotel_Single_Land_244 Istanbul)
     (inCity Resort_Emperor_245 Istanbul)
     (inCity Hotel_Delphin_246 Istanbul)
     (inCity Hotel_Single_Land_247 Istanbul)
     (inCity Resort_Paradise_248 Istanbul)
     (inCity Residence_Sky_249 Istanbul)
     (inCity Residence_Paradise_250 Istanbul)
     (inCity Residence_Lollipop_251 Istanbul)
     (inCity Hostel_Emperor_252 Istanbul)
     (inCity Resort_Paradise_253 Istanbul)
     (inCity Hotel_Lollipop_254 Istanbul)
     (inCity Residence_Sky_255 Rome)
     (inCity Resort_Arabiga_256 Rome)
     (inCity Hostel_Lollipop_257 Rome)
     (inCity Residence_Relax_258 Rome)
     (inCity Apartments_Relax_259 Rome)
     (inCity Apartments_Chill_260 Rome)
     (inCity Hostel_Single_Land_261 Rome)
     (inCity Hostel_Lollipop_262 Rome)
     (inCity Resort_Sky_263 Rome)
     (inCity Residence_Sky_264 Rome)
     (inCity Resort_NH_265 Rome)
     (inCity Hotel_Sky_266 Rome)
     (inCity Hotel_Arabiga_267 Rome)
     (inCity Hotel_Paradise_268 Rome)
     (inCity Apartments_Paradise_269 Rome)
     (inCity Residence_Arabiga_270 Caracas)
     (inCity Hostel_Single_Land_271 Caracas)
     (inCity Hotel_Relax_272 Caracas)
     (inCity Hotel_Single_Land_273 Caracas)
     (inCity Resort_Single_Land_274 Caracas)
     (inCity Resort_Lollipop_275 Caracas)
     (inCity Resort_Delphin_276 Caracas)
     (inCity Hostel_Chill_277 Caracas)
     (inCity Apartments_Lollipop_278 Caracas)
     (inCity Apartments_Arabiga_279 Caracas)
     (inCity Hostel_NH_280 Caracas)
     (inCity Resort_Lollipop_281 Caracas)
     (inCity Residence_Sky_282 Caracas)
     (inCity Hotel_Sky_283 Caracas)
     (inCity Residence_Delphin_284 Caracas)
     (inCity Resort_Chill_285 Rio_de_Janeiro)
     (inCity Apartments_Arabiga_286 Rio_de_Janeiro)
     (inCity Apartments_Chill_287 Rio_de_Janeiro)
     (inCity Apartments_Emperor_288 Rio_de_Janeiro)
     (inCity Residence_Emperor_289 Rio_de_Janeiro)
     (inCity Apartments_Delphin_290 Rio_de_Janeiro)
     (inCity Apartments_Arabiga_291 Rio_de_Janeiro)
     (inCity Resort_Arabiga_292 Rio_de_Janeiro)
     (inCity Resort_Paradise_293 Rio_de_Janeiro)
     (inCity Resort_Lollipop_294 Rio_de_Janeiro)
     (inCity Apartments_NH_295 Rio_de_Janeiro)
     (inCity Apartments_Chill_296 Rio_de_Janeiro)
     (inCity Apartments_Relax_297 Rio_de_Janeiro)
     (inCity Hostel_Arabiga_298 Rio_de_Janeiro)
     (inCity Apartments_Emperor_299 Rio_de_Janeiro)
     (inCity Resort_Lollipop_300 La_Habana)
     (inCity Resort_Arabiga_301 La_Habana)
     (inCity Apartments_Delphin_302 La_Habana)
     (inCity Resort_Single_Land_303 La_Habana)
     (inCity Residence_Emperor_304 La_Habana)
     (inCity Residence_Paradise_305 La_Habana)
     (inCity Hotel_Single_Land_306 La_Habana)
     (inCity Hostel_Single_Land_307 La_Habana)
     (inCity Hotel_Arabiga_308 La_Habana)
     (inCity Residence_Paradise_309 La_Habana)
     (inCity Hostel_Relax_310 La_Habana)
     (inCity Hostel_Arabiga_311 La_Habana)
     (inCity Hostel_Paradise_312 La_Habana)
     (inCity Hotel_Arabiga_313 La_Habana)
     (inCity Hotel_Relax_314 La_Habana)
     (inCity Hotel_NH_315 Medellin)
     (inCity Hostel_Paradise_316 Medellin)
     (inCity Residence_Sky_317 Medellin)
     (inCity Resort_Paradise_318 Medellin)
     (inCity Resort_Sky_319 Medellin)
     (inCity Hotel_NH_320 Medellin)
     (inCity Hostel_NH_321 Medellin)
     (inCity Residence_Lollipop_322 Medellin)
     (inCity Resort_Single_Land_323 Medellin)
     (inCity Hotel_Arabiga_324 Medellin)
     (inCity Resort_Sky_325 Medellin)
     (inCity Apartments_Sky_326 Medellin)
     (inCity Resort_Arabiga_327 Medellin)
     (inCity Resort_Arabiga_328 Medellin)
     (inCity Hostel_Delphin_329 Medellin)
     (inCity Hotel_Arabiga_330 Cali)
     (inCity Hotel_Sky_331 Cali)
     (inCity Hotel_NH_332 Cali)
     (inCity Resort_Emperor_333 Cali)
     (inCity Hostel_Relax_334 Cali)
     (inCity Resort_Chill_335 Cali)
     (inCity Hotel_Paradise_336 Cali)
     (inCity Resort_Chill_337 Cali)
     (inCity Apartments_Delphin_338 Cali)
     (inCity Apartments_Emperor_339 Cali)
     (inCity Residence_Chill_340 Cali)
     (inCity Residence_Single_Land_341 Cali)
     (inCity Hotel_Arabiga_342 Cali)
     (inCity Resort_Emperor_343 Cali)
     (inCity Apartments_Sky_344 Cali)
     (inCity Apartments_Sky_345 Washington_DC)
     (inCity Resort_Emperor_346 Washington_DC)
     (inCity Apartments_Relax_347 Washington_DC)
     (inCity Residence_Delphin_348 Washington_DC)
     (inCity Hotel_Single_Land_349 Washington_DC)
     (inCity Resort_NH_350 Washington_DC)
     (inCity Residence_Lollipop_351 Washington_DC)
     (inCity Residence_Relax_352 Washington_DC)
     (inCity Hotel_Sky_353 Washington_DC)
     (inCity Hostel_Arabiga_354 Washington_DC)
     (inCity Apartments_Emperor_355 Washington_DC)
     (inCity Apartments_Emperor_356 Washington_DC)
     (inCity Hostel_Chill_357 Washington_DC)
     (inCity Apartments_Lollipop_358 Washington_DC)
     (inCity Hostel_Arabiga_359 Washington_DC)
     (inCity Hotel_Emperor_360 New_York)
     (inCity Apartments_Lollipop_361 New_York)
     (inCity Resort_Lollipop_362 New_York)
     (inCity Hostel_Paradise_363 New_York)
     (inCity Hotel_Emperor_364 New_York)
     (inCity Apartments_Delphin_365 New_York)
     (inCity Hostel_Relax_366 New_York)
     (inCity Hotel_Chill_367 New_York)
     (inCity Apartments_NH_368 New_York)
     (inCity Hostel_Chill_369 New_York)
     (inCity Resort_Chill_370 New_York)
     (inCity Hotel_Delphin_371 New_York)
     (inCity Hostel_Arabiga_372 New_York)
     (inCity Residence_Emperor_373 New_York)
     (inCity Hostel_Sky_374 New_York)
)

(:goal 
(and (= (visited-cities) 7)
     (> (total-days) 11)
     (> (total-price) (minPriceTrip))
     (< (total-price) (maxPriceTrip))
)
)

(:metric
     minimize (total-interest) 
     minimize (total-price))

)
