;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem20)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin Dublin Edinburgh Moscow Krakow Venice Saint_Petersburg Istanbul Rome Caracas Rio_de_Janeiro La_Habana Medellin Cali Washington_DC New_York - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 Apartments_Paradise_10 Resort_Arabiga_11 Hotel_Single_Land_12 Apartments_Single_Land_13 Hotel_Arabiga_14 Residence_Delphin_15 Apartments_Single_Land_16 Residence_Delphin_17 Hostel_Emperor_18 Residence_Paradise_19 Apartments_Delphin_20 Resort_Paradise_21 Residence_Relax_22 Resort_NH_23 Hotel_Chill_24 Hostel_Emperor_25 Hotel_Paradise_26 Apartments_Sky_27 Hotel_Single_Land_28 Hostel_Sky_29 Hotel_Chill_30 Residence_Relax_31 Hotel_Sky_32 Resort_Sky_33 Residence_Emperor_34 Hotel_Relax_35 Hotel_Single_Land_36 Residence_Relax_37 Resort_Relax_38 Hotel_Emperor_39 Apartments_Arabiga_40 Apartments_Sky_41 Resort_NH_42 Hostel_Emperor_43 Resort_Relax_44 Hotel_Single_Land_45 Apartments_Sky_46 Residence_Delphin_47 Hostel_Sky_48 Resort_Relax_49 Hotel_Chill_50 Apartments_Relax_51 Hostel_Arabiga_52 Residence_Arabiga_53 Residence_Arabiga_54 Hostel_Single_Land_55 Hotel_Paradise_56 Hostel_Sky_57 Resort_Chill_58 Resort_Relax_59 Resort_Lollipop_60 Residence_Paradise_61 Hostel_Arabiga_62 Hotel_Paradise_63 Residence_Delphin_64 Hostel_Arabiga_65 Apartments_Arabiga_66 Hotel_Sky_67 Apartments_Sky_68 Resort_Delphin_69 Hostel_NH_70 Resort_Single_Land_71 Resort_Emperor_72 Apartments_Lollipop_73 Hotel_NH_74 Resort_Lollipop_75 Apartments_Sky_76 Hotel_NH_77 Hostel_Sky_78 Hotel_Paradise_79 Apartments_Delphin_80 Apartments_Relax_81 Hotel_Paradise_82 Hotel_Emperor_83 Resort_Relax_84 Resort_Relax_85 Hostel_Arabiga_86 Hostel_Emperor_87 Hotel_Arabiga_88 Hostel_Delphin_89 Hostel_Single_Land_90 Apartments_Arabiga_91 Residence_Chill_92 Hostel_Relax_93 Hotel_NH_94 Residence_Delphin_95 Apartments_Chill_96 Apartments_NH_97 Hostel_Emperor_98 Resort_NH_99 Resort_Sky_100 Apartments_Emperor_101 Apartments_Emperor_102 Hotel_Sky_103 Apartments_Relax_104 Apartments_NH_105 Residence_Delphin_106 Hostel_Arabiga_107 Apartments_Relax_108 Apartments_Lollipop_109 Resort_Lollipop_110 Hotel_Single_Land_111 Hotel_Relax_112 Resort_Chill_113 Hostel_Relax_114 Residence_Delphin_115 Resort_Single_Land_116 Residence_Arabiga_117 Resort_Chill_118 Hostel_NH_119 Apartments_Single_Land_120 Apartments_Delphin_121 Apartments_Sky_122 Residence_Lollipop_123 Hotel_Paradise_124 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (stay Dublin) 0)
     (= (stay Edinburgh) 0)
     (= (stay Moscow) 0)
     (= (stay Krakow) 0)
     (= (stay Venice) 0)
     (= (stay Saint_Petersburg) 0)
     (= (stay Istanbul) 0)
     (= (stay Rome) 0)
     (= (stay Caracas) 0)
     (= (stay Rio_de_Janeiro) 0)
     (= (stay La_Habana) 0)
     (= (stay Medellin) 0)
     (= (stay Cali) 0)
     (= (stay Washington_DC) 0)
     (= (stay New_York) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 4)
     (= (minDaysCity Sidney) 2)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 1)
     (= (maxDaysCity Beijing) 5)
     (= (minDaysCity Taiwan) 1)
     (= (maxDaysCity Taiwan) 3)
     (= (minDaysCity Tokio) 1)
     (= (maxDaysCity Tokio) 5)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 4)
     (= (minDaysCity Paris) 1)
     (= (maxDaysCity Paris) 5)
     (= (minDaysCity London) 1)
     (= (maxDaysCity London) 3)
     (= (minDaysCity Berlin) 1)
     (= (maxDaysCity Berlin) 5)
     (= (minDaysCity Dublin) 1)
     (= (maxDaysCity Dublin) 3)
     (= (minDaysCity Edinburgh) 1)
     (= (maxDaysCity Edinburgh) 5)
     (= (minDaysCity Moscow) 2)
     (= (maxDaysCity Moscow) 4)
     (= (minDaysCity Krakow) 1)
     (= (maxDaysCity Krakow) 5)
     (= (minDaysCity Venice) 2)
     (= (maxDaysCity Venice) 5)
     (= (minDaysCity Saint_Petersburg) 2)
     (= (maxDaysCity Saint_Petersburg) 4)
     (= (minDaysCity Istanbul) 2)
     (= (maxDaysCity Istanbul) 5)
     (= (minDaysCity Rome) 1)
     (= (maxDaysCity Rome) 3)
     (= (minDaysCity Caracas) 2)
     (= (maxDaysCity Caracas) 5)
     (= (minDaysCity Rio_de_Janeiro) 2)
     (= (maxDaysCity Rio_de_Janeiro) 4)
     (= (minDaysCity La_Habana) 2)
     (= (maxDaysCity La_Habana) 3)
     (= (minDaysCity Medellin) 2)
     (= (maxDaysCity Medellin) 3)
     (= (minDaysCity Cali) 1)
     (= (maxDaysCity Cali) 4)
     (= (minDaysCity Washington_DC) 1)
     (= (maxDaysCity Washington_DC) 5)
     (= (minDaysCity New_York) 1)
     (= (maxDaysCity New_York) 3)
     (= (total-interest) 0)
     (= (cityInterest Melbourne) 2)
     (= (cityInterest Sidney) 3)
     (= (cityInterest Wellington) 1)
     (= (cityInterest Beijing) 1)
     (= (cityInterest Taiwan) 1)
     (= (cityInterest Tokio) 2)
     (= (cityInterest Nova_Dheli) 1)
     (= (cityInterest Paris) 1)
     (= (cityInterest London) 2)
     (= (cityInterest Berlin) 1)
     (= (cityInterest Dublin) 3)
     (= (cityInterest Edinburgh) 3)
     (= (cityInterest Moscow) 2)
     (= (cityInterest Krakow) 2)
     (= (cityInterest Venice) 1)
     (= (cityInterest Saint_Petersburg) 1)
     (= (cityInterest Istanbul) 3)
     (= (cityInterest Rome) 3)
     (= (cityInterest Caracas) 1)
     (= (cityInterest Rio_de_Janeiro) 3)
     (= (cityInterest La_Habana) 1)
     (= (cityInterest Medellin) 1)
     (= (cityInterest Cali) 2)
     (= (cityInterest Washington_DC) 1)
     (= (cityInterest New_York) 2)
     (flight Melbourne Sidney)
     (flight Melbourne Wellington)
     (flight Melbourne Beijing)
     (flight Melbourne Taiwan)
     (flight Melbourne Tokio)
     (flight Melbourne Nova_Dheli)
     (flight Melbourne Paris)
     (flight Melbourne London)
     (flight Melbourne Berlin)
     (flight Melbourne Dublin)
     (flight Melbourne Edinburgh)
     (flight Melbourne Moscow)
     (flight Melbourne Krakow)
     (flight Melbourne Venice)
     (flight Melbourne Saint_Petersburg)
     (flight Melbourne Istanbul)
     (flight Melbourne Rome)
     (flight Melbourne Caracas)
     (flight Melbourne Rio_de_Janeiro)
     (flight Melbourne La_Habana)
     (flight Melbourne Medellin)
     (flight Melbourne Cali)
     (flight Melbourne Washington_DC)
     (flight Melbourne New_York)
     (flight Sidney Melbourne)
     (flight Sidney Wellington)
     (flight Sidney Beijing)
     (flight Sidney Taiwan)
     (flight Sidney Tokio)
     (flight Sidney Nova_Dheli)
     (flight Sidney Paris)
     (flight Sidney London)
     (flight Sidney Berlin)
     (flight Sidney Dublin)
     (flight Sidney Edinburgh)
     (flight Sidney Moscow)
     (flight Sidney Krakow)
     (flight Sidney Venice)
     (flight Sidney Saint_Petersburg)
     (flight Sidney Istanbul)
     (flight Sidney Rome)
     (flight Sidney Caracas)
     (flight Sidney Rio_de_Janeiro)
     (flight Sidney La_Habana)
     (flight Sidney Medellin)
     (flight Sidney Cali)
     (flight Sidney Washington_DC)
     (flight Sidney New_York)
     (flight Wellington Melbourne)
     (flight Wellington Sidney)
     (flight Wellington Beijing)
     (flight Wellington Taiwan)
     (flight Wellington Tokio)
     (flight Wellington Nova_Dheli)
     (flight Wellington Paris)
     (flight Wellington London)
     (flight Wellington Berlin)
     (flight Wellington Dublin)
     (flight Wellington Edinburgh)
     (flight Wellington Moscow)
     (flight Wellington Krakow)
     (flight Wellington Venice)
     (flight Wellington Saint_Petersburg)
     (flight Wellington Istanbul)
     (flight Wellington Rome)
     (flight Wellington Caracas)
     (flight Wellington Rio_de_Janeiro)
     (flight Wellington La_Habana)
     (flight Wellington Medellin)
     (flight Wellington Cali)
     (flight Wellington Washington_DC)
     (flight Wellington New_York)
     (flight Beijing Melbourne)
     (flight Beijing Sidney)
     (flight Beijing Wellington)
     (flight Beijing Taiwan)
     (flight Beijing Tokio)
     (flight Beijing Nova_Dheli)
     (flight Beijing Paris)
     (flight Beijing London)
     (flight Beijing Berlin)
     (flight Beijing Dublin)
     (flight Beijing Edinburgh)
     (flight Beijing Moscow)
     (flight Beijing Krakow)
     (flight Beijing Venice)
     (flight Beijing Saint_Petersburg)
     (flight Beijing Istanbul)
     (flight Beijing Rome)
     (flight Beijing Caracas)
     (flight Beijing Rio_de_Janeiro)
     (flight Beijing La_Habana)
     (flight Beijing Medellin)
     (flight Beijing Cali)
     (flight Beijing Washington_DC)
     (flight Beijing New_York)
     (flight Taiwan Melbourne)
     (flight Taiwan Sidney)
     (flight Taiwan Wellington)
     (flight Taiwan Beijing)
     (flight Taiwan Tokio)
     (flight Taiwan Nova_Dheli)
     (flight Taiwan Paris)
     (flight Taiwan London)
     (flight Taiwan Berlin)
     (flight Taiwan Dublin)
     (flight Taiwan Edinburgh)
     (flight Taiwan Moscow)
     (flight Taiwan Krakow)
     (flight Taiwan Venice)
     (flight Taiwan Saint_Petersburg)
     (flight Taiwan Istanbul)
     (flight Taiwan Rome)
     (flight Taiwan Caracas)
     (flight Taiwan Rio_de_Janeiro)
     (flight Taiwan La_Habana)
     (flight Taiwan Medellin)
     (flight Taiwan Cali)
     (flight Taiwan Washington_DC)
     (flight Taiwan New_York)
     (flight Tokio Melbourne)
     (flight Tokio Sidney)
     (flight Tokio Wellington)
     (flight Tokio Beijing)
     (flight Tokio Taiwan)
     (flight Tokio Nova_Dheli)
     (flight Tokio Paris)
     (flight Tokio London)
     (flight Tokio Berlin)
     (flight Tokio Dublin)
     (flight Tokio Edinburgh)
     (flight Tokio Moscow)
     (flight Tokio Krakow)
     (flight Tokio Venice)
     (flight Tokio Saint_Petersburg)
     (flight Tokio Istanbul)
     (flight Tokio Rome)
     (flight Tokio Caracas)
     (flight Tokio Rio_de_Janeiro)
     (flight Tokio La_Habana)
     (flight Tokio Medellin)
     (flight Tokio Cali)
     (flight Tokio Washington_DC)
     (flight Tokio New_York)
     (flight Nova_Dheli Melbourne)
     (flight Nova_Dheli Sidney)
     (flight Nova_Dheli Wellington)
     (flight Nova_Dheli Beijing)
     (flight Nova_Dheli Taiwan)
     (flight Nova_Dheli Tokio)
     (flight Nova_Dheli Paris)
     (flight Nova_Dheli London)
     (flight Nova_Dheli Berlin)
     (flight Nova_Dheli Dublin)
     (flight Nova_Dheli Edinburgh)
     (flight Nova_Dheli Moscow)
     (flight Nova_Dheli Krakow)
     (flight Nova_Dheli Venice)
     (flight Nova_Dheli Saint_Petersburg)
     (flight Nova_Dheli Istanbul)
     (flight Nova_Dheli Rome)
     (flight Nova_Dheli Caracas)
     (flight Nova_Dheli Rio_de_Janeiro)
     (flight Nova_Dheli La_Habana)
     (flight Nova_Dheli Medellin)
     (flight Nova_Dheli Cali)
     (flight Nova_Dheli Washington_DC)
     (flight Nova_Dheli New_York)
     (flight Paris Melbourne)
     (flight Paris Sidney)
     (flight Paris Wellington)
     (flight Paris Beijing)
     (flight Paris Taiwan)
     (flight Paris Tokio)
     (flight Paris Nova_Dheli)
     (flight Paris London)
     (flight Paris Berlin)
     (flight Paris Dublin)
     (flight Paris Edinburgh)
     (flight Paris Moscow)
     (flight Paris Krakow)
     (flight Paris Venice)
     (flight Paris Saint_Petersburg)
     (flight Paris Istanbul)
     (flight Paris Rome)
     (flight Paris Caracas)
     (flight Paris Rio_de_Janeiro)
     (flight Paris La_Habana)
     (flight Paris Medellin)
     (flight Paris Cali)
     (flight Paris Washington_DC)
     (flight Paris New_York)
     (flight London Melbourne)
     (flight London Sidney)
     (flight London Wellington)
     (flight London Beijing)
     (flight London Taiwan)
     (flight London Tokio)
     (flight London Nova_Dheli)
     (flight London Paris)
     (flight London Berlin)
     (flight London Dublin)
     (flight London Edinburgh)
     (flight London Moscow)
     (flight London Krakow)
     (flight London Venice)
     (flight London Saint_Petersburg)
     (flight London Istanbul)
     (flight London Rome)
     (flight London Caracas)
     (flight London Rio_de_Janeiro)
     (flight London La_Habana)
     (flight London Medellin)
     (flight London Cali)
     (flight London Washington_DC)
     (flight London New_York)
     (flight Berlin Melbourne)
     (flight Berlin Sidney)
     (flight Berlin Wellington)
     (flight Berlin Beijing)
     (flight Berlin Taiwan)
     (flight Berlin Tokio)
     (flight Berlin Nova_Dheli)
     (flight Berlin Paris)
     (flight Berlin London)
     (flight Berlin Dublin)
     (flight Berlin Edinburgh)
     (flight Berlin Moscow)
     (flight Berlin Krakow)
     (flight Berlin Venice)
     (flight Berlin Saint_Petersburg)
     (flight Berlin Istanbul)
     (flight Berlin Rome)
     (flight Berlin Caracas)
     (flight Berlin Rio_de_Janeiro)
     (flight Berlin La_Habana)
     (flight Berlin Medellin)
     (flight Berlin Cali)
     (flight Berlin Washington_DC)
     (flight Berlin New_York)
     (flight Dublin Melbourne)
     (flight Dublin Sidney)
     (flight Dublin Wellington)
     (flight Dublin Beijing)
     (flight Dublin Taiwan)
     (flight Dublin Tokio)
     (flight Dublin Nova_Dheli)
     (flight Dublin Paris)
     (flight Dublin London)
     (flight Dublin Berlin)
     (flight Dublin Edinburgh)
     (flight Dublin Moscow)
     (flight Dublin Krakow)
     (flight Dublin Venice)
     (flight Dublin Saint_Petersburg)
     (flight Dublin Istanbul)
     (flight Dublin Rome)
     (flight Dublin Caracas)
     (flight Dublin Rio_de_Janeiro)
     (flight Dublin La_Habana)
     (flight Dublin Medellin)
     (flight Dublin Cali)
     (flight Dublin Washington_DC)
     (flight Dublin New_York)
     (flight Edinburgh Melbourne)
     (flight Edinburgh Sidney)
     (flight Edinburgh Wellington)
     (flight Edinburgh Beijing)
     (flight Edinburgh Taiwan)
     (flight Edinburgh Tokio)
     (flight Edinburgh Nova_Dheli)
     (flight Edinburgh Paris)
     (flight Edinburgh London)
     (flight Edinburgh Berlin)
     (flight Edinburgh Dublin)
     (flight Edinburgh Moscow)
     (flight Edinburgh Krakow)
     (flight Edinburgh Venice)
     (flight Edinburgh Saint_Petersburg)
     (flight Edinburgh Istanbul)
     (flight Edinburgh Rome)
     (flight Edinburgh Caracas)
     (flight Edinburgh Rio_de_Janeiro)
     (flight Edinburgh La_Habana)
     (flight Edinburgh Medellin)
     (flight Edinburgh Cali)
     (flight Edinburgh Washington_DC)
     (flight Edinburgh New_York)
     (flight Moscow Melbourne)
     (flight Moscow Sidney)
     (flight Moscow Wellington)
     (flight Moscow Beijing)
     (flight Moscow Taiwan)
     (flight Moscow Tokio)
     (flight Moscow Nova_Dheli)
     (flight Moscow Paris)
     (flight Moscow London)
     (flight Moscow Berlin)
     (flight Moscow Dublin)
     (flight Moscow Edinburgh)
     (flight Moscow Krakow)
     (flight Moscow Venice)
     (flight Moscow Saint_Petersburg)
     (flight Moscow Istanbul)
     (flight Moscow Rome)
     (flight Moscow Caracas)
     (flight Moscow Rio_de_Janeiro)
     (flight Moscow La_Habana)
     (flight Moscow Medellin)
     (flight Moscow Cali)
     (flight Moscow Washington_DC)
     (flight Moscow New_York)
     (flight Krakow Melbourne)
     (flight Krakow Sidney)
     (flight Krakow Wellington)
     (flight Krakow Beijing)
     (flight Krakow Taiwan)
     (flight Krakow Tokio)
     (flight Krakow Nova_Dheli)
     (flight Krakow Paris)
     (flight Krakow London)
     (flight Krakow Berlin)
     (flight Krakow Dublin)
     (flight Krakow Edinburgh)
     (flight Krakow Moscow)
     (flight Krakow Venice)
     (flight Krakow Saint_Petersburg)
     (flight Krakow Istanbul)
     (flight Krakow Rome)
     (flight Krakow Caracas)
     (flight Krakow Rio_de_Janeiro)
     (flight Krakow La_Habana)
     (flight Krakow Medellin)
     (flight Krakow Cali)
     (flight Krakow Washington_DC)
     (flight Krakow New_York)
     (flight Venice Melbourne)
     (flight Venice Sidney)
     (flight Venice Wellington)
     (flight Venice Beijing)
     (flight Venice Taiwan)
     (flight Venice Tokio)
     (flight Venice Nova_Dheli)
     (flight Venice Paris)
     (flight Venice London)
     (flight Venice Berlin)
     (flight Venice Dublin)
     (flight Venice Edinburgh)
     (flight Venice Moscow)
     (flight Venice Krakow)
     (flight Venice Saint_Petersburg)
     (flight Venice Istanbul)
     (flight Venice Rome)
     (flight Venice Caracas)
     (flight Venice Rio_de_Janeiro)
     (flight Venice La_Habana)
     (flight Venice Medellin)
     (flight Venice Cali)
     (flight Venice Washington_DC)
     (flight Venice New_York)
     (flight Saint_Petersburg Melbourne)
     (flight Saint_Petersburg Sidney)
     (flight Saint_Petersburg Wellington)
     (flight Saint_Petersburg Beijing)
     (flight Saint_Petersburg Taiwan)
     (flight Saint_Petersburg Tokio)
     (flight Saint_Petersburg Nova_Dheli)
     (flight Saint_Petersburg Paris)
     (flight Saint_Petersburg London)
     (flight Saint_Petersburg Berlin)
     (flight Saint_Petersburg Dublin)
     (flight Saint_Petersburg Edinburgh)
     (flight Saint_Petersburg Moscow)
     (flight Saint_Petersburg Krakow)
     (flight Saint_Petersburg Venice)
     (flight Saint_Petersburg Istanbul)
     (flight Saint_Petersburg Rome)
     (flight Saint_Petersburg Caracas)
     (flight Saint_Petersburg Rio_de_Janeiro)
     (flight Saint_Petersburg La_Habana)
     (flight Saint_Petersburg Medellin)
     (flight Saint_Petersburg Cali)
     (flight Saint_Petersburg Washington_DC)
     (flight Saint_Petersburg New_York)
     (flight Istanbul Melbourne)
     (flight Istanbul Sidney)
     (flight Istanbul Wellington)
     (flight Istanbul Beijing)
     (flight Istanbul Taiwan)
     (flight Istanbul Tokio)
     (flight Istanbul Nova_Dheli)
     (flight Istanbul Paris)
     (flight Istanbul London)
     (flight Istanbul Berlin)
     (flight Istanbul Dublin)
     (flight Istanbul Edinburgh)
     (flight Istanbul Moscow)
     (flight Istanbul Krakow)
     (flight Istanbul Venice)
     (flight Istanbul Saint_Petersburg)
     (flight Istanbul Rome)
     (flight Istanbul Caracas)
     (flight Istanbul Rio_de_Janeiro)
     (flight Istanbul La_Habana)
     (flight Istanbul Medellin)
     (flight Istanbul Cali)
     (flight Istanbul Washington_DC)
     (flight Istanbul New_York)
     (flight Rome Melbourne)
     (flight Rome Sidney)
     (flight Rome Wellington)
     (flight Rome Beijing)
     (flight Rome Taiwan)
     (flight Rome Tokio)
     (flight Rome Nova_Dheli)
     (flight Rome Paris)
     (flight Rome London)
     (flight Rome Berlin)
     (flight Rome Dublin)
     (flight Rome Edinburgh)
     (flight Rome Moscow)
     (flight Rome Krakow)
     (flight Rome Venice)
     (flight Rome Saint_Petersburg)
     (flight Rome Istanbul)
     (flight Rome Caracas)
     (flight Rome Rio_de_Janeiro)
     (flight Rome La_Habana)
     (flight Rome Medellin)
     (flight Rome Cali)
     (flight Rome Washington_DC)
     (flight Rome New_York)
     (flight Caracas Melbourne)
     (flight Caracas Sidney)
     (flight Caracas Wellington)
     (flight Caracas Beijing)
     (flight Caracas Taiwan)
     (flight Caracas Tokio)
     (flight Caracas Nova_Dheli)
     (flight Caracas Paris)
     (flight Caracas London)
     (flight Caracas Berlin)
     (flight Caracas Dublin)
     (flight Caracas Edinburgh)
     (flight Caracas Moscow)
     (flight Caracas Krakow)
     (flight Caracas Venice)
     (flight Caracas Saint_Petersburg)
     (flight Caracas Istanbul)
     (flight Caracas Rome)
     (flight Caracas Rio_de_Janeiro)
     (flight Caracas La_Habana)
     (flight Caracas Medellin)
     (flight Caracas Cali)
     (flight Caracas Washington_DC)
     (flight Caracas New_York)
     (flight Rio_de_Janeiro Melbourne)
     (flight Rio_de_Janeiro Sidney)
     (flight Rio_de_Janeiro Wellington)
     (flight Rio_de_Janeiro Beijing)
     (flight Rio_de_Janeiro Taiwan)
     (flight Rio_de_Janeiro Tokio)
     (flight Rio_de_Janeiro Nova_Dheli)
     (flight Rio_de_Janeiro Paris)
     (flight Rio_de_Janeiro London)
     (flight Rio_de_Janeiro Berlin)
     (flight Rio_de_Janeiro Dublin)
     (flight Rio_de_Janeiro Edinburgh)
     (flight Rio_de_Janeiro Moscow)
     (flight Rio_de_Janeiro Krakow)
     (flight Rio_de_Janeiro Venice)
     (flight Rio_de_Janeiro Saint_Petersburg)
     (flight Rio_de_Janeiro Istanbul)
     (flight Rio_de_Janeiro Rome)
     (flight Rio_de_Janeiro Caracas)
     (flight Rio_de_Janeiro La_Habana)
     (flight Rio_de_Janeiro Medellin)
     (flight Rio_de_Janeiro Cali)
     (flight Rio_de_Janeiro Washington_DC)
     (flight Rio_de_Janeiro New_York)
     (flight La_Habana Melbourne)
     (flight La_Habana Sidney)
     (flight La_Habana Wellington)
     (flight La_Habana Beijing)
     (flight La_Habana Taiwan)
     (flight La_Habana Tokio)
     (flight La_Habana Nova_Dheli)
     (flight La_Habana Paris)
     (flight La_Habana London)
     (flight La_Habana Berlin)
     (flight La_Habana Dublin)
     (flight La_Habana Edinburgh)
     (flight La_Habana Moscow)
     (flight La_Habana Krakow)
     (flight La_Habana Venice)
     (flight La_Habana Saint_Petersburg)
     (flight La_Habana Istanbul)
     (flight La_Habana Rome)
     (flight La_Habana Caracas)
     (flight La_Habana Rio_de_Janeiro)
     (flight La_Habana Medellin)
     (flight La_Habana Cali)
     (flight La_Habana Washington_DC)
     (flight La_Habana New_York)
     (flight Medellin Melbourne)
     (flight Medellin Sidney)
     (flight Medellin Wellington)
     (flight Medellin Beijing)
     (flight Medellin Taiwan)
     (flight Medellin Tokio)
     (flight Medellin Nova_Dheli)
     (flight Medellin Paris)
     (flight Medellin London)
     (flight Medellin Berlin)
     (flight Medellin Dublin)
     (flight Medellin Edinburgh)
     (flight Medellin Moscow)
     (flight Medellin Krakow)
     (flight Medellin Venice)
     (flight Medellin Saint_Petersburg)
     (flight Medellin Istanbul)
     (flight Medellin Rome)
     (flight Medellin Caracas)
     (flight Medellin Rio_de_Janeiro)
     (flight Medellin La_Habana)
     (flight Medellin Cali)
     (flight Medellin Washington_DC)
     (flight Medellin New_York)
     (flight Cali Melbourne)
     (flight Cali Sidney)
     (flight Cali Wellington)
     (flight Cali Beijing)
     (flight Cali Taiwan)
     (flight Cali Tokio)
     (flight Cali Nova_Dheli)
     (flight Cali Paris)
     (flight Cali London)
     (flight Cali Berlin)
     (flight Cali Dublin)
     (flight Cali Edinburgh)
     (flight Cali Moscow)
     (flight Cali Krakow)
     (flight Cali Venice)
     (flight Cali Saint_Petersburg)
     (flight Cali Istanbul)
     (flight Cali Rome)
     (flight Cali Caracas)
     (flight Cali Rio_de_Janeiro)
     (flight Cali La_Habana)
     (flight Cali Medellin)
     (flight Cali Washington_DC)
     (flight Cali New_York)
     (flight Washington_DC Melbourne)
     (flight Washington_DC Sidney)
     (flight Washington_DC Wellington)
     (flight Washington_DC Beijing)
     (flight Washington_DC Taiwan)
     (flight Washington_DC Tokio)
     (flight Washington_DC Nova_Dheli)
     (flight Washington_DC Paris)
     (flight Washington_DC London)
     (flight Washington_DC Berlin)
     (flight Washington_DC Dublin)
     (flight Washington_DC Edinburgh)
     (flight Washington_DC Moscow)
     (flight Washington_DC Krakow)
     (flight Washington_DC Venice)
     (flight Washington_DC Saint_Petersburg)
     (flight Washington_DC Istanbul)
     (flight Washington_DC Rome)
     (flight Washington_DC Caracas)
     (flight Washington_DC Rio_de_Janeiro)
     (flight Washington_DC La_Habana)
     (flight Washington_DC Medellin)
     (flight Washington_DC Cali)
     (flight Washington_DC New_York)
     (flight New_York Melbourne)
     (flight New_York Sidney)
     (flight New_York Wellington)
     (flight New_York Beijing)
     (flight New_York Taiwan)
     (flight New_York Tokio)
     (flight New_York Nova_Dheli)
     (flight New_York Paris)
     (flight New_York London)
     (flight New_York Berlin)
     (flight New_York Dublin)
     (flight New_York Edinburgh)
     (flight New_York Moscow)
     (flight New_York Krakow)
     (flight New_York Venice)
     (flight New_York Saint_Petersburg)
     (flight New_York Istanbul)
     (flight New_York Rome)
     (flight New_York Caracas)
     (flight New_York Rio_de_Janeiro)
     (flight New_York La_Habana)
     (flight New_York Medellin)
     (flight New_York Cali)
     (flight New_York Washington_DC)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Melbourne)
     (inCity Hotel_Emperor_2 Melbourne)
     (inCity Residence_Sky_3 Melbourne)
     (inCity Hostel_Delphin_4 Melbourne)
     (inCity Residence_Single_Land_5 Sidney)
     (inCity Resort_Lollipop_6 Sidney)
     (inCity Hostel_Emperor_7 Sidney)
     (inCity Hostel_Lollipop_8 Sidney)
     (inCity Hostel_Single_Land_9 Sidney)
     (inCity Apartments_Paradise_10 Wellington)
     (inCity Resort_Arabiga_11 Wellington)
     (inCity Hotel_Single_Land_12 Wellington)
     (inCity Apartments_Single_Land_13 Wellington)
     (inCity Hotel_Arabiga_14 Wellington)
     (inCity Residence_Delphin_15 Beijing)
     (inCity Apartments_Single_Land_16 Beijing)
     (inCity Residence_Delphin_17 Beijing)
     (inCity Hostel_Emperor_18 Beijing)
     (inCity Residence_Paradise_19 Beijing)
     (inCity Apartments_Delphin_20 Taiwan)
     (inCity Resort_Paradise_21 Taiwan)
     (inCity Residence_Relax_22 Taiwan)
     (inCity Resort_NH_23 Taiwan)
     (inCity Hotel_Chill_24 Taiwan)
     (inCity Hostel_Emperor_25 Tokio)
     (inCity Hotel_Paradise_26 Tokio)
     (inCity Apartments_Sky_27 Tokio)
     (inCity Hotel_Single_Land_28 Tokio)
     (inCity Hostel_Sky_29 Tokio)
     (inCity Hotel_Chill_30 Nova_Dheli)
     (inCity Residence_Relax_31 Nova_Dheli)
     (inCity Hotel_Sky_32 Nova_Dheli)
     (inCity Resort_Sky_33 Nova_Dheli)
     (inCity Residence_Emperor_34 Nova_Dheli)
     (inCity Hotel_Relax_35 Paris)
     (inCity Hotel_Single_Land_36 Paris)
     (inCity Residence_Relax_37 Paris)
     (inCity Resort_Relax_38 Paris)
     (inCity Hotel_Emperor_39 Paris)
     (inCity Apartments_Arabiga_40 London)
     (inCity Apartments_Sky_41 London)
     (inCity Resort_NH_42 London)
     (inCity Hostel_Emperor_43 London)
     (inCity Resort_Relax_44 London)
     (inCity Hotel_Single_Land_45 Berlin)
     (inCity Apartments_Sky_46 Berlin)
     (inCity Residence_Delphin_47 Berlin)
     (inCity Hostel_Sky_48 Berlin)
     (inCity Resort_Relax_49 Berlin)
     (inCity Hotel_Chill_50 Dublin)
     (inCity Apartments_Relax_51 Dublin)
     (inCity Hostel_Arabiga_52 Dublin)
     (inCity Residence_Arabiga_53 Dublin)
     (inCity Residence_Arabiga_54 Dublin)
     (inCity Hostel_Single_Land_55 Edinburgh)
     (inCity Hotel_Paradise_56 Edinburgh)
     (inCity Hostel_Sky_57 Edinburgh)
     (inCity Resort_Chill_58 Edinburgh)
     (inCity Resort_Relax_59 Edinburgh)
     (inCity Resort_Lollipop_60 Moscow)
     (inCity Residence_Paradise_61 Moscow)
     (inCity Hostel_Arabiga_62 Moscow)
     (inCity Hotel_Paradise_63 Moscow)
     (inCity Residence_Delphin_64 Moscow)
     (inCity Hostel_Arabiga_65 Krakow)
     (inCity Apartments_Arabiga_66 Krakow)
     (inCity Hotel_Sky_67 Krakow)
     (inCity Apartments_Sky_68 Krakow)
     (inCity Resort_Delphin_69 Krakow)
     (inCity Hostel_NH_70 Venice)
     (inCity Resort_Single_Land_71 Venice)
     (inCity Resort_Emperor_72 Venice)
     (inCity Apartments_Lollipop_73 Venice)
     (inCity Hotel_NH_74 Venice)
     (inCity Resort_Lollipop_75 Saint_Petersburg)
     (inCity Apartments_Sky_76 Saint_Petersburg)
     (inCity Hotel_NH_77 Saint_Petersburg)
     (inCity Hostel_Sky_78 Saint_Petersburg)
     (inCity Hotel_Paradise_79 Saint_Petersburg)
     (inCity Apartments_Delphin_80 Istanbul)
     (inCity Apartments_Relax_81 Istanbul)
     (inCity Hotel_Paradise_82 Istanbul)
     (inCity Hotel_Emperor_83 Istanbul)
     (inCity Resort_Relax_84 Istanbul)
     (inCity Resort_Relax_85 Rome)
     (inCity Hostel_Arabiga_86 Rome)
     (inCity Hostel_Emperor_87 Rome)
     (inCity Hotel_Arabiga_88 Rome)
     (inCity Hostel_Delphin_89 Rome)
     (inCity Hostel_Single_Land_90 Caracas)
     (inCity Apartments_Arabiga_91 Caracas)
     (inCity Residence_Chill_92 Caracas)
     (inCity Hostel_Relax_93 Caracas)
     (inCity Hotel_NH_94 Caracas)
     (inCity Residence_Delphin_95 Rio_de_Janeiro)
     (inCity Apartments_Chill_96 Rio_de_Janeiro)
     (inCity Apartments_NH_97 Rio_de_Janeiro)
     (inCity Hostel_Emperor_98 Rio_de_Janeiro)
     (inCity Resort_NH_99 Rio_de_Janeiro)
     (inCity Resort_Sky_100 La_Habana)
     (inCity Apartments_Emperor_101 La_Habana)
     (inCity Apartments_Emperor_102 La_Habana)
     (inCity Hotel_Sky_103 La_Habana)
     (inCity Apartments_Relax_104 La_Habana)
     (inCity Apartments_NH_105 Medellin)
     (inCity Residence_Delphin_106 Medellin)
     (inCity Hostel_Arabiga_107 Medellin)
     (inCity Apartments_Relax_108 Medellin)
     (inCity Apartments_Lollipop_109 Medellin)
     (inCity Resort_Lollipop_110 Cali)
     (inCity Hotel_Single_Land_111 Cali)
     (inCity Hotel_Relax_112 Cali)
     (inCity Resort_Chill_113 Cali)
     (inCity Hostel_Relax_114 Cali)
     (inCity Residence_Delphin_115 Washington_DC)
     (inCity Resort_Single_Land_116 Washington_DC)
     (inCity Residence_Arabiga_117 Washington_DC)
     (inCity Resort_Chill_118 Washington_DC)
     (inCity Hostel_NH_119 Washington_DC)
     (inCity Apartments_Single_Land_120 New_York)
     (inCity Apartments_Delphin_121 New_York)
     (inCity Apartments_Sky_122 New_York)
     (inCity Residence_Lollipop_123 New_York)
     (inCity Hotel_Paradise_124 New_York)
)

(:goal 
(and (= (visited-cities) 3)
     (> (total-days) 5)
)
)

(:metric minimize (total-interest))

)
