;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem40)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin Dublin Edinburgh Moscow Krakow Venice Saint_Petersburg Istanbul Rome Caracas Rio_de_Janeiro La_Habana Medellin Cali Washington_DC New_York - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 Apartments_Paradise_10 Resort_Arabiga_11 Hotel_Single_Land_12 Apartments_Single_Land_13 Hotel_Arabiga_14 Residence_Delphin_15 Apartments_Single_Land_16 Residence_Delphin_17 Hostel_Emperor_18 Residence_Paradise_19 Apartments_Delphin_20 Resort_Paradise_21 Residence_Relax_22 Resort_NH_23 Hotel_Chill_24 Hostel_Emperor_25 Hotel_Paradise_26 Apartments_Sky_27 Hotel_Single_Land_28 Hostel_Sky_29 Hotel_Chill_30 Residence_Relax_31 Hotel_Sky_32 Resort_Sky_33 Residence_Emperor_34 Hotel_Relax_35 Hotel_Single_Land_36 Residence_Relax_37 Resort_Relax_38 Hotel_Emperor_39 Apartments_Arabiga_40 Apartments_Sky_41 Resort_NH_42 Hostel_Emperor_43 Resort_Relax_44 Hotel_Single_Land_45 Apartments_Sky_46 Residence_Delphin_47 Hostel_Sky_48 Resort_Relax_49 Hotel_Chill_50 Apartments_Relax_51 Hostel_Arabiga_52 Residence_Arabiga_53 Residence_Arabiga_54 Hostel_Single_Land_55 Hotel_Paradise_56 Hostel_Sky_57 Resort_Chill_58 Resort_Relax_59 Resort_Lollipop_60 Residence_Paradise_61 Hostel_Arabiga_62 Hotel_Paradise_63 Residence_Delphin_64 Hostel_Arabiga_65 Apartments_Arabiga_66 Hotel_Sky_67 Apartments_Sky_68 Resort_Delphin_69 Hostel_NH_70 Resort_Single_Land_71 Resort_Emperor_72 Apartments_Lollipop_73 Hotel_NH_74 Resort_Lollipop_75 Apartments_Sky_76 Hotel_NH_77 Hostel_Sky_78 Hotel_Paradise_79 Apartments_Delphin_80 Apartments_Relax_81 Hotel_Paradise_82 Hotel_Emperor_83 Resort_Relax_84 Resort_Relax_85 Hostel_Arabiga_86 Hostel_Emperor_87 Hotel_Arabiga_88 Hostel_Delphin_89 Hostel_Single_Land_90 Apartments_Arabiga_91 Residence_Chill_92 Hostel_Relax_93 Hotel_NH_94 Residence_Delphin_95 Apartments_Chill_96 Apartments_NH_97 Hostel_Emperor_98 Resort_NH_99 Resort_Sky_100 Apartments_Emperor_101 Apartments_Emperor_102 Hotel_Sky_103 Apartments_Relax_104 Apartments_NH_105 Residence_Delphin_106 Hostel_Arabiga_107 Apartments_Relax_108 Apartments_Lollipop_109 Resort_Lollipop_110 Hotel_Single_Land_111 Hotel_Relax_112 Resort_Chill_113 Hostel_Relax_114 Residence_Delphin_115 Resort_Single_Land_116 Residence_Arabiga_117 Resort_Chill_118 Hostel_NH_119 Apartments_Single_Land_120 Apartments_Delphin_121 Apartments_Sky_122 Residence_Lollipop_123 Hotel_Paradise_124 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (stay Dublin) 0)
     (= (stay Edinburgh) 0)
     (= (stay Moscow) 0)
     (= (stay Krakow) 0)
     (= (stay Venice) 0)
     (= (stay Saint_Petersburg) 0)
     (= (stay Istanbul) 0)
     (= (stay Rome) 0)
     (= (stay Caracas) 0)
     (= (stay Rio_de_Janeiro) 0)
     (= (stay La_Habana) 0)
     (= (stay Medellin) 0)
     (= (stay Cali) 0)
     (= (stay Washington_DC) 0)
     (= (stay New_York) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 4)
     (= (minDaysCity Sidney) 2)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 1)
     (= (maxDaysCity Beijing) 5)
     (= (minDaysCity Taiwan) 1)
     (= (maxDaysCity Taiwan) 3)
     (= (minDaysCity Tokio) 1)
     (= (maxDaysCity Tokio) 5)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 4)
     (= (minDaysCity Paris) 1)
     (= (maxDaysCity Paris) 5)
     (= (minDaysCity London) 1)
     (= (maxDaysCity London) 3)
     (= (minDaysCity Berlin) 1)
     (= (maxDaysCity Berlin) 5)
     (= (minDaysCity Dublin) 1)
     (= (maxDaysCity Dublin) 3)
     (= (minDaysCity Edinburgh) 1)
     (= (maxDaysCity Edinburgh) 5)
     (= (minDaysCity Moscow) 2)
     (= (maxDaysCity Moscow) 4)
     (= (minDaysCity Krakow) 1)
     (= (maxDaysCity Krakow) 5)
     (= (minDaysCity Venice) 2)
     (= (maxDaysCity Venice) 5)
     (= (minDaysCity Saint_Petersburg) 2)
     (= (maxDaysCity Saint_Petersburg) 4)
     (= (minDaysCity Istanbul) 2)
     (= (maxDaysCity Istanbul) 5)
     (= (minDaysCity Rome) 1)
     (= (maxDaysCity Rome) 3)
     (= (minDaysCity Caracas) 2)
     (= (maxDaysCity Caracas) 5)
     (= (minDaysCity Rio_de_Janeiro) 2)
     (= (maxDaysCity Rio_de_Janeiro) 4)
     (= (minDaysCity La_Habana) 2)
     (= (maxDaysCity La_Habana) 3)
     (= (minDaysCity Medellin) 2)
     (= (maxDaysCity Medellin) 3)
     (= (minDaysCity Cali) 1)
     (= (maxDaysCity Cali) 4)
     (= (minDaysCity Washington_DC) 1)
     (= (maxDaysCity Washington_DC) 5)
     (= (minDaysCity New_York) 1)
     (= (maxDaysCity New_York) 3)
     (= (total-interest) 0)
     (= (cityInterest Melbourne) 2)
     (= (cityInterest Sidney) 3)
     (= (cityInterest Wellington) 1)
     (= (cityInterest Beijing) 1)
     (= (cityInterest Taiwan) 1)
     (= (cityInterest Tokio) 2)
     (= (cityInterest Nova_Dheli) 1)
     (= (cityInterest Paris) 1)
     (= (cityInterest London) 2)
     (= (cityInterest Berlin) 1)
     (= (cityInterest Dublin) 3)
     (= (cityInterest Edinburgh) 3)
     (= (cityInterest Moscow) 2)
     (= (cityInterest Krakow) 2)
     (= (cityInterest Venice) 1)
     (= (cityInterest Saint_Petersburg) 1)
     (= (cityInterest Istanbul) 3)
     (= (cityInterest Rome) 3)
     (= (cityInterest Caracas) 1)
     (= (cityInterest Rio_de_Janeiro) 3)
     (= (cityInterest La_Habana) 1)
     (= (cityInterest Medellin) 1)
     (= (cityInterest Cali) 2)
     (= (cityInterest Washington_DC) 1)
     (= (cityInterest New_York) 2)
     (= (total-price) 0)
     (= (minPriceTrip) 200)
     (= (maxPriceTrip) 400)
     (= (hotelPrice Hostel_Emperor_0) 35)
     (= (hotelPrice Hotel_Arabiga_1) 39)
     (= (hotelPrice Hotel_Emperor_2) 29)
     (= (hotelPrice Residence_Sky_3) 31)
     (= (hotelPrice Hostel_Delphin_4) 24)
     (= (hotelPrice Residence_Single_Land_5) 29)
     (= (hotelPrice Resort_Lollipop_6) 11)
     (= (hotelPrice Hostel_Emperor_7) 30)
     (= (hotelPrice Hostel_Lollipop_8) 27)
     (= (hotelPrice Hostel_Single_Land_9) 15)
     (= (hotelPrice Apartments_Paradise_10) 28)
     (= (hotelPrice Resort_Arabiga_11) 27)
     (= (hotelPrice Hotel_Single_Land_12) 30)
     (= (hotelPrice Apartments_Single_Land_13) 34)
     (= (hotelPrice Hotel_Arabiga_14) 38)
     (= (hotelPrice Residence_Delphin_15) 10)
     (= (hotelPrice Apartments_Single_Land_16) 14)
     (= (hotelPrice Residence_Delphin_17) 32)
     (= (hotelPrice Hostel_Emperor_18) 39)
     (= (hotelPrice Residence_Paradise_19) 36)
     (= (hotelPrice Apartments_Delphin_20) 11)
     (= (hotelPrice Resort_Paradise_21) 10)
     (= (hotelPrice Residence_Relax_22) 24)
     (= (hotelPrice Resort_NH_23) 32)
     (= (hotelPrice Hotel_Chill_24) 22)
     (= (hotelPrice Hostel_Emperor_25) 12)
     (= (hotelPrice Hotel_Paradise_26) 30)
     (= (hotelPrice Apartments_Sky_27) 35)
     (= (hotelPrice Hotel_Single_Land_28) 25)
     (= (hotelPrice Hostel_Sky_29) 12)
     (= (hotelPrice Hotel_Chill_30) 29)
     (= (hotelPrice Residence_Relax_31) 20)
     (= (hotelPrice Hotel_Sky_32) 12)
     (= (hotelPrice Resort_Sky_33) 18)
     (= (hotelPrice Residence_Emperor_34) 33)
     (= (hotelPrice Hotel_Relax_35) 18)
     (= (hotelPrice Hotel_Single_Land_36) 30)
     (= (hotelPrice Residence_Relax_37) 34)
     (= (hotelPrice Resort_Relax_38) 30)
     (= (hotelPrice Hotel_Emperor_39) 39)
     (= (hotelPrice Apartments_Arabiga_40) 31)
     (= (hotelPrice Apartments_Sky_41) 19)
     (= (hotelPrice Resort_NH_42) 26)
     (= (hotelPrice Hostel_Emperor_43) 22)
     (= (hotelPrice Resort_Relax_44) 35)
     (= (hotelPrice Hotel_Single_Land_45) 24)
     (= (hotelPrice Apartments_Sky_46) 14)
     (= (hotelPrice Residence_Delphin_47) 39)
     (= (hotelPrice Hostel_Sky_48) 39)
     (= (hotelPrice Resort_Relax_49) 13)
     (= (hotelPrice Hotel_Chill_50) 36)
     (= (hotelPrice Apartments_Relax_51) 10)
     (= (hotelPrice Hostel_Arabiga_52) 35)
     (= (hotelPrice Residence_Arabiga_53) 20)
     (= (hotelPrice Residence_Arabiga_54) 32)
     (= (hotelPrice Hostel_Single_Land_55) 39)
     (= (hotelPrice Hotel_Paradise_56) 14)
     (= (hotelPrice Hostel_Sky_57) 23)
     (= (hotelPrice Resort_Chill_58) 35)
     (= (hotelPrice Resort_Relax_59) 21)
     (= (hotelPrice Resort_Lollipop_60) 17)
     (= (hotelPrice Residence_Paradise_61) 24)
     (= (hotelPrice Hostel_Arabiga_62) 23)
     (= (hotelPrice Hotel_Paradise_63) 11)
     (= (hotelPrice Residence_Delphin_64) 24)
     (= (hotelPrice Hostel_Arabiga_65) 16)
     (= (hotelPrice Apartments_Arabiga_66) 19)
     (= (hotelPrice Hotel_Sky_67) 14)
     (= (hotelPrice Apartments_Sky_68) 32)
     (= (hotelPrice Resort_Delphin_69) 32)
     (= (hotelPrice Hostel_NH_70) 36)
     (= (hotelPrice Resort_Single_Land_71) 24)
     (= (hotelPrice Resort_Emperor_72) 11)
     (= (hotelPrice Apartments_Lollipop_73) 22)
     (= (hotelPrice Hotel_NH_74) 28)
     (= (hotelPrice Resort_Lollipop_75) 28)
     (= (hotelPrice Apartments_Sky_76) 29)
     (= (hotelPrice Hotel_NH_77) 32)
     (= (hotelPrice Hostel_Sky_78) 28)
     (= (hotelPrice Hotel_Paradise_79) 28)
     (= (hotelPrice Apartments_Delphin_80) 28)
     (= (hotelPrice Apartments_Relax_81) 16)
     (= (hotelPrice Hotel_Paradise_82) 28)
     (= (hotelPrice Hotel_Emperor_83) 23)
     (= (hotelPrice Resort_Relax_84) 18)
     (= (hotelPrice Resort_Relax_85) 13)
     (= (hotelPrice Hostel_Arabiga_86) 23)
     (= (hotelPrice Hostel_Emperor_87) 23)
     (= (hotelPrice Hotel_Arabiga_88) 18)
     (= (hotelPrice Hostel_Delphin_89) 10)
     (= (hotelPrice Hostel_Single_Land_90) 34)
     (= (hotelPrice Apartments_Arabiga_91) 17)
     (= (hotelPrice Residence_Chill_92) 16)
     (= (hotelPrice Hostel_Relax_93) 18)
     (= (hotelPrice Hotel_NH_94) 19)
     (= (hotelPrice Residence_Delphin_95) 30)
     (= (hotelPrice Apartments_Chill_96) 16)
     (= (hotelPrice Apartments_NH_97) 28)
     (= (hotelPrice Hostel_Emperor_98) 27)
     (= (hotelPrice Resort_NH_99) 39)
     (= (hotelPrice Resort_Sky_100) 20)
     (= (hotelPrice Apartments_Emperor_101) 23)
     (= (hotelPrice Apartments_Emperor_102) 23)
     (= (hotelPrice Hotel_Sky_103) 13)
     (= (hotelPrice Apartments_Relax_104) 27)
     (= (hotelPrice Apartments_NH_105) 33)
     (= (hotelPrice Residence_Delphin_106) 32)
     (= (hotelPrice Hostel_Arabiga_107) 16)
     (= (hotelPrice Apartments_Relax_108) 25)
     (= (hotelPrice Apartments_Lollipop_109) 12)
     (= (hotelPrice Resort_Lollipop_110) 26)
     (= (hotelPrice Hotel_Single_Land_111) 35)
     (= (hotelPrice Hotel_Relax_112) 18)
     (= (hotelPrice Resort_Chill_113) 37)
     (= (hotelPrice Hostel_Relax_114) 19)
     (= (hotelPrice Residence_Delphin_115) 26)
     (= (hotelPrice Resort_Single_Land_116) 10)
     (= (hotelPrice Residence_Arabiga_117) 24)
     (= (hotelPrice Resort_Chill_118) 31)
     (= (hotelPrice Hostel_NH_119) 10)
     (= (hotelPrice Apartments_Single_Land_120) 24)
     (= (hotelPrice Apartments_Delphin_121) 18)
     (= (hotelPrice Apartments_Sky_122) 17)
     (= (hotelPrice Residence_Lollipop_123) 30)
     (= (hotelPrice Hotel_Paradise_124) 18)
     (flight Melbourne Sidney)
     (= (flightPrice Melbourne Sidney) 96)
     (flight Melbourne Wellington)
     (= (flightPrice Melbourne Wellington) 82)
     (flight Melbourne Beijing)
     (= (flightPrice Melbourne Beijing) 94)
     (flight Melbourne Taiwan)
     (= (flightPrice Melbourne Taiwan) 107)
     (flight Melbourne Tokio)
     (= (flightPrice Melbourne Tokio) 99)
     (flight Melbourne Nova_Dheli)
     (= (flightPrice Melbourne Nova_Dheli) 93)
     (flight Melbourne Paris)
     (= (flightPrice Melbourne Paris) 109)
     (flight Melbourne London)
     (= (flightPrice Melbourne London) 82)
     (flight Melbourne Berlin)
     (= (flightPrice Melbourne Berlin) 98)
     (flight Melbourne Dublin)
     (= (flightPrice Melbourne Dublin) 83)
     (flight Melbourne Edinburgh)
     (= (flightPrice Melbourne Edinburgh) 100)
     (flight Melbourne Moscow)
     (= (flightPrice Melbourne Moscow) 91)
     (flight Melbourne Krakow)
     (= (flightPrice Melbourne Krakow) 97)
     (flight Melbourne Venice)
     (= (flightPrice Melbourne Venice) 98)
     (flight Melbourne Saint_Petersburg)
     (= (flightPrice Melbourne Saint_Petersburg) 99)
     (flight Melbourne Istanbul)
     (= (flightPrice Melbourne Istanbul) 91)
     (flight Melbourne Rome)
     (= (flightPrice Melbourne Rome) 85)
     (flight Melbourne Caracas)
     (= (flightPrice Melbourne Caracas) 94)
     (flight Melbourne Rio_de_Janeiro)
     (= (flightPrice Melbourne Rio_de_Janeiro) 99)
     (flight Melbourne La_Habana)
     (= (flightPrice Melbourne La_Habana) 82)
     (flight Melbourne Medellin)
     (= (flightPrice Melbourne Medellin) 95)
     (flight Melbourne Cali)
     (= (flightPrice Melbourne Cali) 107)
     (flight Melbourne Washington_DC)
     (= (flightPrice Melbourne Washington_DC) 104)
     (flight Melbourne New_York)
     (= (flightPrice Melbourne New_York) 109)
     (flight Sidney Melbourne)
     (= (flightPrice Sidney Melbourne) 99)
     (flight Sidney Wellington)
     (= (flightPrice Sidney Wellington) 104)
     (flight Sidney Beijing)
     (= (flightPrice Sidney Beijing) 85)
     (flight Sidney Taiwan)
     (= (flightPrice Sidney Taiwan) 99)
     (flight Sidney Tokio)
     (= (flightPrice Sidney Tokio) 103)
     (flight Sidney Nova_Dheli)
     (= (flightPrice Sidney Nova_Dheli) 105)
     (flight Sidney Paris)
     (= (flightPrice Sidney Paris) 107)
     (flight Sidney London)
     (= (flightPrice Sidney London) 90)
     (flight Sidney Berlin)
     (= (flightPrice Sidney Berlin) 108)
     (flight Sidney Dublin)
     (= (flightPrice Sidney Dublin) 91)
     (flight Sidney Edinburgh)
     (= (flightPrice Sidney Edinburgh) 109)
     (flight Sidney Moscow)
     (= (flightPrice Sidney Moscow) 89)
     (flight Sidney Krakow)
     (= (flightPrice Sidney Krakow) 97)
     (flight Sidney Venice)
     (= (flightPrice Sidney Venice) 108)
     (flight Sidney Saint_Petersburg)
     (= (flightPrice Sidney Saint_Petersburg) 92)
     (flight Sidney Istanbul)
     (= (flightPrice Sidney Istanbul) 85)
     (flight Sidney Rome)
     (= (flightPrice Sidney Rome) 103)
     (flight Sidney Caracas)
     (= (flightPrice Sidney Caracas) 104)
     (flight Sidney Rio_de_Janeiro)
     (= (flightPrice Sidney Rio_de_Janeiro) 89)
     (flight Sidney La_Habana)
     (= (flightPrice Sidney La_Habana) 90)
     (flight Sidney Medellin)
     (= (flightPrice Sidney Medellin) 92)
     (flight Sidney Cali)
     (= (flightPrice Sidney Cali) 100)
     (flight Sidney Washington_DC)
     (= (flightPrice Sidney Washington_DC) 101)
     (flight Sidney New_York)
     (= (flightPrice Sidney New_York) 89)
     (flight Wellington Melbourne)
     (= (flightPrice Wellington Melbourne) 106)
     (flight Wellington Sidney)
     (= (flightPrice Wellington Sidney) 82)
     (flight Wellington Beijing)
     (= (flightPrice Wellington Beijing) 91)
     (flight Wellington Taiwan)
     (= (flightPrice Wellington Taiwan) 92)
     (flight Wellington Tokio)
     (= (flightPrice Wellington Tokio) 80)
     (flight Wellington Nova_Dheli)
     (= (flightPrice Wellington Nova_Dheli) 107)
     (flight Wellington Paris)
     (= (flightPrice Wellington Paris) 83)
     (flight Wellington London)
     (= (flightPrice Wellington London) 91)
     (flight Wellington Berlin)
     (= (flightPrice Wellington Berlin) 101)
     (flight Wellington Dublin)
     (= (flightPrice Wellington Dublin) 89)
     (flight Wellington Edinburgh)
     (= (flightPrice Wellington Edinburgh) 80)
     (flight Wellington Moscow)
     (= (flightPrice Wellington Moscow) 95)
     (flight Wellington Krakow)
     (= (flightPrice Wellington Krakow) 106)
     (flight Wellington Venice)
     (= (flightPrice Wellington Venice) 107)
     (flight Wellington Saint_Petersburg)
     (= (flightPrice Wellington Saint_Petersburg) 97)
     (flight Wellington Istanbul)
     (= (flightPrice Wellington Istanbul) 104)
     (flight Wellington Rome)
     (= (flightPrice Wellington Rome) 80)
     (flight Wellington Caracas)
     (= (flightPrice Wellington Caracas) 96)
     (flight Wellington Rio_de_Janeiro)
     (= (flightPrice Wellington Rio_de_Janeiro) 84)
     (flight Wellington La_Habana)
     (= (flightPrice Wellington La_Habana) 97)
     (flight Wellington Medellin)
     (= (flightPrice Wellington Medellin) 94)
     (flight Wellington Cali)
     (= (flightPrice Wellington Cali) 88)
     (flight Wellington Washington_DC)
     (= (flightPrice Wellington Washington_DC) 95)
     (flight Wellington New_York)
     (= (flightPrice Wellington New_York) 88)
     (flight Beijing Melbourne)
     (= (flightPrice Beijing Melbourne) 82)
     (flight Beijing Sidney)
     (= (flightPrice Beijing Sidney) 96)
     (flight Beijing Wellington)
     (= (flightPrice Beijing Wellington) 90)
     (flight Beijing Taiwan)
     (= (flightPrice Beijing Taiwan) 86)
     (flight Beijing Tokio)
     (= (flightPrice Beijing Tokio) 86)
     (flight Beijing Nova_Dheli)
     (= (flightPrice Beijing Nova_Dheli) 104)
     (flight Beijing Paris)
     (= (flightPrice Beijing Paris) 96)
     (flight Beijing London)
     (= (flightPrice Beijing London) 82)
     (flight Beijing Berlin)
     (= (flightPrice Beijing Berlin) 98)
     (flight Beijing Dublin)
     (= (flightPrice Beijing Dublin) 99)
     (flight Beijing Edinburgh)
     (= (flightPrice Beijing Edinburgh) 86)
     (flight Beijing Moscow)
     (= (flightPrice Beijing Moscow) 90)
     (flight Beijing Krakow)
     (= (flightPrice Beijing Krakow) 97)
     (flight Beijing Venice)
     (= (flightPrice Beijing Venice) 90)
     (flight Beijing Saint_Petersburg)
     (= (flightPrice Beijing Saint_Petersburg) 101)
     (flight Beijing Istanbul)
     (= (flightPrice Beijing Istanbul) 80)
     (flight Beijing Rome)
     (= (flightPrice Beijing Rome) 91)
     (flight Beijing Caracas)
     (= (flightPrice Beijing Caracas) 93)
     (flight Beijing Rio_de_Janeiro)
     (= (flightPrice Beijing Rio_de_Janeiro) 87)
     (flight Beijing La_Habana)
     (= (flightPrice Beijing La_Habana) 87)
     (flight Beijing Medellin)
     (= (flightPrice Beijing Medellin) 82)
     (flight Beijing Cali)
     (= (flightPrice Beijing Cali) 96)
     (flight Beijing Washington_DC)
     (= (flightPrice Beijing Washington_DC) 104)
     (flight Beijing New_York)
     (= (flightPrice Beijing New_York) 105)
     (flight Taiwan Melbourne)
     (= (flightPrice Taiwan Melbourne) 82)
     (flight Taiwan Sidney)
     (= (flightPrice Taiwan Sidney) 100)
     (flight Taiwan Wellington)
     (= (flightPrice Taiwan Wellington) 92)
     (flight Taiwan Beijing)
     (= (flightPrice Taiwan Beijing) 89)
     (flight Taiwan Tokio)
     (= (flightPrice Taiwan Tokio) 100)
     (flight Taiwan Nova_Dheli)
     (= (flightPrice Taiwan Nova_Dheli) 99)
     (flight Taiwan Paris)
     (= (flightPrice Taiwan Paris) 89)
     (flight Taiwan London)
     (= (flightPrice Taiwan London) 94)
     (flight Taiwan Berlin)
     (= (flightPrice Taiwan Berlin) 85)
     (flight Taiwan Dublin)
     (= (flightPrice Taiwan Dublin) 91)
     (flight Taiwan Edinburgh)
     (= (flightPrice Taiwan Edinburgh) 100)
     (flight Taiwan Moscow)
     (= (flightPrice Taiwan Moscow) 83)
     (flight Taiwan Krakow)
     (= (flightPrice Taiwan Krakow) 107)
     (flight Taiwan Venice)
     (= (flightPrice Taiwan Venice) 108)
     (flight Taiwan Saint_Petersburg)
     (= (flightPrice Taiwan Saint_Petersburg) 108)
     (flight Taiwan Istanbul)
     (= (flightPrice Taiwan Istanbul) 96)
     (flight Taiwan Rome)
     (= (flightPrice Taiwan Rome) 90)
     (flight Taiwan Caracas)
     (= (flightPrice Taiwan Caracas) 84)
     (flight Taiwan Rio_de_Janeiro)
     (= (flightPrice Taiwan Rio_de_Janeiro) 106)
     (flight Taiwan La_Habana)
     (= (flightPrice Taiwan La_Habana) 107)
     (flight Taiwan Medellin)
     (= (flightPrice Taiwan Medellin) 86)
     (flight Taiwan Cali)
     (= (flightPrice Taiwan Cali) 90)
     (flight Taiwan Washington_DC)
     (= (flightPrice Taiwan Washington_DC) 99)
     (flight Taiwan New_York)
     (= (flightPrice Taiwan New_York) 97)
     (flight Tokio Melbourne)
     (= (flightPrice Tokio Melbourne) 95)
     (flight Tokio Sidney)
     (= (flightPrice Tokio Sidney) 99)
     (flight Tokio Wellington)
     (= (flightPrice Tokio Wellington) 97)
     (flight Tokio Beijing)
     (= (flightPrice Tokio Beijing) 98)
     (flight Tokio Taiwan)
     (= (flightPrice Tokio Taiwan) 85)
     (flight Tokio Nova_Dheli)
     (= (flightPrice Tokio Nova_Dheli) 83)
     (flight Tokio Paris)
     (= (flightPrice Tokio Paris) 93)
     (flight Tokio London)
     (= (flightPrice Tokio London) 88)
     (flight Tokio Berlin)
     (= (flightPrice Tokio Berlin) 103)
     (flight Tokio Dublin)
     (= (flightPrice Tokio Dublin) 97)
     (flight Tokio Edinburgh)
     (= (flightPrice Tokio Edinburgh) 89)
     (flight Tokio Moscow)
     (= (flightPrice Tokio Moscow) 93)
     (flight Tokio Krakow)
     (= (flightPrice Tokio Krakow) 87)
     (flight Tokio Venice)
     (= (flightPrice Tokio Venice) 98)
     (flight Tokio Saint_Petersburg)
     (= (flightPrice Tokio Saint_Petersburg) 107)
     (flight Tokio Istanbul)
     (= (flightPrice Tokio Istanbul) 84)
     (flight Tokio Rome)
     (= (flightPrice Tokio Rome) 101)
     (flight Tokio Caracas)
     (= (flightPrice Tokio Caracas) 89)
     (flight Tokio Rio_de_Janeiro)
     (= (flightPrice Tokio Rio_de_Janeiro) 80)
     (flight Tokio La_Habana)
     (= (flightPrice Tokio La_Habana) 99)
     (flight Tokio Medellin)
     (= (flightPrice Tokio Medellin) 88)
     (flight Tokio Cali)
     (= (flightPrice Tokio Cali) 108)
     (flight Tokio Washington_DC)
     (= (flightPrice Tokio Washington_DC) 85)
     (flight Tokio New_York)
     (= (flightPrice Tokio New_York) 98)
     (flight Nova_Dheli Melbourne)
     (= (flightPrice Nova_Dheli Melbourne) 104)
     (flight Nova_Dheli Sidney)
     (= (flightPrice Nova_Dheli Sidney) 103)
     (flight Nova_Dheli Wellington)
     (= (flightPrice Nova_Dheli Wellington) 87)
     (flight Nova_Dheli Beijing)
     (= (flightPrice Nova_Dheli Beijing) 81)
     (flight Nova_Dheli Taiwan)
     (= (flightPrice Nova_Dheli Taiwan) 83)
     (flight Nova_Dheli Tokio)
     (= (flightPrice Nova_Dheli Tokio) 98)
     (flight Nova_Dheli Paris)
     (= (flightPrice Nova_Dheli Paris) 90)
     (flight Nova_Dheli London)
     (= (flightPrice Nova_Dheli London) 99)
     (flight Nova_Dheli Berlin)
     (= (flightPrice Nova_Dheli Berlin) 87)
     (flight Nova_Dheli Dublin)
     (= (flightPrice Nova_Dheli Dublin) 99)
     (flight Nova_Dheli Edinburgh)
     (= (flightPrice Nova_Dheli Edinburgh) 109)
     (flight Nova_Dheli Moscow)
     (= (flightPrice Nova_Dheli Moscow) 93)
     (flight Nova_Dheli Krakow)
     (= (flightPrice Nova_Dheli Krakow) 102)
     (flight Nova_Dheli Venice)
     (= (flightPrice Nova_Dheli Venice) 84)
     (flight Nova_Dheli Saint_Petersburg)
     (= (flightPrice Nova_Dheli Saint_Petersburg) 93)
     (flight Nova_Dheli Istanbul)
     (= (flightPrice Nova_Dheli Istanbul) 87)
     (flight Nova_Dheli Rome)
     (= (flightPrice Nova_Dheli Rome) 101)
     (flight Nova_Dheli Caracas)
     (= (flightPrice Nova_Dheli Caracas) 102)
     (flight Nova_Dheli Rio_de_Janeiro)
     (= (flightPrice Nova_Dheli Rio_de_Janeiro) 92)
     (flight Nova_Dheli La_Habana)
     (= (flightPrice Nova_Dheli La_Habana) 100)
     (flight Nova_Dheli Medellin)
     (= (flightPrice Nova_Dheli Medellin) 82)
     (flight Nova_Dheli Cali)
     (= (flightPrice Nova_Dheli Cali) 81)
     (flight Nova_Dheli Washington_DC)
     (= (flightPrice Nova_Dheli Washington_DC) 97)
     (flight Nova_Dheli New_York)
     (= (flightPrice Nova_Dheli New_York) 95)
     (flight Paris Melbourne)
     (= (flightPrice Paris Melbourne) 91)
     (flight Paris Sidney)
     (= (flightPrice Paris Sidney) 97)
     (flight Paris Wellington)
     (= (flightPrice Paris Wellington) 84)
     (flight Paris Beijing)
     (= (flightPrice Paris Beijing) 91)
     (flight Paris Taiwan)
     (= (flightPrice Paris Taiwan) 87)
     (flight Paris Tokio)
     (= (flightPrice Paris Tokio) 81)
     (flight Paris Nova_Dheli)
     (= (flightPrice Paris Nova_Dheli) 101)
     (flight Paris London)
     (= (flightPrice Paris London) 81)
     (flight Paris Berlin)
     (= (flightPrice Paris Berlin) 97)
     (flight Paris Dublin)
     (= (flightPrice Paris Dublin) 100)
     (flight Paris Edinburgh)
     (= (flightPrice Paris Edinburgh) 104)
     (flight Paris Moscow)
     (= (flightPrice Paris Moscow) 100)
     (flight Paris Krakow)
     (= (flightPrice Paris Krakow) 88)
     (flight Paris Venice)
     (= (flightPrice Paris Venice) 85)
     (flight Paris Saint_Petersburg)
     (= (flightPrice Paris Saint_Petersburg) 81)
     (flight Paris Istanbul)
     (= (flightPrice Paris Istanbul) 96)
     (flight Paris Rome)
     (= (flightPrice Paris Rome) 96)
     (flight Paris Caracas)
     (= (flightPrice Paris Caracas) 102)
     (flight Paris Rio_de_Janeiro)
     (= (flightPrice Paris Rio_de_Janeiro) 101)
     (flight Paris La_Habana)
     (= (flightPrice Paris La_Habana) 89)
     (flight Paris Medellin)
     (= (flightPrice Paris Medellin) 106)
     (flight Paris Cali)
     (= (flightPrice Paris Cali) 84)
     (flight Paris Washington_DC)
     (= (flightPrice Paris Washington_DC) 88)
     (flight Paris New_York)
     (= (flightPrice Paris New_York) 90)
     (flight London Melbourne)
     (= (flightPrice London Melbourne) 98)
     (flight London Sidney)
     (= (flightPrice London Sidney) 101)
     (flight London Wellington)
     (= (flightPrice London Wellington) 80)
     (flight London Beijing)
     (= (flightPrice London Beijing) 92)
     (flight London Taiwan)
     (= (flightPrice London Taiwan) 102)
     (flight London Tokio)
     (= (flightPrice London Tokio) 89)
     (flight London Nova_Dheli)
     (= (flightPrice London Nova_Dheli) 107)
     (flight London Paris)
     (= (flightPrice London Paris) 105)
     (flight London Berlin)
     (= (flightPrice London Berlin) 106)
     (flight London Dublin)
     (= (flightPrice London Dublin) 104)
     (flight London Edinburgh)
     (= (flightPrice London Edinburgh) 86)
     (flight London Moscow)
     (= (flightPrice London Moscow) 83)
     (flight London Krakow)
     (= (flightPrice London Krakow) 97)
     (flight London Venice)
     (= (flightPrice London Venice) 99)
     (flight London Saint_Petersburg)
     (= (flightPrice London Saint_Petersburg) 107)
     (flight London Istanbul)
     (= (flightPrice London Istanbul) 84)
     (flight London Rome)
     (= (flightPrice London Rome) 89)
     (flight London Caracas)
     (= (flightPrice London Caracas) 101)
     (flight London Rio_de_Janeiro)
     (= (flightPrice London Rio_de_Janeiro) 97)
     (flight London La_Habana)
     (= (flightPrice London La_Habana) 90)
     (flight London Medellin)
     (= (flightPrice London Medellin) 106)
     (flight London Cali)
     (= (flightPrice London Cali) 90)
     (flight London Washington_DC)
     (= (flightPrice London Washington_DC) 98)
     (flight London New_York)
     (= (flightPrice London New_York) 85)
     (flight Berlin Melbourne)
     (= (flightPrice Berlin Melbourne) 83)
     (flight Berlin Sidney)
     (= (flightPrice Berlin Sidney) 89)
     (flight Berlin Wellington)
     (= (flightPrice Berlin Wellington) 94)
     (flight Berlin Beijing)
     (= (flightPrice Berlin Beijing) 101)
     (flight Berlin Taiwan)
     (= (flightPrice Berlin Taiwan) 85)
     (flight Berlin Tokio)
     (= (flightPrice Berlin Tokio) 94)
     (flight Berlin Nova_Dheli)
     (= (flightPrice Berlin Nova_Dheli) 81)
     (flight Berlin Paris)
     (= (flightPrice Berlin Paris) 95)
     (flight Berlin London)
     (= (flightPrice Berlin London) 85)
     (flight Berlin Dublin)
     (= (flightPrice Berlin Dublin) 104)
     (flight Berlin Edinburgh)
     (= (flightPrice Berlin Edinburgh) 99)
     (flight Berlin Moscow)
     (= (flightPrice Berlin Moscow) 108)
     (flight Berlin Krakow)
     (= (flightPrice Berlin Krakow) 83)
     (flight Berlin Venice)
     (= (flightPrice Berlin Venice) 88)
     (flight Berlin Saint_Petersburg)
     (= (flightPrice Berlin Saint_Petersburg) 95)
     (flight Berlin Istanbul)
     (= (flightPrice Berlin Istanbul) 102)
     (flight Berlin Rome)
     (= (flightPrice Berlin Rome) 82)
     (flight Berlin Caracas)
     (= (flightPrice Berlin Caracas) 102)
     (flight Berlin Rio_de_Janeiro)
     (= (flightPrice Berlin Rio_de_Janeiro) 97)
     (flight Berlin La_Habana)
     (= (flightPrice Berlin La_Habana) 100)
     (flight Berlin Medellin)
     (= (flightPrice Berlin Medellin) 83)
     (flight Berlin Cali)
     (= (flightPrice Berlin Cali) 94)
     (flight Berlin Washington_DC)
     (= (flightPrice Berlin Washington_DC) 96)
     (flight Berlin New_York)
     (= (flightPrice Berlin New_York) 93)
     (flight Dublin Melbourne)
     (= (flightPrice Dublin Melbourne) 86)
     (flight Dublin Sidney)
     (= (flightPrice Dublin Sidney) 83)
     (flight Dublin Wellington)
     (= (flightPrice Dublin Wellington) 103)
     (flight Dublin Beijing)
     (= (flightPrice Dublin Beijing) 104)
     (flight Dublin Taiwan)
     (= (flightPrice Dublin Taiwan) 94)
     (flight Dublin Tokio)
     (= (flightPrice Dublin Tokio) 83)
     (flight Dublin Nova_Dheli)
     (= (flightPrice Dublin Nova_Dheli) 109)
     (flight Dublin Paris)
     (= (flightPrice Dublin Paris) 97)
     (flight Dublin London)
     (= (flightPrice Dublin London) 92)
     (flight Dublin Berlin)
     (= (flightPrice Dublin Berlin) 85)
     (flight Dublin Edinburgh)
     (= (flightPrice Dublin Edinburgh) 88)
     (flight Dublin Moscow)
     (= (flightPrice Dublin Moscow) 89)
     (flight Dublin Krakow)
     (= (flightPrice Dublin Krakow) 100)
     (flight Dublin Venice)
     (= (flightPrice Dublin Venice) 82)
     (flight Dublin Saint_Petersburg)
     (= (flightPrice Dublin Saint_Petersburg) 104)
     (flight Dublin Istanbul)
     (= (flightPrice Dublin Istanbul) 97)
     (flight Dublin Rome)
     (= (flightPrice Dublin Rome) 106)
     (flight Dublin Caracas)
     (= (flightPrice Dublin Caracas) 85)
     (flight Dublin Rio_de_Janeiro)
     (= (flightPrice Dublin Rio_de_Janeiro) 87)
     (flight Dublin La_Habana)
     (= (flightPrice Dublin La_Habana) 101)
     (flight Dublin Medellin)
     (= (flightPrice Dublin Medellin) 93)
     (flight Dublin Cali)
     (= (flightPrice Dublin Cali) 103)
     (flight Dublin Washington_DC)
     (= (flightPrice Dublin Washington_DC) 93)
     (flight Dublin New_York)
     (= (flightPrice Dublin New_York) 88)
     (flight Edinburgh Melbourne)
     (= (flightPrice Edinburgh Melbourne) 95)
     (flight Edinburgh Sidney)
     (= (flightPrice Edinburgh Sidney) 81)
     (flight Edinburgh Wellington)
     (= (flightPrice Edinburgh Wellington) 100)
     (flight Edinburgh Beijing)
     (= (flightPrice Edinburgh Beijing) 98)
     (flight Edinburgh Taiwan)
     (= (flightPrice Edinburgh Taiwan) 87)
     (flight Edinburgh Tokio)
     (= (flightPrice Edinburgh Tokio) 86)
     (flight Edinburgh Nova_Dheli)
     (= (flightPrice Edinburgh Nova_Dheli) 103)
     (flight Edinburgh Paris)
     (= (flightPrice Edinburgh Paris) 85)
     (flight Edinburgh London)
     (= (flightPrice Edinburgh London) 90)
     (flight Edinburgh Berlin)
     (= (flightPrice Edinburgh Berlin) 88)
     (flight Edinburgh Dublin)
     (= (flightPrice Edinburgh Dublin) 80)
     (flight Edinburgh Moscow)
     (= (flightPrice Edinburgh Moscow) 104)
     (flight Edinburgh Krakow)
     (= (flightPrice Edinburgh Krakow) 91)
     (flight Edinburgh Venice)
     (= (flightPrice Edinburgh Venice) 101)
     (flight Edinburgh Saint_Petersburg)
     (= (flightPrice Edinburgh Saint_Petersburg) 83)
     (flight Edinburgh Istanbul)
     (= (flightPrice Edinburgh Istanbul) 95)
     (flight Edinburgh Rome)
     (= (flightPrice Edinburgh Rome) 99)
     (flight Edinburgh Caracas)
     (= (flightPrice Edinburgh Caracas) 83)
     (flight Edinburgh Rio_de_Janeiro)
     (= (flightPrice Edinburgh Rio_de_Janeiro) 104)
     (flight Edinburgh La_Habana)
     (= (flightPrice Edinburgh La_Habana) 81)
     (flight Edinburgh Medellin)
     (= (flightPrice Edinburgh Medellin) 85)
     (flight Edinburgh Cali)
     (= (flightPrice Edinburgh Cali) 90)
     (flight Edinburgh Washington_DC)
     (= (flightPrice Edinburgh Washington_DC) 98)
     (flight Edinburgh New_York)
     (= (flightPrice Edinburgh New_York) 103)
     (flight Moscow Melbourne)
     (= (flightPrice Moscow Melbourne) 95)
     (flight Moscow Sidney)
     (= (flightPrice Moscow Sidney) 106)
     (flight Moscow Wellington)
     (= (flightPrice Moscow Wellington) 95)
     (flight Moscow Beijing)
     (= (flightPrice Moscow Beijing) 109)
     (flight Moscow Taiwan)
     (= (flightPrice Moscow Taiwan) 99)
     (flight Moscow Tokio)
     (= (flightPrice Moscow Tokio) 100)
     (flight Moscow Nova_Dheli)
     (= (flightPrice Moscow Nova_Dheli) 87)
     (flight Moscow Paris)
     (= (flightPrice Moscow Paris) 106)
     (flight Moscow London)
     (= (flightPrice Moscow London) 93)
     (flight Moscow Berlin)
     (= (flightPrice Moscow Berlin) 107)
     (flight Moscow Dublin)
     (= (flightPrice Moscow Dublin) 86)
     (flight Moscow Edinburgh)
     (= (flightPrice Moscow Edinburgh) 101)
     (flight Moscow Krakow)
     (= (flightPrice Moscow Krakow) 105)
     (flight Moscow Venice)
     (= (flightPrice Moscow Venice) 80)
     (flight Moscow Saint_Petersburg)
     (= (flightPrice Moscow Saint_Petersburg) 106)
     (flight Moscow Istanbul)
     (= (flightPrice Moscow Istanbul) 85)
     (flight Moscow Rome)
     (= (flightPrice Moscow Rome) 80)
     (flight Moscow Caracas)
     (= (flightPrice Moscow Caracas) 98)
     (flight Moscow Rio_de_Janeiro)
     (= (flightPrice Moscow Rio_de_Janeiro) 101)
     (flight Moscow La_Habana)
     (= (flightPrice Moscow La_Habana) 92)
     (flight Moscow Medellin)
     (= (flightPrice Moscow Medellin) 82)
     (flight Moscow Cali)
     (= (flightPrice Moscow Cali) 96)
     (flight Moscow Washington_DC)
     (= (flightPrice Moscow Washington_DC) 99)
     (flight Moscow New_York)
     (= (flightPrice Moscow New_York) 101)
     (flight Krakow Melbourne)
     (= (flightPrice Krakow Melbourne) 100)
     (flight Krakow Sidney)
     (= (flightPrice Krakow Sidney) 94)
     (flight Krakow Wellington)
     (= (flightPrice Krakow Wellington) 102)
     (flight Krakow Beijing)
     (= (flightPrice Krakow Beijing) 97)
     (flight Krakow Taiwan)
     (= (flightPrice Krakow Taiwan) 104)
     (flight Krakow Tokio)
     (= (flightPrice Krakow Tokio) 90)
     (flight Krakow Nova_Dheli)
     (= (flightPrice Krakow Nova_Dheli) 83)
     (flight Krakow Paris)
     (= (flightPrice Krakow Paris) 82)
     (flight Krakow London)
     (= (flightPrice Krakow London) 108)
     (flight Krakow Berlin)
     (= (flightPrice Krakow Berlin) 90)
     (flight Krakow Dublin)
     (= (flightPrice Krakow Dublin) 103)
     (flight Krakow Edinburgh)
     (= (flightPrice Krakow Edinburgh) 97)
     (flight Krakow Moscow)
     (= (flightPrice Krakow Moscow) 80)
     (flight Krakow Venice)
     (= (flightPrice Krakow Venice) 80)
     (flight Krakow Saint_Petersburg)
     (= (flightPrice Krakow Saint_Petersburg) 93)
     (flight Krakow Istanbul)
     (= (flightPrice Krakow Istanbul) 94)
     (flight Krakow Rome)
     (= (flightPrice Krakow Rome) 99)
     (flight Krakow Caracas)
     (= (flightPrice Krakow Caracas) 92)
     (flight Krakow Rio_de_Janeiro)
     (= (flightPrice Krakow Rio_de_Janeiro) 107)
     (flight Krakow La_Habana)
     (= (flightPrice Krakow La_Habana) 94)
     (flight Krakow Medellin)
     (= (flightPrice Krakow Medellin) 92)
     (flight Krakow Cali)
     (= (flightPrice Krakow Cali) 95)
     (flight Krakow Washington_DC)
     (= (flightPrice Krakow Washington_DC) 92)
     (flight Krakow New_York)
     (= (flightPrice Krakow New_York) 84)
     (flight Venice Melbourne)
     (= (flightPrice Venice Melbourne) 84)
     (flight Venice Sidney)
     (= (flightPrice Venice Sidney) 83)
     (flight Venice Wellington)
     (= (flightPrice Venice Wellington) 88)
     (flight Venice Beijing)
     (= (flightPrice Venice Beijing) 86)
     (flight Venice Taiwan)
     (= (flightPrice Venice Taiwan) 100)
     (flight Venice Tokio)
     (= (flightPrice Venice Tokio) 108)
     (flight Venice Nova_Dheli)
     (= (flightPrice Venice Nova_Dheli) 99)
     (flight Venice Paris)
     (= (flightPrice Venice Paris) 82)
     (flight Venice London)
     (= (flightPrice Venice London) 92)
     (flight Venice Berlin)
     (= (flightPrice Venice Berlin) 83)
     (flight Venice Dublin)
     (= (flightPrice Venice Dublin) 91)
     (flight Venice Edinburgh)
     (= (flightPrice Venice Edinburgh) 108)
     (flight Venice Moscow)
     (= (flightPrice Venice Moscow) 93)
     (flight Venice Krakow)
     (= (flightPrice Venice Krakow) 94)
     (flight Venice Saint_Petersburg)
     (= (flightPrice Venice Saint_Petersburg) 102)
     (flight Venice Istanbul)
     (= (flightPrice Venice Istanbul) 92)
     (flight Venice Rome)
     (= (flightPrice Venice Rome) 104)
     (flight Venice Caracas)
     (= (flightPrice Venice Caracas) 95)
     (flight Venice Rio_de_Janeiro)
     (= (flightPrice Venice Rio_de_Janeiro) 101)
     (flight Venice La_Habana)
     (= (flightPrice Venice La_Habana) 97)
     (flight Venice Medellin)
     (= (flightPrice Venice Medellin) 95)
     (flight Venice Cali)
     (= (flightPrice Venice Cali) 107)
     (flight Venice Washington_DC)
     (= (flightPrice Venice Washington_DC) 81)
     (flight Venice New_York)
     (= (flightPrice Venice New_York) 106)
     (flight Saint_Petersburg Melbourne)
     (= (flightPrice Saint_Petersburg Melbourne) 89)
     (flight Saint_Petersburg Sidney)
     (= (flightPrice Saint_Petersburg Sidney) 108)
     (flight Saint_Petersburg Wellington)
     (= (flightPrice Saint_Petersburg Wellington) 91)
     (flight Saint_Petersburg Beijing)
     (= (flightPrice Saint_Petersburg Beijing) 93)
     (flight Saint_Petersburg Taiwan)
     (= (flightPrice Saint_Petersburg Taiwan) 93)
     (flight Saint_Petersburg Tokio)
     (= (flightPrice Saint_Petersburg Tokio) 103)
     (flight Saint_Petersburg Nova_Dheli)
     (= (flightPrice Saint_Petersburg Nova_Dheli) 97)
     (flight Saint_Petersburg Paris)
     (= (flightPrice Saint_Petersburg Paris) 89)
     (flight Saint_Petersburg London)
     (= (flightPrice Saint_Petersburg London) 98)
     (flight Saint_Petersburg Berlin)
     (= (flightPrice Saint_Petersburg Berlin) 106)
     (flight Saint_Petersburg Dublin)
     (= (flightPrice Saint_Petersburg Dublin) 87)
     (flight Saint_Petersburg Edinburgh)
     (= (flightPrice Saint_Petersburg Edinburgh) 80)
     (flight Saint_Petersburg Moscow)
     (= (flightPrice Saint_Petersburg Moscow) 104)
     (flight Saint_Petersburg Krakow)
     (= (flightPrice Saint_Petersburg Krakow) 98)
     (flight Saint_Petersburg Venice)
     (= (flightPrice Saint_Petersburg Venice) 104)
     (flight Saint_Petersburg Istanbul)
     (= (flightPrice Saint_Petersburg Istanbul) 108)
     (flight Saint_Petersburg Rome)
     (= (flightPrice Saint_Petersburg Rome) 101)
     (flight Saint_Petersburg Caracas)
     (= (flightPrice Saint_Petersburg Caracas) 86)
     (flight Saint_Petersburg Rio_de_Janeiro)
     (= (flightPrice Saint_Petersburg Rio_de_Janeiro) 98)
     (flight Saint_Petersburg La_Habana)
     (= (flightPrice Saint_Petersburg La_Habana) 85)
     (flight Saint_Petersburg Medellin)
     (= (flightPrice Saint_Petersburg Medellin) 92)
     (flight Saint_Petersburg Cali)
     (= (flightPrice Saint_Petersburg Cali) 91)
     (flight Saint_Petersburg Washington_DC)
     (= (flightPrice Saint_Petersburg Washington_DC) 89)
     (flight Saint_Petersburg New_York)
     (= (flightPrice Saint_Petersburg New_York) 109)
     (flight Istanbul Melbourne)
     (= (flightPrice Istanbul Melbourne) 106)
     (flight Istanbul Sidney)
     (= (flightPrice Istanbul Sidney) 80)
     (flight Istanbul Wellington)
     (= (flightPrice Istanbul Wellington) 96)
     (flight Istanbul Beijing)
     (= (flightPrice Istanbul Beijing) 84)
     (flight Istanbul Taiwan)
     (= (flightPrice Istanbul Taiwan) 99)
     (flight Istanbul Tokio)
     (= (flightPrice Istanbul Tokio) 89)
     (flight Istanbul Nova_Dheli)
     (= (flightPrice Istanbul Nova_Dheli) 80)
     (flight Istanbul Paris)
     (= (flightPrice Istanbul Paris) 108)
     (flight Istanbul London)
     (= (flightPrice Istanbul London) 109)
     (flight Istanbul Berlin)
     (= (flightPrice Istanbul Berlin) 83)
     (flight Istanbul Dublin)
     (= (flightPrice Istanbul Dublin) 91)
     (flight Istanbul Edinburgh)
     (= (flightPrice Istanbul Edinburgh) 84)
     (flight Istanbul Moscow)
     (= (flightPrice Istanbul Moscow) 98)
     (flight Istanbul Krakow)
     (= (flightPrice Istanbul Krakow) 109)
     (flight Istanbul Venice)
     (= (flightPrice Istanbul Venice) 86)
     (flight Istanbul Saint_Petersburg)
     (= (flightPrice Istanbul Saint_Petersburg) 87)
     (flight Istanbul Rome)
     (= (flightPrice Istanbul Rome) 97)
     (flight Istanbul Caracas)
     (= (flightPrice Istanbul Caracas) 93)
     (flight Istanbul Rio_de_Janeiro)
     (= (flightPrice Istanbul Rio_de_Janeiro) 87)
     (flight Istanbul La_Habana)
     (= (flightPrice Istanbul La_Habana) 91)
     (flight Istanbul Medellin)
     (= (flightPrice Istanbul Medellin) 82)
     (flight Istanbul Cali)
     (= (flightPrice Istanbul Cali) 82)
     (flight Istanbul Washington_DC)
     (= (flightPrice Istanbul Washington_DC) 81)
     (flight Istanbul New_York)
     (= (flightPrice Istanbul New_York) 95)
     (flight Rome Melbourne)
     (= (flightPrice Rome Melbourne) 80)
     (flight Rome Sidney)
     (= (flightPrice Rome Sidney) 99)
     (flight Rome Wellington)
     (= (flightPrice Rome Wellington) 100)
     (flight Rome Beijing)
     (= (flightPrice Rome Beijing) 84)
     (flight Rome Taiwan)
     (= (flightPrice Rome Taiwan) 80)
     (flight Rome Tokio)
     (= (flightPrice Rome Tokio) 101)
     (flight Rome Nova_Dheli)
     (= (flightPrice Rome Nova_Dheli) 83)
     (flight Rome Paris)
     (= (flightPrice Rome Paris) 107)
     (flight Rome London)
     (= (flightPrice Rome London) 94)
     (flight Rome Berlin)
     (= (flightPrice Rome Berlin) 91)
     (flight Rome Dublin)
     (= (flightPrice Rome Dublin) 81)
     (flight Rome Edinburgh)
     (= (flightPrice Rome Edinburgh) 83)
     (flight Rome Moscow)
     (= (flightPrice Rome Moscow) 100)
     (flight Rome Krakow)
     (= (flightPrice Rome Krakow) 103)
     (flight Rome Venice)
     (= (flightPrice Rome Venice) 82)
     (flight Rome Saint_Petersburg)
     (= (flightPrice Rome Saint_Petersburg) 91)
     (flight Rome Istanbul)
     (= (flightPrice Rome Istanbul) 107)
     (flight Rome Caracas)
     (= (flightPrice Rome Caracas) 85)
     (flight Rome Rio_de_Janeiro)
     (= (flightPrice Rome Rio_de_Janeiro) 96)
     (flight Rome La_Habana)
     (= (flightPrice Rome La_Habana) 95)
     (flight Rome Medellin)
     (= (flightPrice Rome Medellin) 84)
     (flight Rome Cali)
     (= (flightPrice Rome Cali) 102)
     (flight Rome Washington_DC)
     (= (flightPrice Rome Washington_DC) 102)
     (flight Rome New_York)
     (= (flightPrice Rome New_York) 101)
     (flight Caracas Melbourne)
     (= (flightPrice Caracas Melbourne) 107)
     (flight Caracas Sidney)
     (= (flightPrice Caracas Sidney) 102)
     (flight Caracas Wellington)
     (= (flightPrice Caracas Wellington) 104)
     (flight Caracas Beijing)
     (= (flightPrice Caracas Beijing) 101)
     (flight Caracas Taiwan)
     (= (flightPrice Caracas Taiwan) 96)
     (flight Caracas Tokio)
     (= (flightPrice Caracas Tokio) 105)
     (flight Caracas Nova_Dheli)
     (= (flightPrice Caracas Nova_Dheli) 87)
     (flight Caracas Paris)
     (= (flightPrice Caracas Paris) 88)
     (flight Caracas London)
     (= (flightPrice Caracas London) 95)
     (flight Caracas Berlin)
     (= (flightPrice Caracas Berlin) 99)
     (flight Caracas Dublin)
     (= (flightPrice Caracas Dublin) 92)
     (flight Caracas Edinburgh)
     (= (flightPrice Caracas Edinburgh) 87)
     (flight Caracas Moscow)
     (= (flightPrice Caracas Moscow) 83)
     (flight Caracas Krakow)
     (= (flightPrice Caracas Krakow) 96)
     (flight Caracas Venice)
     (= (flightPrice Caracas Venice) 84)
     (flight Caracas Saint_Petersburg)
     (= (flightPrice Caracas Saint_Petersburg) 97)
     (flight Caracas Istanbul)
     (= (flightPrice Caracas Istanbul) 99)
     (flight Caracas Rome)
     (= (flightPrice Caracas Rome) 107)
     (flight Caracas Rio_de_Janeiro)
     (= (flightPrice Caracas Rio_de_Janeiro) 92)
     (flight Caracas La_Habana)
     (= (flightPrice Caracas La_Habana) 82)
     (flight Caracas Medellin)
     (= (flightPrice Caracas Medellin) 101)
     (flight Caracas Cali)
     (= (flightPrice Caracas Cali) 86)
     (flight Caracas Washington_DC)
     (= (flightPrice Caracas Washington_DC) 93)
     (flight Caracas New_York)
     (= (flightPrice Caracas New_York) 90)
     (flight Rio_de_Janeiro Melbourne)
     (= (flightPrice Rio_de_Janeiro Melbourne) 92)
     (flight Rio_de_Janeiro Sidney)
     (= (flightPrice Rio_de_Janeiro Sidney) 101)
     (flight Rio_de_Janeiro Wellington)
     (= (flightPrice Rio_de_Janeiro Wellington) 105)
     (flight Rio_de_Janeiro Beijing)
     (= (flightPrice Rio_de_Janeiro Beijing) 96)
     (flight Rio_de_Janeiro Taiwan)
     (= (flightPrice Rio_de_Janeiro Taiwan) 85)
     (flight Rio_de_Janeiro Tokio)
     (= (flightPrice Rio_de_Janeiro Tokio) 90)
     (flight Rio_de_Janeiro Nova_Dheli)
     (= (flightPrice Rio_de_Janeiro Nova_Dheli) 80)
     (flight Rio_de_Janeiro Paris)
     (= (flightPrice Rio_de_Janeiro Paris) 83)
     (flight Rio_de_Janeiro London)
     (= (flightPrice Rio_de_Janeiro London) 104)
     (flight Rio_de_Janeiro Berlin)
     (= (flightPrice Rio_de_Janeiro Berlin) 96)
     (flight Rio_de_Janeiro Dublin)
     (= (flightPrice Rio_de_Janeiro Dublin) 96)
     (flight Rio_de_Janeiro Edinburgh)
     (= (flightPrice Rio_de_Janeiro Edinburgh) 90)
     (flight Rio_de_Janeiro Moscow)
     (= (flightPrice Rio_de_Janeiro Moscow) 92)
     (flight Rio_de_Janeiro Krakow)
     (= (flightPrice Rio_de_Janeiro Krakow) 95)
     (flight Rio_de_Janeiro Venice)
     (= (flightPrice Rio_de_Janeiro Venice) 98)
     (flight Rio_de_Janeiro Saint_Petersburg)
     (= (flightPrice Rio_de_Janeiro Saint_Petersburg) 99)
     (flight Rio_de_Janeiro Istanbul)
     (= (flightPrice Rio_de_Janeiro Istanbul) 85)
     (flight Rio_de_Janeiro Rome)
     (= (flightPrice Rio_de_Janeiro Rome) 80)
     (flight Rio_de_Janeiro Caracas)
     (= (flightPrice Rio_de_Janeiro Caracas) 106)
     (flight Rio_de_Janeiro La_Habana)
     (= (flightPrice Rio_de_Janeiro La_Habana) 80)
     (flight Rio_de_Janeiro Medellin)
     (= (flightPrice Rio_de_Janeiro Medellin) 88)
     (flight Rio_de_Janeiro Cali)
     (= (flightPrice Rio_de_Janeiro Cali) 103)
     (flight Rio_de_Janeiro Washington_DC)
     (= (flightPrice Rio_de_Janeiro Washington_DC) 97)
     (flight Rio_de_Janeiro New_York)
     (= (flightPrice Rio_de_Janeiro New_York) 108)
     (flight La_Habana Melbourne)
     (= (flightPrice La_Habana Melbourne) 92)
     (flight La_Habana Sidney)
     (= (flightPrice La_Habana Sidney) 101)
     (flight La_Habana Wellington)
     (= (flightPrice La_Habana Wellington) 80)
     (flight La_Habana Beijing)
     (= (flightPrice La_Habana Beijing) 105)
     (flight La_Habana Taiwan)
     (= (flightPrice La_Habana Taiwan) 108)
     (flight La_Habana Tokio)
     (= (flightPrice La_Habana Tokio) 85)
     (flight La_Habana Nova_Dheli)
     (= (flightPrice La_Habana Nova_Dheli) 85)
     (flight La_Habana Paris)
     (= (flightPrice La_Habana Paris) 90)
     (flight La_Habana London)
     (= (flightPrice La_Habana London) 107)
     (flight La_Habana Berlin)
     (= (flightPrice La_Habana Berlin) 103)
     (flight La_Habana Dublin)
     (= (flightPrice La_Habana Dublin) 98)
     (flight La_Habana Edinburgh)
     (= (flightPrice La_Habana Edinburgh) 82)
     (flight La_Habana Moscow)
     (= (flightPrice La_Habana Moscow) 83)
     (flight La_Habana Krakow)
     (= (flightPrice La_Habana Krakow) 90)
     (flight La_Habana Venice)
     (= (flightPrice La_Habana Venice) 107)
     (flight La_Habana Saint_Petersburg)
     (= (flightPrice La_Habana Saint_Petersburg) 107)
     (flight La_Habana Istanbul)
     (= (flightPrice La_Habana Istanbul) 107)
     (flight La_Habana Rome)
     (= (flightPrice La_Habana Rome) 86)
     (flight La_Habana Caracas)
     (= (flightPrice La_Habana Caracas) 109)
     (flight La_Habana Rio_de_Janeiro)
     (= (flightPrice La_Habana Rio_de_Janeiro) 81)
     (flight La_Habana Medellin)
     (= (flightPrice La_Habana Medellin) 101)
     (flight La_Habana Cali)
     (= (flightPrice La_Habana Cali) 89)
     (flight La_Habana Washington_DC)
     (= (flightPrice La_Habana Washington_DC) 100)
     (flight La_Habana New_York)
     (= (flightPrice La_Habana New_York) 98)
     (flight Medellin Melbourne)
     (= (flightPrice Medellin Melbourne) 89)
     (flight Medellin Sidney)
     (= (flightPrice Medellin Sidney) 88)
     (flight Medellin Wellington)
     (= (flightPrice Medellin Wellington) 98)
     (flight Medellin Beijing)
     (= (flightPrice Medellin Beijing) 90)
     (flight Medellin Taiwan)
     (= (flightPrice Medellin Taiwan) 103)
     (flight Medellin Tokio)
     (= (flightPrice Medellin Tokio) 107)
     (flight Medellin Nova_Dheli)
     (= (flightPrice Medellin Nova_Dheli) 80)
     (flight Medellin Paris)
     (= (flightPrice Medellin Paris) 86)
     (flight Medellin London)
     (= (flightPrice Medellin London) 99)
     (flight Medellin Berlin)
     (= (flightPrice Medellin Berlin) 102)
     (flight Medellin Dublin)
     (= (flightPrice Medellin Dublin) 81)
     (flight Medellin Edinburgh)
     (= (flightPrice Medellin Edinburgh) 97)
     (flight Medellin Moscow)
     (= (flightPrice Medellin Moscow) 107)
     (flight Medellin Krakow)
     (= (flightPrice Medellin Krakow) 109)
     (flight Medellin Venice)
     (= (flightPrice Medellin Venice) 107)
     (flight Medellin Saint_Petersburg)
     (= (flightPrice Medellin Saint_Petersburg) 96)
     (flight Medellin Istanbul)
     (= (flightPrice Medellin Istanbul) 102)
     (flight Medellin Rome)
     (= (flightPrice Medellin Rome) 87)
     (flight Medellin Caracas)
     (= (flightPrice Medellin Caracas) 91)
     (flight Medellin Rio_de_Janeiro)
     (= (flightPrice Medellin Rio_de_Janeiro) 105)
     (flight Medellin La_Habana)
     (= (flightPrice Medellin La_Habana) 98)
     (flight Medellin Cali)
     (= (flightPrice Medellin Cali) 88)
     (flight Medellin Washington_DC)
     (= (flightPrice Medellin Washington_DC) 94)
     (flight Medellin New_York)
     (= (flightPrice Medellin New_York) 95)
     (flight Cali Melbourne)
     (= (flightPrice Cali Melbourne) 86)
     (flight Cali Sidney)
     (= (flightPrice Cali Sidney) 85)
     (flight Cali Wellington)
     (= (flightPrice Cali Wellington) 96)
     (flight Cali Beijing)
     (= (flightPrice Cali Beijing) 108)
     (flight Cali Taiwan)
     (= (flightPrice Cali Taiwan) 94)
     (flight Cali Tokio)
     (= (flightPrice Cali Tokio) 108)
     (flight Cali Nova_Dheli)
     (= (flightPrice Cali Nova_Dheli) 88)
     (flight Cali Paris)
     (= (flightPrice Cali Paris) 103)
     (flight Cali London)
     (= (flightPrice Cali London) 108)
     (flight Cali Berlin)
     (= (flightPrice Cali Berlin) 107)
     (flight Cali Dublin)
     (= (flightPrice Cali Dublin) 105)
     (flight Cali Edinburgh)
     (= (flightPrice Cali Edinburgh) 102)
     (flight Cali Moscow)
     (= (flightPrice Cali Moscow) 104)
     (flight Cali Krakow)
     (= (flightPrice Cali Krakow) 105)
     (flight Cali Venice)
     (= (flightPrice Cali Venice) 100)
     (flight Cali Saint_Petersburg)
     (= (flightPrice Cali Saint_Petersburg) 85)
     (flight Cali Istanbul)
     (= (flightPrice Cali Istanbul) 97)
     (flight Cali Rome)
     (= (flightPrice Cali Rome) 93)
     (flight Cali Caracas)
     (= (flightPrice Cali Caracas) 102)
     (flight Cali Rio_de_Janeiro)
     (= (flightPrice Cali Rio_de_Janeiro) 87)
     (flight Cali La_Habana)
     (= (flightPrice Cali La_Habana) 92)
     (flight Cali Medellin)
     (= (flightPrice Cali Medellin) 91)
     (flight Cali Washington_DC)
     (= (flightPrice Cali Washington_DC) 103)
     (flight Cali New_York)
     (= (flightPrice Cali New_York) 84)
     (flight Washington_DC Melbourne)
     (= (flightPrice Washington_DC Melbourne) 99)
     (flight Washington_DC Sidney)
     (= (flightPrice Washington_DC Sidney) 84)
     (flight Washington_DC Wellington)
     (= (flightPrice Washington_DC Wellington) 101)
     (flight Washington_DC Beijing)
     (= (flightPrice Washington_DC Beijing) 109)
     (flight Washington_DC Taiwan)
     (= (flightPrice Washington_DC Taiwan) 85)
     (flight Washington_DC Tokio)
     (= (flightPrice Washington_DC Tokio) 107)
     (flight Washington_DC Nova_Dheli)
     (= (flightPrice Washington_DC Nova_Dheli) 94)
     (flight Washington_DC Paris)
     (= (flightPrice Washington_DC Paris) 91)
     (flight Washington_DC London)
     (= (flightPrice Washington_DC London) 82)
     (flight Washington_DC Berlin)
     (= (flightPrice Washington_DC Berlin) 102)
     (flight Washington_DC Dublin)
     (= (flightPrice Washington_DC Dublin) 81)
     (flight Washington_DC Edinburgh)
     (= (flightPrice Washington_DC Edinburgh) 96)
     (flight Washington_DC Moscow)
     (= (flightPrice Washington_DC Moscow) 92)
     (flight Washington_DC Krakow)
     (= (flightPrice Washington_DC Krakow) 90)
     (flight Washington_DC Venice)
     (= (flightPrice Washington_DC Venice) 82)
     (flight Washington_DC Saint_Petersburg)
     (= (flightPrice Washington_DC Saint_Petersburg) 82)
     (flight Washington_DC Istanbul)
     (= (flightPrice Washington_DC Istanbul) 109)
     (flight Washington_DC Rome)
     (= (flightPrice Washington_DC Rome) 107)
     (flight Washington_DC Caracas)
     (= (flightPrice Washington_DC Caracas) 104)
     (flight Washington_DC Rio_de_Janeiro)
     (= (flightPrice Washington_DC Rio_de_Janeiro) 103)
     (flight Washington_DC La_Habana)
     (= (flightPrice Washington_DC La_Habana) 95)
     (flight Washington_DC Medellin)
     (= (flightPrice Washington_DC Medellin) 86)
     (flight Washington_DC Cali)
     (= (flightPrice Washington_DC Cali) 101)
     (flight Washington_DC New_York)
     (= (flightPrice Washington_DC New_York) 104)
     (flight New_York Melbourne)
     (= (flightPrice New_York Melbourne) 100)
     (flight New_York Sidney)
     (= (flightPrice New_York Sidney) 93)
     (flight New_York Wellington)
     (= (flightPrice New_York Wellington) 81)
     (flight New_York Beijing)
     (= (flightPrice New_York Beijing) 82)
     (flight New_York Taiwan)
     (= (flightPrice New_York Taiwan) 97)
     (flight New_York Tokio)
     (= (flightPrice New_York Tokio) 97)
     (flight New_York Nova_Dheli)
     (= (flightPrice New_York Nova_Dheli) 109)
     (flight New_York Paris)
     (= (flightPrice New_York Paris) 108)
     (flight New_York London)
     (= (flightPrice New_York London) 101)
     (flight New_York Berlin)
     (= (flightPrice New_York Berlin) 100)
     (flight New_York Dublin)
     (= (flightPrice New_York Dublin) 107)
     (flight New_York Edinburgh)
     (= (flightPrice New_York Edinburgh) 106)
     (flight New_York Moscow)
     (= (flightPrice New_York Moscow) 90)
     (flight New_York Krakow)
     (= (flightPrice New_York Krakow) 91)
     (flight New_York Venice)
     (= (flightPrice New_York Venice) 80)
     (flight New_York Saint_Petersburg)
     (= (flightPrice New_York Saint_Petersburg) 92)
     (flight New_York Istanbul)
     (= (flightPrice New_York Istanbul) 105)
     (flight New_York Rome)
     (= (flightPrice New_York Rome) 81)
     (flight New_York Caracas)
     (= (flightPrice New_York Caracas) 109)
     (flight New_York Rio_de_Janeiro)
     (= (flightPrice New_York Rio_de_Janeiro) 87)
     (flight New_York La_Habana)
     (= (flightPrice New_York La_Habana) 91)
     (flight New_York Medellin)
     (= (flightPrice New_York Medellin) 103)
     (flight New_York Cali)
     (= (flightPrice New_York Cali) 81)
     (flight New_York Washington_DC)
     (= (flightPrice New_York Washington_DC) 82)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Melbourne)
     (inCity Hotel_Emperor_2 Melbourne)
     (inCity Residence_Sky_3 Melbourne)
     (inCity Hostel_Delphin_4 Melbourne)
     (inCity Residence_Single_Land_5 Sidney)
     (inCity Resort_Lollipop_6 Sidney)
     (inCity Hostel_Emperor_7 Sidney)
     (inCity Hostel_Lollipop_8 Sidney)
     (inCity Hostel_Single_Land_9 Sidney)
     (inCity Apartments_Paradise_10 Wellington)
     (inCity Resort_Arabiga_11 Wellington)
     (inCity Hotel_Single_Land_12 Wellington)
     (inCity Apartments_Single_Land_13 Wellington)
     (inCity Hotel_Arabiga_14 Wellington)
     (inCity Residence_Delphin_15 Beijing)
     (inCity Apartments_Single_Land_16 Beijing)
     (inCity Residence_Delphin_17 Beijing)
     (inCity Hostel_Emperor_18 Beijing)
     (inCity Residence_Paradise_19 Beijing)
     (inCity Apartments_Delphin_20 Taiwan)
     (inCity Resort_Paradise_21 Taiwan)
     (inCity Residence_Relax_22 Taiwan)
     (inCity Resort_NH_23 Taiwan)
     (inCity Hotel_Chill_24 Taiwan)
     (inCity Hostel_Emperor_25 Tokio)
     (inCity Hotel_Paradise_26 Tokio)
     (inCity Apartments_Sky_27 Tokio)
     (inCity Hotel_Single_Land_28 Tokio)
     (inCity Hostel_Sky_29 Tokio)
     (inCity Hotel_Chill_30 Nova_Dheli)
     (inCity Residence_Relax_31 Nova_Dheli)
     (inCity Hotel_Sky_32 Nova_Dheli)
     (inCity Resort_Sky_33 Nova_Dheli)
     (inCity Residence_Emperor_34 Nova_Dheli)
     (inCity Hotel_Relax_35 Paris)
     (inCity Hotel_Single_Land_36 Paris)
     (inCity Residence_Relax_37 Paris)
     (inCity Resort_Relax_38 Paris)
     (inCity Hotel_Emperor_39 Paris)
     (inCity Apartments_Arabiga_40 London)
     (inCity Apartments_Sky_41 London)
     (inCity Resort_NH_42 London)
     (inCity Hostel_Emperor_43 London)
     (inCity Resort_Relax_44 London)
     (inCity Hotel_Single_Land_45 Berlin)
     (inCity Apartments_Sky_46 Berlin)
     (inCity Residence_Delphin_47 Berlin)
     (inCity Hostel_Sky_48 Berlin)
     (inCity Resort_Relax_49 Berlin)
     (inCity Hotel_Chill_50 Dublin)
     (inCity Apartments_Relax_51 Dublin)
     (inCity Hostel_Arabiga_52 Dublin)
     (inCity Residence_Arabiga_53 Dublin)
     (inCity Residence_Arabiga_54 Dublin)
     (inCity Hostel_Single_Land_55 Edinburgh)
     (inCity Hotel_Paradise_56 Edinburgh)
     (inCity Hostel_Sky_57 Edinburgh)
     (inCity Resort_Chill_58 Edinburgh)
     (inCity Resort_Relax_59 Edinburgh)
     (inCity Resort_Lollipop_60 Moscow)
     (inCity Residence_Paradise_61 Moscow)
     (inCity Hostel_Arabiga_62 Moscow)
     (inCity Hotel_Paradise_63 Moscow)
     (inCity Residence_Delphin_64 Moscow)
     (inCity Hostel_Arabiga_65 Krakow)
     (inCity Apartments_Arabiga_66 Krakow)
     (inCity Hotel_Sky_67 Krakow)
     (inCity Apartments_Sky_68 Krakow)
     (inCity Resort_Delphin_69 Krakow)
     (inCity Hostel_NH_70 Venice)
     (inCity Resort_Single_Land_71 Venice)
     (inCity Resort_Emperor_72 Venice)
     (inCity Apartments_Lollipop_73 Venice)
     (inCity Hotel_NH_74 Venice)
     (inCity Resort_Lollipop_75 Saint_Petersburg)
     (inCity Apartments_Sky_76 Saint_Petersburg)
     (inCity Hotel_NH_77 Saint_Petersburg)
     (inCity Hostel_Sky_78 Saint_Petersburg)
     (inCity Hotel_Paradise_79 Saint_Petersburg)
     (inCity Apartments_Delphin_80 Istanbul)
     (inCity Apartments_Relax_81 Istanbul)
     (inCity Hotel_Paradise_82 Istanbul)
     (inCity Hotel_Emperor_83 Istanbul)
     (inCity Resort_Relax_84 Istanbul)
     (inCity Resort_Relax_85 Rome)
     (inCity Hostel_Arabiga_86 Rome)
     (inCity Hostel_Emperor_87 Rome)
     (inCity Hotel_Arabiga_88 Rome)
     (inCity Hostel_Delphin_89 Rome)
     (inCity Hostel_Single_Land_90 Caracas)
     (inCity Apartments_Arabiga_91 Caracas)
     (inCity Residence_Chill_92 Caracas)
     (inCity Hostel_Relax_93 Caracas)
     (inCity Hotel_NH_94 Caracas)
     (inCity Residence_Delphin_95 Rio_de_Janeiro)
     (inCity Apartments_Chill_96 Rio_de_Janeiro)
     (inCity Apartments_NH_97 Rio_de_Janeiro)
     (inCity Hostel_Emperor_98 Rio_de_Janeiro)
     (inCity Resort_NH_99 Rio_de_Janeiro)
     (inCity Resort_Sky_100 La_Habana)
     (inCity Apartments_Emperor_101 La_Habana)
     (inCity Apartments_Emperor_102 La_Habana)
     (inCity Hotel_Sky_103 La_Habana)
     (inCity Apartments_Relax_104 La_Habana)
     (inCity Apartments_NH_105 Medellin)
     (inCity Residence_Delphin_106 Medellin)
     (inCity Hostel_Arabiga_107 Medellin)
     (inCity Apartments_Relax_108 Medellin)
     (inCity Apartments_Lollipop_109 Medellin)
     (inCity Resort_Lollipop_110 Cali)
     (inCity Hotel_Single_Land_111 Cali)
     (inCity Hotel_Relax_112 Cali)
     (inCity Resort_Chill_113 Cali)
     (inCity Hostel_Relax_114 Cali)
     (inCity Residence_Delphin_115 Washington_DC)
     (inCity Resort_Single_Land_116 Washington_DC)
     (inCity Residence_Arabiga_117 Washington_DC)
     (inCity Resort_Chill_118 Washington_DC)
     (inCity Hostel_NH_119 Washington_DC)
     (inCity Apartments_Single_Land_120 New_York)
     (inCity Apartments_Delphin_121 New_York)
     (inCity Apartments_Sky_122 New_York)
     (inCity Residence_Lollipop_123 New_York)
     (inCity Hotel_Paradise_124 New_York)
)

(:goal 
(and (= (visited-cities) 3)
     (> (total-days) 5)
     (> (total-price) (minPriceTrip))
     (< (total-price) (maxPriceTrip))
)
)

(:metric
     minimize (total-interest) 
     minimize (total-price))

)
