;************** INSTANCES GENERATOR **************
; Planification project - Artificial Intelligence


(define (problem tripProblem30)
     (:domain trip-domain)
(:objects
Melbourne Sidney Wellington Beijing Taiwan Tokio Nova_Dheli Paris London Berlin - city
Hostel_Emperor_0 Hotel_Arabiga_1 Hotel_Emperor_2 Residence_Sky_3 Hostel_Delphin_4 Residence_Single_Land_5 Resort_Lollipop_6 Hostel_Emperor_7 Hostel_Lollipop_8 Hostel_Single_Land_9 - hotel
)
(:init
     (= (total-days) 0)
     (= (visited-cities) 0)
     (= (stay Melbourne) 0)
     (= (stay Sidney) 0)
     (= (stay Wellington) 0)
     (= (stay Beijing) 0)
     (= (stay Taiwan) 0)
     (= (stay Tokio) 0)
     (= (stay Nova_Dheli) 0)
     (= (stay Paris) 0)
     (= (stay London) 0)
     (= (stay Berlin) 0)
     (= (minDaysCity Melbourne) 2)
     (= (maxDaysCity Melbourne) 5)
     (= (minDaysCity Sidney) 2)
     (= (maxDaysCity Sidney) 3)
     (= (minDaysCity Wellington) 1)
     (= (maxDaysCity Wellington) 5)
     (= (minDaysCity Beijing) 1)
     (= (maxDaysCity Beijing) 4)
     (= (minDaysCity Taiwan) 2)
     (= (maxDaysCity Taiwan) 4)
     (= (minDaysCity Tokio) 2)
     (= (maxDaysCity Tokio) 3)
     (= (minDaysCity Nova_Dheli) 1)
     (= (maxDaysCity Nova_Dheli) 3)
     (= (minDaysCity Paris) 2)
     (= (maxDaysCity Paris) 3)
     (= (minDaysCity London) 2)
     (= (maxDaysCity London) 4)
     (= (minDaysCity Berlin) 2)
     (= (maxDaysCity Berlin) 4)
     (= (total-price) 0)
     (= (minPriceTrip) 200)
     (= (maxPriceTrip) 800)
     (= (hotelPrice Hostel_Emperor_0) 19)
     (= (hotelPrice Hotel_Arabiga_1) 13)
     (= (hotelPrice Hotel_Emperor_2) 31)
     (= (hotelPrice Residence_Sky_3) 39)
     (= (hotelPrice Hostel_Delphin_4) 24)
     (= (hotelPrice Residence_Single_Land_5) 17)
     (= (hotelPrice Resort_Lollipop_6) 18)
     (= (hotelPrice Hostel_Emperor_7) 24)
     (= (hotelPrice Hostel_Lollipop_8) 15)
     (= (hotelPrice Hostel_Single_Land_9) 10)
     (flight Melbourne Beijing)
     (= (flightPrice Melbourne Beijing) 96)
     (flight Melbourne Sidney)
     (= (flightPrice Melbourne Sidney) 100)
     (flight Melbourne Nova_Dheli)
     (= (flightPrice Melbourne Nova_Dheli) 83)
     (flight Melbourne Wellington)
     (= (flightPrice Melbourne Wellington) 100)
     (flight Sidney Nova_Dheli)
     (= (flightPrice Sidney Nova_Dheli) 81)
     (flight Sidney Tokio)
     (= (flightPrice Sidney Tokio) 95)
     (flight Sidney Taiwan)
     (= (flightPrice Sidney Taiwan) 107)
     (flight Sidney Nova_Dheli)
     (= (flightPrice Sidney Nova_Dheli) 85)
     (flight Wellington Nova_Dheli)
     (= (flightPrice Wellington Nova_Dheli) 89)
     (flight Wellington Beijing)
     (= (flightPrice Wellington Beijing) 97)
     (flight Wellington Taiwan)
     (= (flightPrice Wellington Taiwan) 95)
     (flight Beijing Tokio)
     (= (flightPrice Beijing Tokio) 94)
     (flight Beijing Paris)
     (= (flightPrice Beijing Paris) 94)
     (flight Beijing Taiwan)
     (= (flightPrice Beijing Taiwan) 83)
     (flight Beijing Melbourne)
     (= (flightPrice Beijing Melbourne) 87)
     (flight Taiwan London)
     (= (flightPrice Taiwan London) 86)
     (flight Taiwan London)
     (= (flightPrice Taiwan London) 88)
     (flight Taiwan Beijing)
     (= (flightPrice Taiwan Beijing) 91)
     (flight Tokio Taiwan)
     (= (flightPrice Tokio Taiwan) 99)
     (flight Tokio Wellington)
     (= (flightPrice Tokio Wellington) 80)
     (flight Tokio Nova_Dheli)
     (= (flightPrice Tokio Nova_Dheli) 98)
     (flight Tokio Berlin)
     (= (flightPrice Tokio Berlin) 102)
     (flight Nova_Dheli Taiwan)
     (= (flightPrice Nova_Dheli Taiwan) 109)
     (flight Nova_Dheli Tokio)
     (= (flightPrice Nova_Dheli Tokio) 90)
     (flight Paris Taiwan)
     (= (flightPrice Paris Taiwan) 108)
     (flight Paris Sidney)
     (= (flightPrice Paris Sidney) 97)
     (flight Paris Wellington)
     (= (flightPrice Paris Wellington) 107)
     (flight London Wellington)
     (= (flightPrice London Wellington) 102)
     (flight London Nova_Dheli)
     (= (flightPrice London Nova_Dheli) 81)
     (flight London Melbourne)
     (= (flightPrice London Melbourne) 106)
     (flight London Sidney)
     (= (flightPrice London Sidney) 95)
     (flight Berlin Taiwan)
     (= (flightPrice Berlin Taiwan) 109)
     (flight Berlin Melbourne)
     (= (flightPrice Berlin Melbourne) 89)
     (flight Berlin Sidney)
     (= (flightPrice Berlin Sidney) 87)
     (inCity Hostel_Emperor_0 Melbourne)
     (inCity Hotel_Arabiga_1 Sidney)
     (inCity Hotel_Emperor_2 Wellington)
     (inCity Residence_Sky_3 Beijing)
     (inCity Hostel_Delphin_4 Taiwan)
     (inCity Residence_Single_Land_5 Tokio)
     (inCity Resort_Lollipop_6 Nova_Dheli)
     (inCity Hostel_Emperor_7 Paris)
     (inCity Hostel_Lollipop_8 London)
     (inCity Hostel_Single_Land_9 Berlin)
)

(:goal 
(and (> (visited-cities) 3)
     (> (total-days) 5)
     (> (total-price) (minPriceTrip))
     (< (total-price) (maxPriceTrip))
)
)

(:metric minimize (total-price))

)
